### ISSUE TITLE
Image broken

### ISSUE THREAD

**Issue by jlmontes1697** [algenty/grafana-flowcharting#10]
I created a graphic with images in draw.io. 
When I import them in graffite, the image is broken. 
It is referencing /img/....png and does not exist on the server

**Comment by algenty** [comment]
Hi jlmontes1697,
thx for you feedback and using flowcharting.
Image from draw.io not supported for the time, only absolute image with complete url works (in draw.io, click on add picture)
I hope in next release, not in 0.3 cooming soon, maybe in 0.4.

Best reguards,
Arnaud

**Comment by algenty** [comment]
Hi @jlmontes1697,
images are available with the version 0.5.0, its a snapshot
https://algenty.github.io/flowcharting-repository/CHANGELOG.html

BR,
Arnaud
