### ISSUE TITLE
[SNAPSHOT 0.6.0]Unable to read metrics 

### ISSUE THREAD

**Issue by Sunnor** [algenty/grafana-flowcharting#100]
Hi Arnaud,
    I'm testing your lastest snapshot 0.6.0. But I found an issue.

**[Issue]:**  Unable to read metrics when setting rules.
**[Version]:** snapshot 0.6.0
**[Reproduce Steps]:**
       1. Create Flowcharting panel and add query.  Query inspector show normal response.
![image](https://user-images.githubusercontent.com/49578115/70987949-daebfb80-20fb-11ea-8033-a505faa32a99.png)
      2.  Jump to rules setting, but unable to read the metrics in cell "Apply to metrics".  Also see errors as below
![image](https://user-images.githubusercontent.com/49578115/70988184-5057cc00-20fc-11ea-882c-349a29d0baa6.png)

**[Expected Result]:**  Able to read metrics and show dropdown list like
![image](https://user-images.githubusercontent.com/49578115/70988398-be03f800-20fc-11ea-845d-8bee20a95823.png)

**Comment by algenty** [comment]
Hi Sunor,
try to write /mem/ instead mem

**Comment by Sunnor** [comment]
Still the same, can not read. 

In fact, I found this issue because all my previous graphs can not display the values after upgrade plugin version.

**Comment by algenty** [comment]
What is your previous version ?

**Comment by Sunnor** [comment]
Hi Arnaud,
1. My datasource is open-falcon.
2. My previous production version is 0.4.0,  but those diagrams are displayed normally with version 0.5.0.

**Comment by algenty** [comment]
I don't know open-falcon
I need more trace, are you accept a beta test with logs ?

BR
Arnaud

**Comment by Sunnor** [comment]
sure, what should I do to cooperate with you?

**Comment by algenty** [comment]
i need to build a special version with trace in console

**Comment by algenty** [comment]
[agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/3979360/agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip)

Can you try this version and give me trace in console

**Comment by Sunnor** [comment]
[0.7.0Snapshot.log](https://github.com/algenty/grafana-flowcharting/files/3981676/0.7.0Snapshot.log)
Here are the logs when I proceed the same steps above.

**Comment by algenty** [comment]
I cant found the error because in stack stace, i have no class/js of Flowcharting.
What is your version of grafana ?

**Comment by Sunnor** [comment]
Hi Arnaud,

Sorry for late reply.   My Grafana Version is v6.2.5 (6082d19) Redhat & Centos(64 Bit).  

Do let me know if anything I can help.

**Comment by algenty** [comment]
Can you try to create a new Panel Flowcharting with this query to verify if problem exits when you are directly in 0.6.0 without to pass previous version ?

**Comment by Sunnor** [comment]
Hi Arnaud,
     I tried in 0.6.0 and 0.7.0 by creating a new panel.    The problem is still there with the same error.   But with other plugins like Graph, Singlestat, all of them can display the metric normally. 
![image](https://user-images.githubusercontent.com/49578115/71473491-26945880-2812-11ea-8c6d-f973cc3573a5.png)

**Comment by algenty** [comment]
Ok, are on edit mode when error is displayed

**Comment by algenty** [comment]
after comparing with version 0.5.0, i have an idea.
Can u try it and give me the output console : 
[agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4003073/agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip)

**Comment by Sunnor** [comment]
The new 0.7.0 works! 

I tested with this version:
1.  Created a new panel, the metric can be found in the list, the text mapping also works good.
    ( Here is the console log: [0.7.0snapshot-20191227.log](https://github.com/algenty/grafana-flowcharting/files/4003855/0.7.0snapshot-20191227.log)
2.  I checked several panels I created in previous version, they are displaying normally.

Thank you so much for solving this issue!

**Comment by algenty** [comment]
K, thx for your feedback, i'll build a version without trace.
Be carefull, 0.7.0 is not stable, it's an alpha

**Comment by algenty** [comment]
A version optimized without trace
[agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4006925/agenty-flowcharting-panel-0.7.0-SNAPSHOT.zip)

**Comment by Sunnor** [comment]
It seems this one is same as last special version with trace, as I checked the MD5.   cd38648bc4680cc2e9cd4e7bed2ac6f2

Would you help to check?

**Comment by algenty** [comment]
You can found last build at : 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by Labbs** [comment]
I have the same issue with AWS Cloudwatch datasource and it's work with 0.7.0.

**Comment by algenty** [comment]
i need to publish a fix for 0.6.0

**Comment by algenty** [comment]
Push fix to grafana in progress :  https://github.com/grafana/grafana-plugin-repository/pull/556

**Comment by algenty** [comment]
Hey guys,
Grafana team is very slow to push this update, go to https://github.com/grafana/grafana-plugin-repository/pull/556 and put and inch ;)

**Comment by algenty** [comment]
released and fixed
