### ISSUE TITLE
Can the flowcharts update live?

### ISSUE THREAD

**Issue by GideonWolfe** [algenty/grafana-flowcharting#101]
I have some elements of my chart linked to queries representing the statuses of various systems and services.

For example when my site takes too long to respond, the item turns orange and flashes the error symbol.

However the status does not change unless I refresh the page, which is not very helpful if I want to passively monitor the status of stuff without spamming refresh.

Is there any way to accomplish this?

**Comment by algenty** [comment]
Hi, 
Can you try last version. publication coming soom.
You can download it at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BR
Arnaud

**Comment by algenty** [comment]
0.6.0 published

**Comment by GideonWolfe** [comment]
So I updated to this version, and there's a couple things:

1. I don't think the flowcharts are updating live. I'm looking at a ping response where the variable is bound to text showing milliseconds. I am staring at this for minutes at a time without any of these numbers changing.

2. Previously I had the decimal places setting to `0`, because I don't need accuracy to the hundredth of a millisecond when I'm looking at ping. This update changes the decimal count back to `2` and even when I manually change the number back to `0` and save the dashboard it reverts back to `2`.

**Comment by algenty** [comment]
Hi @GideonWolfe 
When you write "flowchart", it's flowcharting or graph in tooltip ? Graph is not updated when it is visible.
I'll fix decimal in next version.

**Comment by GideonWolfe** [comment]
I am referring to the chart itself.

For example, I used draw.io to get a diagram of a computer, and if a database query returns a response time of over 100ms for that computer, the computer shape will turn orange and the warning icon will blink.

I can only see the state of the computer as it was when the flowchart was loaded. If I load the page and the diagram is green, it will stay green until I refresh the page, even if the warning should show.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bijwaard** [comment]
Hi Gideon,

For me the flowchart is updated automatically with the given update frequency in the top-right of grafana. The fastest update speed is 1 second. In the picture below it is set to 30 seconds. When you have zoomed in, the autofresh is disabled until you select autorefresh again.
![image](https://user-images.githubusercontent.com/6523124/72048101-53d61180-32bc-11ea-9612-496c34fe9bf0.png)
I think the normal autofresh goes down to 5 second, you can insert 1s in the dashboard settings when you want faster updates:
![image](https://user-images.githubusercontent.com/6523124/72048201-8aac2780-32bc-11ea-8037-4d8acad72211.png)
Kind regards,
Dennis

**Comment by GideonWolfe** [comment]
That worked perfectly, thanks!
