### ISSUE TITLE
Edit Draw will result in a "Loading..." endless Draw.io sceen

### ISSUE THREAD

**Issue by raidsec** [algenty/grafana-flowcharting#102]
Hello, 

with your new version (0.6.0) i facing the issue that when I click on "Edit Draw" it will load the draw.io window but the only thing what i see is an "Loading..." circle. See here:

![image](https://user-images.githubusercontent.com/33294982/71522103-9c0c3180-28c3-11ea-8d0e-e259e74da5e3.png)

If i go to draw.io and paste my "Source Content" directly via "Extras" -> "Edit Diagram" it will load the draw without any problems and within one second.

What could be the issue?

**Comment by algenty** [comment]
Hi,
Can you try with the original draw of flowcharting with a new panel ?
Have you an error in console (ctrl+shift+i)

**Comment by raidsec** [comment]
Same issue with a new "panel" (original data) within the same "dashboard". See here:

![image](https://user-images.githubusercontent.com/33294982/71576857-541f2180-2af2-11ea-9002-ab4a63f87a62.png)

There are some issues in the Console, see here:

![image](https://user-images.githubusercontent.com/33294982/71576950-96486300-2af2-11ea-84e8-fd772a21ec60.png)

**Comment by xkilian** [comment]
I get the same problem as well. with 6.5. I was in the middle of a presentation too, did not realize it had broken, I just recently upgraded. ah bork.

**Comment by Sunnor** [comment]
I have the same problem

**Comment by gliu93** [comment]
I have the same problem.

This function was ok until I upgraded the plugin. I forgot what was my old plugin version. I tried multiple computers the problem is the same.

**Comment by gliu93** [comment]
Reverted to 0.5.0 solved the problem.
sudo grafana-cli plugins install agenty-flowcharting-panel 0.5.0

**Comment by algenty** [comment]
Can't reproduce,
Can you try with version 0.7.0 in download section ?
algenty.github.io/flowcharting-repository/

**Comment by algenty** [comment]
@gliu93 
You can also copy/paste source into draw.io until next fix

**Comment by xkilian** [comment]
Same with 0.7.0, endless loading. Cutting and pasting the xml does work.

**Comment by raidsec** [comment]
Could it be a problem with the document.write function? See Chrome warning here:

![image](https://user-images.githubusercontent.com/33294982/72432068-770a3080-3796-11ea-8cf7-7ce5e61879a5.png)

**Comment by algenty** [comment]
Hi @All,

I try again with version 6 and 7, i can't reproduce this bug,
Have you an another panel in your dashboard ?
Which one ?

![image](https://user-images.githubusercontent.com/47012725/72433913-afac0900-379a-11ea-8556-29474faa4b76.png)

**Comment by algenty** [comment]
Anyone can try this fix ? , i rollbacked a part of code from 0.5.0
[agenty-flowcharting-panel-0.6.1-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4064968/agenty-flowcharting-panel-0.6.1-SNAPSHOT.zip)

**Comment by Sunnor** [comment]
your 0.6.1 fixed the issue

**Comment by raidsec** [comment]
I tested it some seconds ago with a Firefox portable (version 72.0.1, 64 bit) and it is working with 0.6.0, see here:

![image](https://user-images.githubusercontent.com/33294982/72435616-c7858c00-379e-11ea-9767-133544d119e6.png)

it is not working with my installed google chrome (version 77.0.3865.120, 64 bit). It is not working with a portable installation of google chrome (version 79.0.3945.88, 32 bit).

@algenty: Which Google Chrome are you using? Could you test it with 77.0.3865.120 or higher? I think its a browser issue.

**Comment by algenty** [comment]
My current chrome version at my work 
Version 72.0.3626.81 (Build officiel) (64 bits)

**Comment by raidsec** [comment]
@algenty: So try to open it with 77 or higher, it should show you the problem. BTW: Error is fixed with version 0.6.1.

**Comment by algenty** [comment]
Push to grafana in progress :  https://github.com/grafana/grafana-plugin-repository/pull/556

**Comment by algenty** [comment]
released and fixed
