### ISSUE TITLE
Same name, same values, Zabbix datastore

### ISSUE THREAD

**Issue by portatip** [algenty/grafana-flowcharting#106]
Used Zabbix datastore. Added a few query, added rules.
![Безымянный](https://user-images.githubusercontent.com/54619629/72526243-0555e380-3877-11ea-89ad-69471d601b0f.png)
![image](https://user-images.githubusercontent.com/54619629/72525451-41884480-3875-11ea-837e-741ecfb63204.png)
what happens: When a trigger fires on a single host, others start fires too. On all rules values become the same as on the host where the trigger worked.
what was expected: one host on map would blink, others should be in ok state.
I also tested if I used items. I think this is due to the same metric names.
![Безымянный](https://user-images.githubusercontent.com/54619629/72526635-edcb2a80-3877-11ea-8e4c-e5b9ce11c061.png)
![image](https://user-images.githubusercontent.com/54619629/72526645-f6bbfc00-3877-11ea-9454-59176c50d725.png)
Grafana v6.5.2
Zabbix Plugin v3.10.5
FlowCharting v0.6.0
Zabbix Server v4.0.9

**Comment by algenty** [comment]
Hi @portatip 
Thx for your feedback but at this time, i'am not unable to test zabbix
in issue #90 @nmoreaud uses flowcharting with zabbix

**Comment by Gainutdinov** [comment]
faced the same issue :(
@portatip did you find workaround? 
Maybe adding additional metrics for alerted triggers in zabbix with be solution?

**Comment by KatarzynaPiorkowska** [comment]
Hi, I have the same problem. Any chance of fixing it?

**Comment by algenty** [comment]
I have no zabbix to test that
If i post a version with more trace
You can test that ?

**Comment by KatarzynaPiorkowska** [comment]
Thanks for your response. Yes, I can test the new version.

Fixing it would be really helpful, as we use your plugin for creating network maps. We would like to show Zabbix triggers on a map, but right now when trigger appears on one device, all devices on a map are in alarm. It defeats the purpose of a map, because it's impossible to attribute trigger to exact device.

**Comment by algenty** [comment]
I sent an issue to alexander for help.
I see in zabbix doc http://zabbix.grafana-zabbix.org/api_jsonrpc.php but i can't to connect to.
Do you know a demo zabbix server ?

**Comment by algenty** [comment]
Ok, with muutech site, i found a zabbix server
Install that, 
[agenty-flowcharting-panel-0.6.2-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4303443/agenty-flowcharting-panel-0.6.2-SNAPSHOT.zip)
open chrome, call dashboard and give me the result under GF WARN : data 
like this (i dont need datapoints values, just values for alias, targets  and refId
{alias: "M1", target: "M1", datapoints: Array(1081), unit: undefined, refId: "A", …}
alias: "M1"
target: "M1"
unit: undefined
refId: "A"
meta: undefined

BR
Arnaud

**Comment by KatarzynaPiorkowska** [comment]
![grafana_console_warnings](https://user-images.githubusercontent.com/24686826/76221038-bbef9800-6218-11ea-8e55-ea3a59ad96e5.PNG)

**Comment by algenty** [comment]
Thx,
I see in this result, the same name. For information, data has returned by grafana.
You cannot add alias in zabbix metrics ?

**Comment by algenty** [comment]
can you make a snapshot of your query ?

**Comment by KatarzynaPiorkowska** [comment]
![zabbix_query](https://user-images.githubusercontent.com/24686826/76514847-d1eb9b80-6458-11ea-8a6b-1f3bd7774fa0.PNG)
As you can see, there is no possibility of adding alias. Do you think it would fix this problem? If so, I'll open an issue for Zabbix plugin.

**Comment by algenty** [comment]
At this time, i can't resolve it if data objects have the same name.
Can you try to change your panel with a graph type to to see if in legend, all metrics have the same name ?

**Comment by petryx** [comment]
Hi algenty

I tried, but did not work.

**Comment by jorlandobr** [comment]
@portatip, @KatarzynaPiorkowska, @petrix

I had the same problem with my triggers. Various devices, a trigger in one would set the others.

It appears to be solved on the new version (0.9.0) of flowcharting.

To succeed I created a trigger and set the hostname to /.*/ (all devices), then selected the metric (power supply status, interface status, ping...) for that trigger.

Then I would add a new mapping rule and on that rule I would select the specific device that I want to map the trigger.
![grafana](https://user-images.githubusercontent.com/22829448/85187385-b8d36180-b275-11ea-8ea5-053d75c12edb.png)

**Comment by algenty** [comment]
Ok i close it,
Thx for your feedback
