### ISSUE TITLE
E2E documentation or tutorials

### ISSUE THREAD

**Issue by indranildev** [algenty/grafana-flowcharting#107]
Hello ,

I have been looking in this project and could not find an easy or E2E tutorial explaining steps on integration with data sources.
for example if I use promethus as my data source and want to configure metrics how do I do that ?
It would be really helpful if there are some tutorials or docs regarding this.

**Comment by algenty** [comment]
https://algenty.github.io/flowcharting-repository/STARTED.html

**Comment by indranildev** [comment]
I have already gone through this documentation, but specifically with promethus metrics how can add the values ?

**Comment by indranildev** [comment]
Hello,
I need some help to understand on how to integrate Prometheus metrics with this plugin.
any platform where I can explain you my scenario ?
