### ISSUE TITLE
Not an issue: Great job!

### ISSUE THREAD

**Issue by cukal** [algenty/grafana-flowcharting#11]
Hi, we've been using mermaid graph extensively but found your plugin when upgrading our Grafana environment, I installed the zip you posted as reply on another issue. 
We're starting to move all our mermaid graphs to mxgraph / draw.io now ;)

You nailed it with the scaling, inline editor, link-picker and the overall functionality, really great job! 

Thanks for sharing this!

**Comment by algenty** [comment]
Thanks a lot, it's a pleasure to read this
0.3.0 coming soon bug grafana is very slow to publish
dev is finish, test in progress (branch function_6_flowchart)

Change log : 
## [0.3.0] - 2019-05-01
### Added
    - Full review of code (ES6 Class mode)
    - Unit test with jest to increase quality
    - Fill/text/stoke rules on the same object
    - Mapping selector helper
    - Icon overlay state
    - Implemented Texton state input
    - new inspect Tab with :
      - Renamer ID (double click on ID)
      - State status
      - Debug mode
###
    - Substring replace on text (Issue #8)
    - Editor object not found Exception (Issue #1)

If you want to become a beta tester, no pb.

Best reguard
Arnaud

**Comment by cukal** [comment]
Thanks! I just installed 0.3, inspect is a nice touch!
