### ISSUE TITLE
Process Flow Diagram

### ISSUE THREAD

**Issue by DornaForoughpour** [algenty/grafana-flowcharting#112]
Hi,I'd like to know is there any way to create a  process flow diagram with animation?
I need to use a diagram with animation to indicate the general flow of processes of threads.

**Comment by algenty** [comment]
Hi @DornaForoughpour 
No animation at this time, maybe in next version ;)
You can see examples on twitter
https://twitter.com/gf_flowcharting

**Comment by DornaForoughpour** [comment]
Thank you for reply. Can you estimate when the next release is?

**Comment by algenty** [comment]
no date planified, need to define animation first, i have no idea

**Comment by bijwaard** [comment]
If dynamically updating text labels, dynamic color changes, and tooltips with graphs are animation enough, FlowCharting is kind of ready with updates in the pace of grafana (minimum 1 second update rate).
Are your processes and threads stored in a database like influxdb, or do you want to feed them to grafana in another way such as the JSON datasource?
One of my usages of FlowCharting is for updated sensor measurements and derived values that are calculated in a distributed dataflow, and conveyed via a JSON datasource. Output ports turn red/green depending on configured thresholds for their value.
![image](https://user-images.githubusercontent.com/6523124/73215695-dd0e9480-4154-11ea-9253-9990fb56611d.png)
Another of my FlowCharting usages is to show a selection of derived measurements from an influx database, inverter icons turn greener when there is more solar production;-)
![image](https://user-images.githubusercontent.com/6523124/73217688-af2b4f00-4158-11ea-9abf-7e75b1659f7b.png)

Kind regards,
Dennis

**Comment by algenty** [comment]
thx for your explain dennis

**Comment by CrashLaker** [comment]
Hi @bijwaard 
what a busy graph. great view.
mind to ask you did you manually arrange the graph on these parts?
![image](https://user-images.githubusercontent.com/4432491/79691445-ed0ab180-8235-11ea-9cfe-c8d3caef910b.png)

i tried porting some of my **outside** views to flowcharting without success as it becomes too much work to just place everything.
![image](https://user-images.githubusercontent.com/4432491/79691490-3e1aa580-8236-11ea-9f4e-7ab0057adf4b.png)

**Comment by bijwaard** [comment]
Hi CrashLaker,

The communication between our distributed sensors and smart nodes may indeed look quite complicated. My diagrams work the other way around however, I graphically design the internals of my sensor and other devices, parse the graphML file and generate a start script for all the internal C++ and Python DSPs that process the synchronized sensor data on each device.

I got fed up with doing this manually and now have one output bar for all the DSPs on a sensor;-)
![image](https://user-images.githubusercontent.com/6523124/79695297-5ad6cd80-8276-11ea-8a99-010622cd7ae6.png)

Kind regards,
Dennis

**Comment by xkilian** [comment]
0.8 now has animated events. Arnaud has outdone himself on this last version.
