### ISSUE TITLE
Mapped values in thresholds for SNMP (Zabbix)

### ISSUE THREAD

**Issue by jorlandobr** [algenty/grafana-flowcharting#113]
The threshold now is defined as two values, with the extremes being error and ok and the range between these values a warning state.

For SNMP (using Zabbix datasource) queries sometimes are mapped to values and I can't find a way to use use threshold rules to do it. Simple example, power supplies from RAS servers return 3 values:

1 - absent
2 - ok
3 - failed

If I use 1,2 (critical, ok) equipments with status 1 gets orange, I was expecting red.

Is it possible an improvement to define threshold as 3 values or maps of values?

For example, slot status have values from 1 to 9:

                            operStateDown( 1 ),
                            operStateUp( 2 ),
                            operStateDiag( 3 ),
                            operStateCoreDump( 4 ),
                            operStateLoading( 5 ),
                            operStatePost( 6 ),
                            operStateNone( 7 ),
                            operStateOccupied( 8 ),
                            operStateMaintenance( 9 )

Green for 2,7 or 9
Orange for 3,5,6 and 8
Red for 1 and 4

**Comment by algenty** [comment]
You can use string and mapping text for it

**Comment by jorlandobr** [comment]
Thanks for the instruction, I didn't thought doing this way! :-) But as nottend in #90  and #106, it seems that triggers in one element propagate to all others.

As you suggested I created a query and mapped string values:
![flowchart_query](https://user-images.githubusercontent.com/22829448/73138221-181ea400-403f-11ea-8b0d-c7eb596e1e8b.png)

Then I started creating generic rules that could use that query, using regex so all six devices would use the same query:
![flowchart_rules](https://user-images.githubusercontent.com/22829448/73138248-5ae07c00-403f-11ea-942d-e8931de1875c.png)

I can test different scenarios, since one device is disconnected (all queries made by Zabbix timeout)), 2 have both power supplies OK, 2 have only PS A OK, and one have PS A OK and PS B failling all day long.

So the visualizaton for PS A is ok, since none is failling (even the device that is disconnected shows PS A as ok, but that is not a problem right now)

The visualization for PS B is wrong, since one is defective, all devices will have PS B allarmed, no matter PS B status on the device.

I thought that it could be that I was using regex, so I did individual queries and rules for PSB and when I created one rule for a device with PS B down, the others started showing alarms on PS B.

On the picture the allarmed PS B is from NASSPOMB01, that has the graphic hint showing it as ok. I think that behaviour is not eclusive to Zabbix and it is no intended to work this way. If you need more info, just ask! :-)
![flowchart_individual_rules](https://user-images.githubusercontent.com/22829448/73138398-f3c3c700-4040-11ea-9759-534dc963b7d7.png)

**Comment by algenty** [comment]
In next version for this week, you can define more colors :
https://twitter.com/gf_flowcharting/status/1242192224106024963

**Comment by jorlandobr** [comment]
I tried the new version and could implement a very functional map with it!

I'll also take a look on what was posted on #90 and #106, these bugs seems to be solved, now you can have one trigger with a regex for the device name and you can filter the trigger on the mapping.

Thanks a lot!
