### ISSUE TITLE
Grafana's rendering feature on FlowCharting panel does not work

### ISSUE THREAD

**Issue by qrtalaci** [algenty/grafana-flowcharting#114]
I would like to create .PNG snapshot images for reporting purpose and tried to invoke the rendering URL on one FlowCharting panel:

![image](https://user-images.githubusercontent.com/639291/73690496-c924de80-46d0-11ea-95de-e0c68d72bb58.png)

I tried it with the deprecated PhantomJS renderer and with the new grafana-image-renderer plugin as well, booth give TimeoutError on FlowCharting panels.

This is the debug printout of grafana-image-renderer plugin when I invoke the rendering:
```
{"level":"info","message":"Render request received', 'url', http://grafana:3000/d-solo/EYdpLlaZk/borg-warner?orgId=1&from=1580291897741&to=1580313497742&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1"}
{"0":"url","1":"http://grafana:3000/d-solo/EYdpLlaZk/panel?orgId=1&from=1580291897741&to=1580313497742&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1","2":"error","3":{"name":"TimeoutError"},"level":"error","message":"Render request failed"}
{"message":"::ffff:172.23.0.4 - - [29/Jan/2020:15:59:25 +0000] \"GET /render?domain=grafana&encoding=&height=500&renderKey=xxx&timeout=60&timezone=Europe%2FBudapest&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FEYdpLlaZk%2Fpanel%3ForgId%3D1%26from%3D1580291897741%26to%3D1580313497742%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DEurope%252FBudapest%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Go-http-client/1.1\"\n","level":"info"}
```

Is it possible to create a snapshot of one FlowChart panel that way? Is it a bug or something should be implemented to make these panels renderable?

**Comment by algenty** [comment]
Need to try, never tested

**Comment by taemmert** [comment]
The feature supports to share with externals a quasi online view of a dedicated FlowChart panel. Does anybody have any idea how to solve it?

**Comment by algenty** [comment]
For information, work in progress, i added this.renderingCompleted(), render function give a result but without colors ;
![chrome_yvn8vIxAqm](https://user-images.githubusercontent.com/47012725/77236432-ab4b0480-6bbe-11ea-8c13-62676e3d78f6.png)

**Comment by algenty** [comment]
I add link with grafana issue
https://github.com/grafana/grafana-image-renderer/issues/67

**Comment by ryantxu** [comment]
@algenty -- you may want to add a slight delay after you think it is done before calling renderingCompleted()

**Comment by algenty** [comment]
Hi @ryantxu,
How do you do ?
I'll try it
A little question, with "Direct link rendered image" called, which event is called ? 'render' ? 'snapshot' ?
In code :
    // Events Render
    ctrl.events.on('render', () => {
      this.render();
    });

**Comment by algenty** [comment]
It works with a delay, but i'am not satisfied with this method because display is longer
![chrome_xsALp2QlFG](https://user-images.githubusercontent.com/47012725/77237133-c53c1580-6bc5-11ea-9466-4463a8776f95.png)

**Comment by qrtalaci** [comment]
Thank you, it works like a charm :)

**Comment by taemmert** [comment]
Thank You very much guys!
Stay healthy!

**Comment by algenty** [comment]
You'r welcome :)
Be carefull, disable animation in flowchart section  if u use rendering
thx @ryantxu for your help
