### ISSUE TITLE
Color stay after selecting another value from Variables 

### ISSUE THREAD

**Issue by qbeacco** [algenty/grafana-flowcharting#115]
Good morning,

As you can see, when I selected a value from Grafana Variable, it stays on (red color, the previous color).

![image](https://user-images.githubusercontent.com/2326885/74016010-023fa600-4992-11ea-8a4f-68000d38799c.png)

Best regard.

**Comment by algenty** [comment]
Hi @qbeacco 
At this time, if you want to use a variable, you need to extract source of flowcharting

BR
Arna

**Comment by qbeacco** [comment]
HI @algenty 
What would you say about "extract source of flowcharting" ?

Best regard
@qbeacco.

**Comment by qbeacco** [comment]
I think you mean XML content of FlowCharting from Draw.io ? (File -> Export as -> XML)
I already use XML content for my Panel (here in compressed format) and I have this problem.

Best Regard,
@qbeacco.

**Comment by algenty** [comment]
yes, you need to click on button uncompress/extract
In you xml, you need to see your variable like ${variable}

**Comment by qbeacco** [comment]
Hi, from the new version 0.7.0. It works when I disabling animation.

Thanks a lot.
