### ISSUE TITLE
Query name of metrics

### ISSUE THREAD

**Issue by Maxiz80** [algenty/grafana-flowcharting#117]
I'm doing a very big flowchart with a lot of metrics.
And I've noticed that once you arrive to "Z" the next metric has NO NAME.
And that would not be a big problem since you can still use in visualization.
But the problem come when you need to delete or move up/down.
If you try to delete it will delete the last one with no name and you cannot move up/down.

**Comment by algenty** [comment]
Yes, that is the limit of Grafana, see issues in Grafana Githut
The only solution is use group by if your datasource is influx or same solution.
Like this
select value from mytables group by host

**Comment by Maxiz80** [comment]
I don't find the issue but i trust you :)

**Comment by algenty** [comment]
see that
https://github.com/algenty/grafana-flowcharting/issues/96
