### ISSUE TITLE
RGBA color opacity is ignored after refresh

### ISSUE THREAD

**Issue by peterstefanek** [algenty/grafana-flowcharting#118]
Hello.
I have floorplan with room overlays. Room overlay color is set according to the current temperature. I am using RGBA colors with opacity. After refresh, color opacity is ignored.

![floorlan_opacity](https://user-images.githubusercontent.com/28655688/75246281-c00ac700-57cf-11ea-9f92-c3b9817c2cee.png)
![floorlan_opacity_missing_after_refresh](https://user-images.githubusercontent.com/28655688/75246289-c5681180-57cf-11ea-96ee-6b378159cd26.png)
![floorlan_opacity_missing_edit](https://user-images.githubusercontent.com/28655688/75246299-c8630200-57cf-11ea-8f3b-84b3946d4ec3.png)

**Comment by algenty** [comment]
Hi @peterstefanek,

I tested that now, and its work for me. on your floorplan, place a rectangle on front and modify opacity to 30% or less
![image](https://user-images.githubusercontent.com/47012725/75263069-c019bf80-57ed-11ea-9643-b916af1bdcac.png)

In flowchart, select the rectangle and configure threshold, that is the result for me in 0.6.1 :
![floorplan](https://user-images.githubusercontent.com/47012725/75263753-b47ac880-57ee-11ea-81bf-469e5c70059f.png)

P.S : Nice floorplan !
In next version of flowcharting, you'll can choose more than 3 colors with a gradient.

**Comment by peterstefanek** [comment]
I works :)
In version 0.4, it was enough to set the RGBA color with opacity in Grafana without setting the opacity in draw.io diagram. After upgrading to 0.6, the behavior is as I described, but your workaround works, so it's okay.

Thank you.
