### ISSUE TITLE
duration (s) 

### ISSUE THREAD

**Issue by cukal** [algenty/grafana-flowcharting#12]
I'm on 0.3.0-SNAPSHOT & using a query metric that returns a value that can be used with time-duration(s) and a numerical threshold: 

```probe_ssl_earliest_cert_expiry{instance="<hostname>",job="<jobname>"}-time()``` 

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/627072/57163100-7ee49900-6df0-11e9-9303-a16d028831db.png">

To use the numerical threshold the unit needs to be time/duration(s) but it's impossible to select it in the dropdown, it can however be changed in the json: 

```          "unit": "dtdurations",```

After that it works like a regular panel: changing color to red as the expiration date comes closer.

Thx!

**Comment by algenty** [comment]
I'll try to reproduce it and i come back.

**Comment by algenty** [comment]
Fixed
Download last snapshot and test it.
https://algenty.github.io/flowcharting-repository/ARCHIVES.html
