### ISSUE TITLE
Weird behavior in Mapping

### ISSUE THREAD

**Issue by radimmachu** [algenty/grafana-flowcharting#122]
Hi,

I am using Flowcharting in Grafana v5.4.3.
I have a dashboard with almost twenty metrics (and mappings).
Plugin worked great in the beginning, but now I have find out this bug:
- I am not able to add new working mapping: when it as added, it does not read values from metric (it shows "value : []" in the mapping header).
- if I add a new mapping by cloning an existing rule, data connection to metric works! But in this case, new added mapping inherits color setting in Thresholds section: if I change colours in a new cloned mapping, colours are also changed in the mapping which was a source for clone.

Thanks for an advice,

Radim

**Comment by algenty** [comment]
Hi, 
See https://github.com/algenty/grafana-flowcharting/issues/96
