### ISSUE TITLE
can't configure different Thresholds directions (Ok > Warn > Critical) for different mapping rules

### ISSUE THREAD

**Issue by arnitolog** [algenty/grafana-flowcharting#124]
Hello,
I'm trying to configure different thresholds directions (Ok > Warn > Critical) for different mapping rules. But seems like they apply globally for all available mappings.
Here what I have: 
-an existing mapping for Elasticsearch
![image](https://user-images.githubusercontent.com/34036079/76187851-25eb4b80-61df-11ea-8ca6-3e554a7880b1.png)
![image](https://user-images.githubusercontent.com/34036079/76187870-33083a80-61df-11ea-871a-d7fa9e5704db.png)
- an existing mapping for another system component:
![image](https://user-images.githubusercontent.com/34036079/76187929-63e86f80-61df-11ea-9e5f-f73bd2d62f33.png)
And when I tried to add the third component (Kafka) with the opposite threshold direction (Critical > Warn > Ok), the first two changed their color to red:
![image](https://user-images.githubusercontent.com/34036079/76188040-ba55ae00-61df-11ea-94d0-ae62f30e3142.png)

![image](https://user-images.githubusercontent.com/34036079/76188087-deb18a80-61df-11ea-8329-0b4898c2d098.png)

is it a bug, or am I doing something wrong?

**Comment by algenty** [comment]
Hi @arnitolog 
Thx for this feedback.
Stroke and fill works only for drawio shapes, for pictures use border.
If in xml, you see base64 or an url, it's a picture otherwise it's a shape
See that : 
https://github.com/algenty/flowcharting-repository/blob/master/images/colormode_ani.png?raw=true

**Comment by arnitolog** [comment]
@algenty what I'm trying to do is just have different directions for thresholds. I click on `Invert ` button for one of the rules. And seems like it affects all existing rules

**Comment by algenty** [comment]
ok, it's maybe a bug, when you clone rules, can you try to create rule without clone options ?

**Comment by arnitolog** [comment]
yeah, the new one works for me thanks a lot. This is really cool plugin. Thank you very much

**Comment by algenty** [comment]
you're welcome, i'll try this bug this week to fix it

**Comment by algenty** [comment]
Ok, can reproduce bug, i'll fix it

**Comment by algenty** [comment]
Can you try 0.7.0 snapshot in https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by arnitolog** [comment]
looks good to me. Thank you
