### ISSUE TITLE
Kubernetes shape doesn't display correctly in Grafana

### ISSUE THREAD

**Issue by arnitolog** [algenty/grafana-flowcharting#125]
For some reason Kubernetes blocks do not display correctly in Grafana.
Here is what I have in the editor:
![image](https://user-images.githubusercontent.com/34036079/76189270-ee7e9e00-61e2-11ea-8c58-f505eff52009.png)
And here is how it is displayed in Grafana:
![image](https://user-images.githubusercontent.com/34036079/76189314-07874f00-61e3-11ea-8d5c-0a3662f7b029.png)
Kubernetes blocks substituted by blue squares

**Comment by algenty** [comment]
which versions of flowcharting ?

**Comment by arnitolog** [comment]
plugin version: 0.6.1

**Comment by algenty** [comment]
Can you give me the name of this shape ?
Maybe, need to update drawio libs il flowcharting

**Comment by arnitolog** [comment]
I guess the name is `Kubernetes`
![image](https://user-images.githubusercontent.com/34036079/76216217-da559380-6218-11ea-884f-92e95991c21a.png)

**Comment by algenty** [comment]
Can you try 0.7.0 snapshot in https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by arnitolog** [comment]
it works for me. Thanks a lot

**Comment by algenty** [comment]
You're welcome
