### ISSUE TITLE
Changing shape size parameter

### ISSUE THREAD

**Issue by coussej** [algenty/grafana-flowcharting#126]
Hello, 

I am using your plugin in an industrial context, to mimic typical operator control screen. VERY COOL! ;-)

I was wondering if there is a possibility (or in the future) to change a height or width parameter of a chape. I want to be able to change the fill level of a tank picture based on the actual value:

![image](https://user-images.githubusercontent.com/9944663/76516482-cbaaee80-645b-11ea-99cf-80513146ff1a.png)

Thanks for your feedback!

**Comment by algenty** [comment]
Not at this time, maybe in a next version.
But you can cheat, put more shapes 'froides' on same place with serval height like this
EAU_ENTRE_10-20
EAU_ENTRE-20-40
EAU_ENTRE_40-60

For EAU_ENTRE_0-20, select threshold 10,20, thats mean between 0 to 10 => OK
10 to 20 => Warn
Upper 20 => Error
And select transparent colors for OK et ERROR, bleu for WARN, select object EAU_ENTRE_0-20 in color mapping

Create a new rule and repeat for EAU_ENTRE-20-40, with threshold 20,40
ect ...

**Comment by coussej** [comment]
Ah yes, I was thinking in something like that. Thanks for your input, and again, great work on the plugin!

**Comment by algenty** [comment]
where in belguim ? i live in rijsel ;)

**Comment by coussej** [comment]
Ah, we're from Ghent! Our company (factry.io) specializes in using open source for manufacturing and process industry. We should have a chat sometimes!

**Comment by paregupt** [comment]
Hello, I am interested in this too. Here is my use-case: I am trying to show network load-balancing at scale. If I can adjust the width of the elements based on the usage, many such components side-by-side can be a great representation. Honestly, I was expecting some other panel to do this but all of them have limitations. Thanks

**Comment by algenty** [comment]
already available in 0.8.0

**Comment by algenty** [comment]
Hi @coussej 
I saw your example at https://demo.factry.io/d/ZhjweprWk/city-water-tank-flowchart?orgId=1&from=1592313404205&to=1592335004205
Very nice
For more beautifull effect, try to install 0.9.0 and activate Shared Cross Hair (CTRL + O), when you move mouse on panel "City Water tank", the flowcharting changes like this
![floorplan_graphhover](https://user-images.githubusercontent.com/47012725/84804897-b36ee080-b003-11ea-88f7-f6ceae372846.gif)
