### ISSUE TITLE
Step by Step Instruction For Setting up Metrics and Assign Mappings To Flowchart Controls

### ISSUE THREAD

**Issue by cpsarathi79** [algenty/grafana-flowcharting#129]
I couldn't understand how to map metrics to individual objects in Flowchart.

Is there any video or step by step instructions available? I have gone through 'Getting Started' links under Github but not able to make it.

In the "mapping" section I see option to select the metrics (sql query), but I don't know how to apply that to a specific object in flowchart?

**Comment by algenty** [comment]
Are you novice in Grafana ?
To apply rules to an object, in color mapping, click on link icons and select object

**Comment by cpsarathi79** [comment]
Yes, thanks much for your reply :)
