### ISSUE TITLE
Duplicate Panel

### ISSUE THREAD

**Issue by cukal** [algenty/grafana-flowcharting#13]
After duplicating a Flowcharting panel changes done on the duplicated panel are also saved in the source panel and after a refresh both panels appear the same.

**Comment by algenty** [comment]
Hi cukal,
thx for feedback 
which version do you use?
Can you try 0.3.0 in https://github.com/algenty/flowcharting-repository/tree/master/archives please.

Best reguards,
Arnaud

**Comment by cukal** [comment]
Yes, I’m using 0.3.0.
I’ll try if it happens with the default panel without changing anything.

**Comment by cukal** [comment]
I must have messed something up, with the default example panel it works perfectly.
