### ISSUE TITLE
Flowchart first time load is very slow

### ISSUE THREAD

**Issue by Codeout256** [algenty/grafana-flowcharting#131]
Hello @algenty 
I have been using the agenty-flowcharting-panel @ 0.6.1 version and I currently have around 120 queries and mapping rules in a current dashboard, What I have observed is it loading very slow when it loads first time then the dashboard refresh happens fine.
Since I have multiple links to other Grafana dashboards from one dashboard it is pretty difficult to wait for the loading... it takes around ~30 secs to load a dashboard.
I check the query execution time in prometheus which hardly takes 950ms for 120 queries.

Any issues with the version ? How can I optimize the load time ?

**Comment by algenty** [comment]
Can you try 0.7.0, in this version, u can reduce number of rules

**Comment by Codeout256** [comment]
can I have multiple queries & labels in one rule ?

**Comment by algenty** [comment]
Yes, you can, use a regex like /.*CPU.*/

**Comment by Codeout256** [comment]
Okay so let me explain your scenario.

So I have three queries & their values like this (prometheus) :

Appmetrics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 0

Apprespmterics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 12.09
Apploadmetrics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 22.4

All the three queries are mapped to a single shape and according to value of "Appmetrics" I am changing the colour of the shapes and other two "Apprespmterics" , ApploadmetricsI am using there values (label) and plotting graph on the shape.

Currently I have them in three separate rule map, How can I reduce this using v.07.0 ? Any idea

**Comment by Codeout256** [comment]
@algenty  I could not use three queries in a single rule map, Do you know any way out here.

**Comment by algenty** [comment]
without context, i can't help you

**Comment by Codeout256** [comment]
@algenty Here is the context below :

I have three queries in prometheus as mentioned below (a), (b), (c) :

(a). **Appmetrics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 0**

(b) **Appresponsemterics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 12.09**

(c) **Appcpuloadmetrics{instance="10.78.22.6:9900",job="Grafanadas",appid="7889",appname="akamaihy"} 22.4**

Currently all the three queries above are mapped to a single shape using 3 different **rule** and according to value of "Appmetrics" i.e, query **(a)** I am changing the color of the shape(red/green-->threshold(0,1)).

and the other two queries **(b)** "Apprespmterics" (gives value for application response time) & **(c)** Apploadmetrics" (gives value of application CPU load) I have created two rules each to map and then plotting graphs on the values (usinf display metrics in the **rule** option for same shape.

So Currently I have three separate rule map with 3 different queries applied on the same shape.
So based on my scenario is it possible to reduce these rules to only one rule and apply these 3 queries out there ?

Thanks !!

**Comment by Codeout256** [comment]
Any help @algenty

**Comment by algenty** [comment]
try without shapes, with an empty graph
It's perhaps downloaded logo

**Comment by algenty** [comment]
You can try this version,
Open console and give me the tables
[agenty-flowcharting-panel-0.8.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4535560/agenty-flowcharting-panel-0.8.0-SNAPSHOT.zip)

**Comment by algenty** [comment]
no anwer, i close
