### ISSUE TITLE
Count Aggregation not show the correct value

### ISSUE THREAD

**Issue by fadjar340** [algenty/grafana-flowcharting#134]
Hi,
I have count metric using elasticsearch and the result was correct, then I put into the flowcharting rule using Aggregation Count, then I enable metric display. 
The metric display show the correct value, but the information value in the right side of the Rule name, was not correct and the impact is the alert was not correct also.
I think this is the relation of the metric display and calculation of the metric value not connected.
If I use the other aggregation, the value was correct.

Regards,
Fadjar340

**Comment by algenty** [comment]
Hi,
Can u take a screenshot please ?

**Comment by fadjar340** [comment]
This the two of the Aggregation Count
![Screenshot from 2020-04-03 18-51-05](https://user-images.githubusercontent.com/1247073/78358318-32e03c80-75dd-11ea-9a01-fb2bf7f89be1.png)
![Screenshot from 2020-04-03 18-52-33](https://user-images.githubusercontent.com/1247073/78358326-34aa0000-75dd-11ea-9fe5-4c9dbeac41dd.png)

The first image, should be 0 and the second image the value should be the bar count.
The graph is correct, but the value...

Regards,
Fadjar340

**Comment by algenty** [comment]
Can u try last version please, maybe bug is fixed

**Comment by fadjar340** [comment]
Already use version 0.7.0

**Comment by algenty** [comment]
Ok, i understand count in Flowcharting counts the number of serie.
If your query is already a count, you have ony one serie then 1.
Use last if you count in query

**Comment by algenty** [comment]
no news, i close it
