### ISSUE TITLE
New Aggregation option returning the Last value including null

### ISSUE THREAD

**Issue by IT024551** [algenty/grafana-flowcharting#135]
Hi,
I would like you to evaluate a small enhancement which would help me building a dashboard where I use your wonderful plugin.
In short, I would need to select as Aggregation rule an option similar to "Last" but returning even the null value and not as today the last value not null.

I noticed that several plugins (Stat, Gauge and some other) already offer that option.
To avoid breaking things, you could name such new aggregation type as "Current", for example.

Thank you for your job.
Lorenzo

**Comment by algenty** [comment]
implemented in 0.9.0
