### ISSUE TITLE
Add support for multiple link mappings for the same shape

### ISSUE THREAD

**Issue by nitzanharel** [algenty/grafana-flowcharting#137]
If multiple mappings exist for the same shape, on click - open a menu to choose which link to go.
Just like here : https://grafana.com/blog/2019/08/27/new-in-grafana-6.3-easy-to-use-data-links/

**Comment by algenty** [comment]
Hi, 
As this time, it's not possible, only the last link in rule link opens, link function is a draw.io function. If you want multi link, u need to open an enhancement at draw.io.
But you can add icons or mini shapes on your shape like this :
![image](https://user-images.githubusercontent.com/47012725/78470177-9d04f880-7727-11ea-89ae-3aa0880a4733.png)

**Comment by nitzanharel-branch** [comment]
@algenty  - you can have multiple links on draw.io
they all open at the same time on a click though:
data:action/json,{
  "actions": [
    {
      "open": "http://google.com"
    },
    {
      "open": "http://yahoo.com"
    }
  ]
}
Is this something that can still be achieved ?

**Comment by nitzanharel** [comment]
@algenty  - you can have multiple links on draw.io
they all open at the same time on a click though:
data:action/json,{
"actions": [
{
"open": "http://google.com"
},
{
"open": "http://yahoo.com"
}
]
}
Is this something that can still be achieved ?
