### ISSUE TITLE
Can't change threshold colors

### ISSUE THREAD

**Issue by cukal** [algenty/grafana-flowcharting#14]
Can't change threshold colours: https://monosnap.com/file/7wDMBApYHRiO7k0TPalt6RXxx4g6H5

**Comment by algenty** [comment]
Hi, i'll see, ... this is a mistery, I'll try to reproduce it

**Comment by algenty** [comment]
Fixed,
Download snapshot in https://github.com/algenty/flowcharting-repository/tree/master/archives
0.3.0 will be pushed this week i hope on grafana. Test and docs at 90%
Thx a lot for your tests
