### ISSUE TITLE
Change color of custom SVG imported to Draw.io

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#144]
Hi all.

I'm trying to dynamically change the colors of custom SVG shapes imported to Draw.io wihout success.. Does anyone know what am I missing?

![image](https://user-images.githubusercontent.com/4432491/78932618-3f054780-7a7e-11ea-909d-d9c31fc40b65.png)
From the image above I'm able to change the colors of the three dots on the left (circle shapes from draw.io) but the shapes on the right although I'm able to change their color inside Draw.io they doesn't seem to be affected by Flowchart.

![image](https://user-images.githubusercontent.com/4432491/78932821-95728600-7a7e-11ea-9bda-f8c6777d53bc.png)

They all seems to be working

![image](https://user-images.githubusercontent.com/4432491/78932873-a9b68300-7a7e-11ea-84c5-e487660012b9.png)

**Comment by nmoreaud** [comment]
Hello @CrashLayer,
Your SVG seems to embed raster images, which you wont be able to color with this plugin (`<image href="data:image/svg+xml;base64... />`).
Your shapes are filled with plain color, you should be able to draw them with vectorial elements (ex polygon).

>  I'm trying to achieve the same results but I couldnt find a way to programatically position it (I'm still loading a buch of SVG shapes and manually positioning them to form a country or continent) and to dynamically change its color based on grafana's metrics.

It's quite hard to create such a map by yourself. However, there are a lot already existing on the web, you should google for svg maps. Then you can add ids or classes to some elements to manipulate them with this plugin. This extension would also make the job : [marcuscalidus-svg-panel](https://grafana.com/grafana/plugins/marcuscalidus-svg-panel).
There are also js libraries that generate SVG maps such as [this one](https://jvectormap.com) which is ultimately based on a polygon dataset.

**Comment by algenty** [comment]
Hi @CrashLaker 
@mmoreau is right
It's not a shape but an image, you need to use border or backgroud to colorize it

**Comment by CrashLaker** [comment]
Bingo!
@nmoreaud I've actually just read your other comment mentioning you used SVG panel instead and decided to give it a try.
I thought this was the case for flowcharting but SVG panel is pretty powerful too as it lets you to code javascript on every metric pull.
So this indeed shouldn't be possible with flowcharting as it only supports Draw.io's XML and a polygon + shaped SVG turns to be that `data:image/svg+xml;base64... ` inside draw.io.. right @algenty ?

![image](https://user-images.githubusercontent.com/4432491/78944774-0d4bab00-7a95-11ea-8007-8fe69e365220.png)

got it using the same colors as yours haha again thank you

**Comment by algenty** [comment]
I found it in draw.io. 
https://desk.draw.io/support/solutions/articles/16000079239-how-to-change-colors-in-svg-images-

**Comment by CrashLaker** [comment]
Hi @algenty. Thank you for your reply.

I've tried it already. By doing that I can change any SVG color inside Draw.io but I cannot in Flowcharting.

This is the RAW SVG before importing to Draw.io
```
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="409.10588508799844 398.880889114085 82.9067692610505 83.39213696581282" >
<style>
.st0 {fill: white;}
</style>
<path class="st0" d="M467.70933024090607,408.81278949816647L470.5084333831601,416.36251817300877L492.01265434904894,426.5196750762701L491.70164288879835,431.92388520192526L474.8181636180592,459.3270632791787L467.5760396150845,464.35104002222647L461.9778333305761,468.62115669571955L457.8458239301058,474.8299358634859L454.5135582845652,482.2730260798978L449.4929447119506,480.5783932587481L442.0286696659397,481.7886620469675L436.5193237986459,460.4741001047465L412.4825809421462,459.70932385674405L412.7935924023967,444.57834851378595L409.10588508799844,432.3474657191132L417.947496600833,407.97561722984017L426.7891081136672,400.91923971408755L435.053126914608,398.880889114085L444.7833425995866,404.6766577764405L456.1130457944247,404.39810599806185L460.867078115396,399.2050455719135L460.8226479067888,404.6302299682337L456.55734788049676,408.85930882487355Z"></path>
</svg>
```

this is how the shape is encoded after dragging it to Draw.io
```
shape=image;verticalLabelPosition=bottom;labelBackgroundColor=#ffffff;verticalAlign=top;aspect=fixed;imageAspect=0;image=data:image/svg+xml,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIHZpZXdCb3g9IjQwOS4xMDU4ODUwODc5OTg0NCAzOTguODgwODg5MTE0MDg1IDgyLjkwNjc2OTI2MTA1MDUgODMuMzkyMTM2OTY1ODEyODIiPiYjeGE7PHN0eWxlPi5zdDAgeyBmaWxsOiByZ2IoMTAyLCAyMDQsIDApOyB9IDwvc3R5bGU+JiN4YTs8cGF0aCBjbGFzcz0ic3QwIiBkPSJNNDY3LjcwOTMzMDI0MDkwNjA3LDQwOC44MTI3ODk0OTgxNjY0N0w0NzAuNTA4NDMzMzgzMTYwMSw0MTYuMzYyNTE4MTczMDA4NzdMNDkyLjAxMjY1NDM0OTA0ODk0LDQyNi41MTk2NzUwNzYyNzAxTDQ5MS43MDE2NDI4ODg3OTgzNSw0MzEuOTIzODg1MjAxOTI1MjZMNDc0LjgxODE2MzYxODA1OTIsNDU5LjMyNzA2MzI3OTE3ODdMNDY3LjU3NjAzOTYxNTA4NDUsNDY0LjM1MTA0MDAyMjIyNjQ3TDQ2MS45Nzc4MzMzMzA1NzYxLDQ2OC42MjExNTY2OTU3MTk1NUw0NTcuODQ1ODIzOTMwMTA1OCw0NzQuODI5OTM1ODYzNDg1OUw0NTQuNTEzNTU4Mjg0NTY1Miw0ODIuMjczMDI2MDc5ODk3OEw0NDkuNDkyOTQ0NzExOTUwNiw0ODAuNTc4MzkzMjU4NzQ4MUw0NDIuMDI4NjY5NjY1OTM5Nyw0ODEuNzg4NjYyMDQ2OTY3NUw0MzYuNTE5MzIzNzk4NjQ1OSw0NjAuNDc0MTAwMTA0NzQ2NUw0MTIuNDgyNTgwOTQyMTQ2Miw0NTkuNzA5MzIzODU2NzQ0MDVMNDEyLjc5MzU5MjQwMjM5NjcsNDQ0LjU3ODM0ODUxMzc4NTk1TDQwOS4xMDU4ODUwODc5OTg0NCw0MzIuMzQ3NDY1NzE5MTEzMkw0MTcuOTQ3NDk2NjAwODMzLDQwNy45NzU2MTcyMjk4NDAxN0w0MjYuNzg5MTA4MTEzNjY3Miw0MDAuOTE5MjM5NzE0MDg3NTVMNDM1LjA1MzEyNjkxNDYwOCwzOTguODgwODg5MTE0MDg1TDQ0NC43ODMzNDI1OTk1ODY2LDQwNC42NzY2NTc3NzY0NDA1TDQ1Ni4xMTMwNDU3OTQ0MjQ3LDQwNC4zOTgxMDU5OTgwNjE4NUw0NjAuODY3MDc4MTE1Mzk2LDM5OS4yMDUwNDU1NzE5MTM1TDQ2MC44MjI2NDc5MDY3ODg4LDQwNC42MzAyMjk5NjgyMzM3TDQ1Ni41NTczNDc4ODA0OTY3Niw0MDguODU5MzA4ODI0ODczNTVaIi8+JiN4YTs8L3N2Zz4=;editableCssRules=\.*;
```

Note I've added `editableCssRules=\.*;` at the end.

By doing that I can change the shape's color from Draw.io's interface.
![image](https://user-images.githubusercontent.com/4432491/79009634-530c8000-7b36-11ea-9539-ccc0c9d86f4c.png)

But exporting from Draw.io as XML the image is encoded as `data:image/svg+xml;base64...`

**Comment by algenty** [comment]
Maybe in a next release, i can add this function in flowcharting to color svg like it.
I added to roadmap

**Comment by CrashLaker** [comment]
Hi @algenty thanks for that.
meanwhile investigating it a bit further i bumped to this:
https://webapps.stackexchange.com/questions/48770/can-i-add-custom-shapes-to-draw-io

Where user `Amit Kumar Gupta` mentioned that Draw.io's default SVG format wasn't the one described in W3C SVG path [doc](https://www.w3.org/TR/SVG11/paths.html#PathData). `M`, `L`, `Z`.
but rather a XML one as shown below:
```
<shape aspect="variable" h="24" name="share2" strokewidth="inherit" w="24">
  <connections/>
  <foreground>
    <strokewidth width="0.5"/>
    <path>
      <move x="12" y="0"/>
      <line x="24" y="12"/>
      <line x="12" y="24"/>
      <line x="0" y="12"/>
      <close/>
      <close/>
      <move x="10" y="16"/>
      <line x="10" y="12"/>
      <line x="15" y="12"/>
      <line x="15" y="14"/>
      <line x="18" y="11"/>
      <line x="15" y="8"/>
      <line x="15" y="10"/>
      <line x="8" y="10"/>
      <line x="8" y="16"/>
      <close/>
    </path>
    <fillstroke/>
  </foreground>
</shape>
```
the XML above would render into this:
![image](https://user-images.githubusercontent.com/4432491/79054628-e9b36c80-7c1c-11ea-889f-8c7900fef0c7.png)

the procedure then is for the user to add it in `Arrange` -> `Insert` -> `Shape`

By doing that I could get them to work.

![image](https://user-images.githubusercontent.com/4432491/79054507-b3c1b880-7c1b-11ea-840e-dbaeacfd93dd.png)

But now I'm facing two main issues:
* As it's pretty easy to convert SVG path to Draw.io's XML format the process of loading it to Draw.io's is still too cumbersome as simply dragging the XML results in a broken shape (instead we should `Arrange` -> `Insert` -> `Shape`.
* After loading the shape it loses its scale becoming sometimes a lot bigger compared to the other shapes. Also the process of glueing all the pieces is just too much work. There has to be another solution.

additional refs:
https://desk.draw.io/support/solutions/articles/16000070744-how-to-create-custom-stencils-in-draw-io-using-the-text-editor-step-by-step-
https://desk.draw.io/support/solutions/articles/16000052874-how-to-create-and-edit-shapes-

**Comment by CrashLaker** [comment]
Doing it manually solved it.
![image](https://user-images.githubusercontent.com/4432491/79055295-52e9ae80-7c22-11ea-8c89-4f0d20f1cb5d.png)

Although IMHO the SVG panel approach is more feasible since by doing this I had to:
* Manually change the shape ID
* Manually insert metric ID Alias
* Manually assign metric ID -> shape ID
* ~~Would need to manually change color thresholds for all shapes~~ (didnt do this)

Not to tell that I had to manually position Draw.io's XML SVG by hand.

SVG panel gives you more control of all over the bullet points above simply because javascript. Also we'd use SVG path from W3C.

Not saying one is better than the other. Both are awesome. I just learned a bit more about Draw.io's shapes with this.

**Comment by algenty** [comment]
very nice

**Comment by algenty** [comment]
@CrashLaker, are you the author of this ? 
https://medium.com/@crashlaker/mapa-do-brasil-no-grafana-b5fcf36583cf
Very nice

**Comment by CrashLaker** [comment]
Hi @algenty 
Yeah I wrote that to help our brazillian fellows on how to build maps in grafana.
sorry i didn't say anything
Although it's in portuguese I mentioned that (correct me if i'm wrong) flowcharting is a tool that allows one to build/display maps on but its main value comes from allowing the user to operate on custom made diagrams like network/cloud architectures, floor plans, etc. And using it to arrange pixel level precision "drawing" would require another helper tool.
In short this is a really interesting project that needs its own article.
later on i'm keen on trying out some ideas related to "expand & collapse" and "rack diagram" from the [playground](https://play.grafana.org/d/JG78lp0Zk/) and also the new features from 0.8.0 version.
thank you for the project :)

**Comment by algenty** [comment]
You're welcome, 
you can found other examples at
https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1
Can i add your dashboard?

BR
Arnaud

**Comment by CrashLaker** [comment]
Sure. U could use this here: https://grafana.com/grafana/dashboards/12092

as i've corrected the scales

**Comment by image72** [comment]
> Hi @algenty thanks for that. meanwhile investigating it a bit further i bumped to this: https://webapps.stackexchange.com/questions/48770/can-i-add-custom-shapes-to-draw-io
> 
> Where user `Amit Kumar Gupta` mentioned that Draw.io's default SVG format wasn't the one described in W3C SVG path [doc](https://www.w3.org/TR/SVG11/paths.html#PathData). `M`, `L`, `Z`. but rather as an XML one as shown below:
> 
> ```
> <shape aspect="variable" h="24" name="share2" strokewidth="inherit" w="24">
>   <connections/>
>   <foreground>
>     <strokewidth width="0.5"/>
>     <path>
>       <move x="12" y="0"/>
>       <line x="24" y="12"/>
>       <line x="12" y="24"/>
>       <line x="0" y="12"/>
>       <close/>
>       <close/>
>       <move x="10" y="16"/>
>       <line x="10" y="12"/>
>       <line x="15" y="12"/>
>       <line x="15" y="14"/>
>       <line x="18" y="11"/>
>       <line x="15" y="8"/>
>       <line x="15" y="10"/>
>       <line x="8" y="10"/>
>       <line x="8" y="16"/>
>       <close/>
>     </path>
>     <fillstroke/>
>   </foreground>
> </shape>
> ```
> 
> the XML above would render into this: ![image](https://user-images.githubusercontent.com/4432491/79054628-e9b36c80-7c1c-11ea-889f-8c7900fef0c7.png)
> 
> the procedure then is for the user to add it in `Arrange` -> `Insert` -> `Shape`
> 
> By doing that I could get them to work.
> 
> ![image](https://user-images.githubusercontent.com/4432491/79054507-b3c1b880-7c1b-11ea-840e-dbaeacfd93dd.png)
> 
> But now I'm facing two main issues:
> 
> * As it's pretty easy to convert SVG path to Draw.io's XML format the process of loading it to Draw.io's is still too cumbersome as simply dragging the XML results in a broken shape (instead we should `Arrange` -> `Insert` -> `Shape`.
> * After loading the shape it loses its scale becoming sometimes a lot bigger compared to the other shapes. Also the process of glueing all the pieces is just too much work. There has to be another solution.
> 
> If I try to add all the shapes in a single XML code it indeed recognizes them as an unique plot. ![image](https://user-images.githubusercontent.com/4432491/79054811-73176e80-7c1e-11ea-8d32-d1ab8715df9f.png)
> 
> additional refs: https://desk.draw.io/support/solutions/articles/16000070744-how-to-create-custom-stencils-in-draw-io-using-the-text-editor-step-by-step- https://desk.draw.io/support/solutions/articles/16000052874-how-to-create-and-edit-shapes-

has any tools convert svg to shapes xml?
