### ISSUE TITLE
Problem when editing a second diagram

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#146]
Reproducing:
Open a dashboard, edit a draw.io diaram, save it.
Open another dashboard, edit a draw.io diagram.
Comme back to the original and edit again. The draw.io will contain the xml of both drawings! Zoom out and it is apparent that both drawings are there. Very strange.
(I reproduced it twice, not sure it was the exact same steps, but similar)
This is with 0.7.

**Comment by algenty** [comment]
ok,i'll try to reproduce it.

**Comment by xkilian** [comment]
Not had the issue with 0.8, closing,
