### ISSUE TITLE
Change Draw.io arrow color

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#148]
Can I change arrow colors?

![image](https://user-images.githubusercontent.com/4432491/79642097-f3375a00-8171-11ea-82d3-7f8981b1d350.png)

![image](https://user-images.githubusercontent.com/4432491/79642320-33e3a300-8173-11ea-8c9c-72aa049fbe03.png)

**Comment by algenty** [comment]
Yes, choose stroke in color method

**Comment by CrashLaker** [comment]
Thank you. It worked.

![app-flow-gif](https://user-images.githubusercontent.com/4432491/79644683-e0785180-8180-11ea-9a46-5dccedffa33a.gif)

btw as a workaround we could loop refresh by running
`setInterval(() => $('.fa-refresh').click(), 1000)` in the console
