### ISSUE TITLE
Value Mappings are not working properly with v0.71

### ISSUE THREAD

**Issue by epcos71** [algenty/grafana-flowcharting#150]
Hi,

I just updated the panel from version 0.7 to 0.71. In version 0.7 I am using the panel for showing the status of my house windows. Therefore I needed the type String and  a value mapping from true -> open and false -> closed. These values (closed, open)  I used for the thresholds. After the update the panel does not accept the mapped values, it only works when I am using the  origin values (true, false) from the database. So I think the value mapping does not work properly.

Thanks & regards,
Michael

**Comment by algenty** [comment]
Fixed in 0.8.0

**Comment by algenty** [comment]
0.8.0 published
