### ISSUE TITLE
"Undefined" metric cant be saved due to inability to alias in Clickhouse plugin

### ISSUE THREAD

**Issue by dannyman00123** [algenty/grafana-flowcharting#152]
I am using Clickhouse plugin 1.9.5 (latest). In the getting started guide, queries are able to be aliased but this doesnt work with Clickhouse. 
I have to use one query to return multiple metrics (which is fine).

In this example below, my "metric" is undefined but I can access my two columns (c1 and c2).

![image](https://user-images.githubusercontent.com/50487205/80365498-99284a00-887f-11ea-93b5-664096721f7e.png)

![undefined](https://user-images.githubusercontent.com/50487205/80365163-0e474f80-887f-11ea-9368-512a60211c97.PNG)

However, whenever I save and reload. they default back to blank

![image](https://user-images.githubusercontent.com/50487205/80365532-ab09ed00-887f-11ea-9d01-fc2428feb0df.png).

I was wondering if there was a quick fix or trick to this? I'd love to be able to use this plugin but I am bound to using Clickhouse.

**Comment by algenty** [comment]
Hi @dannyman00123 
Thx for your feedback
actualy, i can't try all datasource.
Clickhouse is not supported

**Comment by algenty** [comment]
You can try https://github.com/GoshPosh/grafana-meta-queries/issues to convert clickhouse to compatible datasource
