### ISSUE TITLE
When an object is rotated, events get broken for width and height

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#154]
From your example: 
> 
>     You need a percent for you query.
>     For my test, i use Grafana DB with Min : 0 max : 100
> 
> For the first, 2 rectangles, one solide in back, the width never changes (note the size, here 120px)
> The second on front , with event width, field When : All, field value : ${_value} * 1.2
> why 1.2? because, size must be 120px (100*1,2) when value is 100%

Ok, if I take the same example you prepared with the horizontal status bar. Rotate the shape 90 degrees (to vertical). Try to modify the width, it causes an X axis offset in addition to growing the shape in an unexpected way.
Rotating shapes seems to break the height/width changing logic. Should this be a supported use case, or should the documentation reflect that rotating shapes is a no no.

**Comment by algenty** [comment]
fixed in 0.9.0

**Comment by xkilian** [comment]
Thanks, that kind of went under the radar!
