### ISSUE TITLE
World map background in flowcharting/draw.io?

### ISSUE THREAD

**Issue by paregupt** [algenty/grafana-flowcharting#155]
Looking for world map as a background and then draw the usual draw.io shaped on top of it. Any suggestion, please?
Example:
![image](https://user-images.githubusercontent.com/8773072/81139495-d09b9400-8f1a-11ea-837b-e955f6299e71.png)

**Comment by algenty** [comment]
You can add an svg or png in your draw.io

**Comment by CrashLaker** [comment]
@paregupt 
more about the discussion [here](https://github.com/algenty/grafana-flowcharting/issues/144)
and [here](https://github.com/algenty/grafana-flowcharting/issues/90)

You only want a map "background" meaning you don't want to color (apply any effects) to each country and place boards on top of it?

**Comment by paregupt** [comment]
Initially, I was only looking for a map background and use usual shapes for other purpose, like metric display, color change, etc. But looks like more may be possible. Thank you @algenty and @CrashLaker. Looks promising. Let me try and share with you.
