### ISSUE TITLE
support of font types

### ISSUE THREAD

**Issue by x70b1** [algenty/grafana-flowcharting#156]
Thank you for this great work here!

`draw.io` supports different ways to define fonts: 

- System
- Google Fonts
- Web Fonts

After an import there is only the default font. 
I suppose the function is not yet implemented? But I also don't know if that is even possible.

**Comment by algenty** [comment]
Hi, not tested, i'll try it

**Comment by x70b1** [comment]
In this [image](https://raw.githubusercontent.com/algenty/flowcharting-repository/master/images/banner_large.png) it looks like the `Flowcharting` text use a custom font.
So maybe the fault is on my side.

**Comment by algenty** [comment]
@x70b1 Can you try the snapshot version in
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by x70b1** [comment]
Yep, I will try it.

**Comment by x70b1** [comment]
Works in your latest snapshot.
Thx! :sunglasses:

**Comment by hellt** [comment]
@algenty 
so if I want to have the Google Fonts that I use in my drawing to render in flowchart panel, I need to fetch the latest snapshot?
