### ISSUE TITLE
Shape as AWS of GCP are not displayed correctly

### ISSUE THREAD

**Issue by feraudet** [algenty/grafana-flowcharting#16]
Hello,

Shape as AWS of GCP are displayed without content.

In console log I can see 2 xml file with 404 error : 
* http://localhost/public/plugins/agenty-flowcharting-panel/libs/mxgraph/javascript/dist/stencils/aws4.xml
* http://localhost/public/plugins/agenty-flowcharting-panel/libs/mxgraph/javascript/dist/stencils/gcp2.xml

Any idea ?

Thanks in advance

**Comment by algenty** [comment]
Hi Cyril,
All shapes are included in version 0.4.0 SNAPSHOT (not released), what is your version ?
https://algenty.github.io/flowcharting-repository/ARCHIVES.html
Cordialement,

**Comment by feraudet** [comment]
Hi Arnaud,
I use 0.3.0, I will try this one

**Comment by feraudet** [comment]
It's strange, plugin is not present in the plugin list but I've this output in logs : 
`installing agenty-flowcharting-panel @
from url: https://algenty.github.io/flowcharting-repository/archives/agenty-flowcharting-panel-0.4.0-SNAPSHOT.zip
into: /var/lib/grafana/plugins
✔ Installed agenty-flowcharting-panel successfully
Restart grafana after installing plugins . <service grafana-server restart>
`
I use **grafana/grafana** docker image with this env var : `GF_INSTALL_PLUGINS=https://algenty.github.io/flowcharting-repository/archives/agenty-flowcharting-panel-0.4.0-SNAPSHOT.zip;agenty-flowcharting-panel`

An idea ?

**Comment by algenty** [comment]
have you remove old version ?
delete session directory in data too

**Comment by algenty** [comment]
PI 0.3.0 is published on grafana

**Comment by feraudet** [comment]
I don't undertand why grafana-cli work with 0.3 but not with 0.4. An idea ?
Thanks in advance
```
root@430c9f42e7f1:/usr/share/grafana# grafana-cli --pluginUrl "https://algenty.github.io/flowcharting-repository/archives/agenty-flowcharting-panel-0.4.0-SNAPSHOT.zip" --pluginsDir "${GF_PATHS_PLUGINS}" plugins install agenty-flowcharting-panel
installing agenty-flowcharting-panel @
from url: https://algenty.github.io/flowcharting-repository/archives/agenty-flowcharting-panel-0.4.0-SNAPSHOT.zip
into: /var/lib/grafana/plugins

✔ Installed agenty-flowcharting-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>

root@430c9f42e7f1:/usr/share/grafana# ls -l /var/lib/grafana/plugins
total 0
root@430c9f42e7f1:/usr/share/grafana# grafana-cli --pluginUrl "https://github.com/algenty/grafana-flowcharting/archive/master.zip" --pluginsDir "${GF_PATHS_PLUGINS}" plugins install agenty-flowcharting-panel
installing agenty-flowcharting-panel @
from url: https://github.com/algenty/grafana-flowcharting/archive/master.zip
into: /var/lib/grafana/plugins

✔ Installed agenty-flowcharting-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>

root@430c9f42e7f1:/usr/share/grafana# ls -l /var/lib/grafana/plugins
total 4
drwxr-xr-x 5 root root 4096 Jun 17 14:46 agenty-flowcharting-panel
root@430c9f42e7f1:/usr/share/grafana#
```

**Comment by algenty** [comment]
With grafana-cli, you cant install non published version.
You must download zip from https://algenty.github.io/flowcharting-repository/ARCHIVES.html and unzip it in plugin directory
