### ISSUE TITLE
Used Drawio in Vscode

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#160]
This might be interesting:
https://github.com/hediet/vscode-drawio

![demo](https://user-images.githubusercontent.com/4432491/81566131-d35e1500-9370-11ea-8334-8acf54f8e611.gif)

**Comment by algenty** [comment]
I saw that, i've already tweeted it

**Comment by CrashLaker** [comment]
Sorry. I was only to have it recorded here.
> I don't think I made a mistake when I chose draw.io for the plugin.

Why? i'm not saying u've made a mistake.
Just posting an useful resource for those who develop in vscode.
