### ISSUE TITLE
Using custom images based on condition

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#162]
Hi all,

I know we can change the shape based on condition
as described [here](https://github.com/algenty/grafana-flowcharting/issues/145#issuecomment-615437953)
but the shape is from drawio's gallery

Is it possible to link to a dynamic image. Something like this?
![image](https://user-images.githubusercontent.com/4432491/81620468-52c80480-93c2-11ea-8f60-94adb14a5dab.png)

or this?
![image](https://user-images.githubusercontent.com/4432491/81620556-90c52880-93c2-11ea-8a94-c2bd112648e3.png)

**Comment by algenty** [comment]
you can use event image : change url

**Comment by CrashLaker** [comment]
I'm sorry is it in the `Event/Animation Mappings`?
![image](https://user-images.githubusercontent.com/4432491/81700738-75e4c980-943f-11ea-9506-cd037f38c7c0.png)

I'm afraid I'm using an older version. Idk which version I'm using. How could I check?
Anyways Imma download the newest release.

**Comment by CrashLaker** [comment]
Found it thank you.

![image](https://user-images.githubusercontent.com/4432491/81702777-19cf7480-9442-11ea-8211-1ad00b1a5407.png)

I think I was using a SNAPSHOT version you've released prior to 0.8.0.
All fine now.

**Comment by CrashLaker** [comment]
The images don't seem to be resizeable.

Can I customize its size?
![image](https://user-images.githubusercontent.com/4432491/81725379-206ae580-945c-11ea-9094-9a89d17e4da6.png)

**Comment by algenty** [comment]
don't know ?try width and height

**Comment by CrashLaker** [comment]
I see.

You can only change if the object is already an image not a shape.

It worked after setting width and height
thank you.
![image](https://user-images.githubusercontent.com/4432491/81738986-fb34a200-9470-11ea-8f86-0ed2a350e385.png)

**Comment by algenty** [comment]
You write a new medium blog ?

**Comment by CrashLaker** [comment]
> You write a new medium blog?

not yet though i'm planning to.
is it possible to have a slight fade transition when updating the image?
all this blinking makes it a bit weird.
![change-fruit](https://user-images.githubusercontent.com/4432491/81763605-02c26e00-94a6-11ea-9fe4-7b3fba7c20da.gif)

**Comment by algenty** [comment]
i can't, it's a draw.io methods

**Comment by CrashLaker** [comment]
Hm ok.

changing the whole xml makes it refresh faster though
gotta explore this
![change-fruit2](https://user-images.githubusercontent.com/4432491/81826795-844de680-950e-11ea-9133-b5108c74aab3.gif)
