### ISSUE TITLE
Is there a limit of 6 metrics?

### ISSUE THREAD

**Issue by keifnz** [algenty/grafana-flowcharting#163]
Hi,

Firstly can I say this Grafana Plugin is very impressive. I've just started playing around with it against one of my personal IoT projects running at home.

I've hit upon a weird issue which I'm convinced is user error, but I can't seem to figure out where I'm going wrong.

I've tried creating a number of different diagrams, some using the "Edit Draw" button from a clean "FlowCharting" visualisation. Others by creating a simple image in Draw.Io and then pasting the XML.

However in all my scenarios, no matter what queries I write against InfluxDb - I seem to only be able to access the first 6 metrics.

Here is an example of of the metric list having just clicked in

![image](https://user-images.githubusercontent.com/10351093/82079571-f7a45380-96da-11ea-9ff4-5791bb553f3c.png)

Based on my 2 queries in the bottom diagram, I should have 4 metrics with a "-TempC" suffix, which I can see. I should also have 4 metrics with a "-Humidity" suffix, but only 2 show up. You can see when I start to search of "Office-Humidity" which is definitely there as I have graphs running identical queries, nothing shows up as a match.

![image](https://user-images.githubusercontent.com/10351093/82079618-0ab72380-96db-11ea-90cb-420423034184.png)

As further debugging, if I use one of the metrics that shows in the dropdown, you can see the rule summary has a correct Raw Value and suitable Formatted Value

![image](https://user-images.githubusercontent.com/10351093/82080452-7a79de00-96dc-11ea-8fd0-05a79076396c.png)

If I then type in "Office-Humidity" in this case, you see the Raw Value is null

![image](https://user-images.githubusercontent.com/10351093/82080499-93828f00-96dc-11ea-907b-e39e63f2df4e.png)

If I then delete my first temperature based query, removing all the data with the "-TempC" suffix, and leaving the single humidity based query with should produce 4 results with a "-Humidity" suffix the rule starts showing the Raw Value and Formatted Value

![image](https://user-images.githubusercontent.com/10351093/82080856-3b985800-96dd-11ea-9503-864a6372c87c.png)

Just to help provide context, here are the two influx queries.

![image](https://user-images.githubusercontent.com/10351093/82079690-29b5b580-96db-11ea-9895-c4f9e71a9700.png)

I'm sure this is something I'm doing wrong, but I can't for the life of me figure out where I'm going wrong :)

Many thanks in advance, Keith

P.S. Grafana version is 6.7.3 and FlowChartting plugin version 0.8.1

**Comment by algenty** [comment]
Use the query inspector to verify the number of query in result
![image](https://user-images.githubusercontent.com/47012725/82118030-b8c2dc00-9774-11ea-81e0-f6cc96cd8e51.png)

**Comment by keifnz** [comment]
Hi Arnaud,

Thanks for your super fast reply.

Looks like InfuxDb doesn't use the data element in the object model:

![image](https://user-images.githubusercontent.com/10351093/82122629-ac4a7d80-978c-11ea-86d0-8aa79768f152.png)

But I have made a bit of a discovery which has unblocked me.

If I have this query:
![image](https://user-images.githubusercontent.com/10351093/82122647-c3896b00-978c-11ea-8be1-e1a77443bef6.png)

Then I get a full list of metrics:
![image](https://user-images.githubusercontent.com/10351093/82122652-d13ef080-978c-11ea-903b-36bf0d3302b8.png)

However if I am getting the data from the same source but using two more discrete queries:

![image](https://user-images.githubusercontent.com/10351093/82122699-051a1600-978d-11ea-878a-f6bf34719b9b.png)

Then I get the issue where I can't refer to all the metrics that result from these two queries (there should be 8 items in the list):
![image](https://user-images.githubusercontent.com/10351093/82122725-27ac2f00-978d-11ea-82e8-60c0fc24264b.png)

I've started to detect that there may be a pattern which seems to depend on the source of the first query. This is based on some things I spotted using multiple data sources. Though it's only a hunch at the moment and I can't quite think how to articulate it.

I've found a way forward now thanks :) If I think I can shed more light on this I'll update the issue.

Many thanks, Keith
