### ISSUE TITLE
Uploading the initial image - how?

### ISSUE THREAD

**Issue by minfrin** [algenty/grafana-flowcharting#168]
The process used to upload the initial image needs to be overhauled for people who aren't yet familiar with the drawio tools.

The principle of least surprise tells me I am looking for an upload button where I can upload a file. This would be a file that was edited by a tool, backed up, and checked into source control on my side.

What I see instead is a dropdown called "Source Type" that can only be set to XML, and then a textarea called "Source Content", that contains some opaque base64 that isn't XML.

There is no obvious way to generate that base64, which makes this difficult for someone else who needs to manage this in 6 months time. There is no clue as to what the original source file was, or where it might come from.

**Comment by minfrin** [comment]
What eventually worked was to load the drawio file into TextEdit, cut and paste the XML into the window where the base64 was, and from then on I had an image to work with.

To fix this, add a normal file upload option that populates the textarea with the contents of a file.

**Comment by algenty** [comment]
You don't have to download a file.
I suggest you look at the doc.
When adding the panel, you have to click on edit.
The base64 is not required, it is only used to reduce the size of the schema in the grafana database.

**Comment by minfrin** [comment]
Getting my head around this made my head hurt. I sort of understand that grafana is pretending to be a desktop application in a web browser, but it doesn't come close.

In theory, all of the options below can be simplified down to one button - "edit drawing". None of the other options make any sense to me as an end user, this should just happen in the background.

<img width="459" alt="grafana-simplify" src="https://user-images.githubusercontent.com/1331788/82498122-b99a9b80-9aef-11ea-8e67-44cf82bfcbc1.png">

Relying on draw.io for a key part of the plugin is a problem - like all online services, they are at risk of disappearing without notice. If that happens, the whole plugin breaks, and leaves us DoSed.

The ability to load and save an SVG version of the file future-proofs the plugin.

**Comment by algenty** [comment]
I'am not agree with you, these buttons are usefull for modify xml with variables and/or compress text after. If you open a drawio, you can see a base64 not an xml.
Second point, you can install your own draw.io server (it's easy) and change the draw.io url.

**Comment by minfrin** [comment]
I'm reporting this as the experience of a new user. The very first step was to upload the image I already had, and the software was fighting me at every turn.

**Comment by algenty** [comment]
I understand, Flowcharting is always in beta, it can make many things then it's a little complex.
If you want more simplicity, i suggest to use imageIt
