### ISSUE TITLE
Feature request: specify remote location for XML

### ISSUE THREAD

**Issue by teunvink** [algenty/grafana-flowcharting#17]
Thanks for the great plugin! I have a feature request: instead of creating/editing the Draw.io XML I would like to use diagram we already have made and which are hosted on a server. This way we would not have to copy XMLs from our documentation archive to Grafana, and we would not risk that the documentation an dashboard run out of sync.

**Comment by algenty** [comment]
Hi teunvink

This feature is in roadmap (tab flowchart, source : url) but not implemented at this time, maybe in 0.4.0 if i have more times

br,
Arnaud

**Comment by algenty** [comment]
Hi teunvink,
Last version 0.4.0 support url, it's the version candidate for release this week
See changelog at https://algenty.github.io/flowcharting-repository/CHANGELOG.html

BR
Arnaud

**Comment by Seana36** [comment]
Thank you so much for the update! This was exactly what I was looking for. When I am trying out the 0.4.0 version with the support url, I am getting an error, see picture. I am using HTTPS link, GET, and it is returning xml/plain type. Is there anything I am missing?
![GrafanaError](https://user-images.githubusercontent.com/11064014/65179080-178a5700-da28-11e9-884f-60f22b46ecae.jpg)

**Comment by algenty** [comment]
Hi, 
can you give me stack error in console chrome ?
ctrl + shift + i

BR
Arnaud

**Comment by algenty** [comment]
Try too : 
Draw.io format (compressed)
https://raw.githubusercontent.com/algenty/flowcharting-repository/master/graphs/Flowcharting_carto.drawio
And xml (not compressed)
https://raw.githubusercontent.com/algenty/flowcharting-repository/master/graphs/critrix.xml

**Comment by Seana36** [comment]
Looks like it was CORS error when working inside grafana. Once I iframed the graphic into my parent application it started working fine. Thanks for all the help!!

**Comment by algenty** [comment]
Can you give me trace of the first error to fix CORS

**Comment by Seana36** [comment]
![GrafanaError2](https://user-images.githubusercontent.com/11064014/65277923-f8a7c580-daf8-11e9-9d3c-1db79179d12a.jpg)
Sorry had to block out a bunch of the URLs for privacy.

**Comment by algenty** [comment]
thx
