### ISSUE TITLE
Theme passed to draw.io ignored by plugin - black text on a black background

### ISSUE THREAD

**Issue by minfrin** [algenty/grafana-flowcharting#170]
After successfully importing a diagram into draw.io, and using the dark theme, draw.io renders the image as follows - white text on a black background:

<img width="306" alt="draw io-white-text" src="https://user-images.githubusercontent.com/1331788/82500066-0cc21d80-9af3-11ea-9438-640656eb6e2c.png">

After clicking "save" and returning to the plugin in grafana, the resulting image is rendered as follows, using black text on a black background:

<img width="229" alt="plugin-black-text-black-background" src="https://user-images.githubusercontent.com/1331788/82500334-79d5b300-9af3-11ea-9805-11e25048f4e2.png">

It looks like the plugin doesn't seem to apply the same theme that was passed to draw.io (that's a guess).

**Comment by minfrin** [comment]
Clearer example:

<img width="206" alt="plugin-black-text-attempt-two" src="https://user-images.githubusercontent.com/1331788/82500853-873f6d00-9af4-11ea-8109-8484c147830a.png">

**Comment by algenty** [comment]
Yes, it's a bug from draw.io, the color of label is not in xml, try Light theme instead to resolve it

**Comment by minfrin** [comment]
All themes have the same effect, they seem to work fine in draw.io, but the plugin renders all themes on the same black background. I have not yet been able to get any text to be visible from any of the drawings.

**Comment by algenty** [comment]
Try to force text to white
