### ISSUE TITLE
Multimple metric values in  single rule 

### ISSUE THREAD

**Issue by rsa2k8** [algenty/grafana-flowcharting#171]
Hello. Is it possible to use many values of query tsdb( for example ) in the mapping of text?
How it to do?
In other words, how in the single rule to separate items of the metric list(array)?
Thanks

**Comment by algenty** [comment]
You can use a regex in field "Apply to metry" to select multiple metrics

**Comment by rsa2k8** [comment]
Good day!
Yes, I can
Next step is to mapping the data by ids
Example:
I have six queries
![image](https://user-images.githubusercontent.com/5236961/82810386-089d5380-9e97-11ea-9b98-132ca3a6e301.png)

Aliases are A-F

I applied regex
![image](https://user-images.githubusercontent.com/5236961/82810488-53b76680-9e97-11ea-82e2-d0b0deeabca7.png)

How to mapping values by id item?
![image](https://user-images.githubusercontent.com/5236961/82810625-9416e480-9e97-11ea-9b1e-bffdf38b300b.png)

![image](https://user-images.githubusercontent.com/5236961/82810694-ca546400-9e97-11ea-888e-5e6835149552.png)

Now, last item of array is selected  and  inserted at all ids
![image](https://user-images.githubusercontent.com/5236961/82810889-3c2cad80-9e98-11ea-8926-3887cba6c88d.png)

**Comment by algenty** [comment]
In Label, don't use SubString, but "alltext" instead in your case
See options demo at 
https://play.grafana.org/d/VbE3_jqZz/flowcharting-options-demo?orgId=1
Line 2
