### ISSUE TITLE
Flowchart Image (draw.io) scatter around when zoomed in

### ISSUE THREAD

**Issue by msinphilpk** [algenty/grafana-flowcharting#172]
Hi,

I am using Flowcharting panel to show a sample SLD diagram in my grafana dashboard. The plugin is very good and very useful, thanks. But, if the flowchart / image is zoomed, the remaining part of the image is blown out of the panel boundary. Please fix this issue as soon as possible.

Thank you.

![before_zoom](https://user-images.githubusercontent.com/22269123/82863926-fd9efd80-9f40-11ea-98f6-b989aecae7e5.png)
![after_zoom](https://user-images.githubusercontent.com/22269123/82863931-01328480-9f41-11ea-9002-b26e9b1bad5e.png)

**Comment by algenty** [comment]
Fixed on v0.9.0

**Comment by algenty** [comment]
You can download it at
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by msinphilpk** [comment]
Thank you very much for fixing the issue.
