### ISSUE TITLE
Force bring elements to front in CSV

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#174]
I think the order of the elements is what determines whether  it comes on top or not.

Is it possible to force that when using CSV?

For instance in this image I want to get the icons on top of the edges.
![image](https://user-images.githubusercontent.com/4432491/83220114-820f9d00-a148-11ea-989f-f1f4b440091c.png)

thank you

**Comment by algenty** [comment]
If you have the same result in draw.io
I suggest to open a ticket at draw.io
https://groups.google.com/forum/#!forum/drawio

**Comment by CrashLaker** [comment]
Actually this works like SVG so order matters.
So one'd have to bring all the arrows before the icons.
This isn't as simple when you're dealing with complex diagram but it's a start.
