### ISSUE TITLE
Even when condition is false , Blinking event is triggered in animation 

### ISSUE THREAD

**Issue by amitmalhotra-cell** [algenty/grafana-flowcharting#177]
I used below setting to blink if value = 1
![image](https://user-images.githubusercontent.com/63041681/83652760-9cc69380-a5d8-11ea-9c15-d20777629a0f.png)

But even when Last value is 0 , it is blinking. Please check at your end if this is existing bug

**Comment by algenty** [comment]
Already fixed in 0.9.0, publication in progress
