### ISSUE TITLE
FlowChart doesn't show some specific metrics

### ISSUE THREAD

**Issue by tdungsi1** [algenty/grafana-flowcharting#178]
Hello,
I was trying to apply this metric on my map but this metric doesn't show. I have verified everything from the query function.
![Query](https://user-images.githubusercontent.com/26120816/84225120-8d7ba480-ab08-11ea-999a-fd4869029f85.PNG)
This is the metric
![Metrics](https://user-images.githubusercontent.com/26120816/84225140-9a989380-ab08-11ea-8ea6-946129450c5d.PNG)
It worked and queried fine when i created a new dashboard, still used FlowCharting, same step, same configuration but the new one worked. I don't know why. Can you explain to me or give me a solution for this?
![StillFlowChart](https://user-images.githubusercontent.com/26120816/84225201-b9972580-ab08-11ea-9134-5f6e851579e1.PNG)

Thank you

**Comment by tdungsi1** [comment]
The first dashboard which didn't work, i have 2 more rules, just a fact you may need.

**Comment by jorlandobr** [comment]
On your query A, intead of an item you put a regex /.*/ (everything).

From my experience, it's the oposite. You put the regex /.*/ for the hostames, on Item your specific metric (Bandwith Usage Percent, accordingly your picture). On the mapping you specify the host(s) that you want to use this metric.

**Comment by tdungsi1** [comment]
This problem is solved actually.
I added a function where "SetAlias" to something else.
