### ISSUE TITLE
More than 26 Queries

### ISSUE THREAD

**Issue by techcubs** [algenty/grafana-flowcharting#179]
Hi All,

When I have more than 26 queries, I hit the Grafana limit ([issue 4978](https://github.com/grafana/grafana/issues/4978)) I manually update the JSON and add RefID's like AA AB etc. these then show up fine in the Query section.

When I try to use these queries in the rules, I only see the A-Z Queries under "Apply to Metrics".

Can someone help me on this? has anybody created a flowchart with more than 26 queries? I am struggling to complete a network diagram as it has quite a lot of devices and each device needs multiple queries.

Regards,
Raj

**Comment by xkilian** [comment]
This is a known issue. I have made my case on the issue. It is an arbitrary limit. Setting up dynamic dashboards can also generate way more than 26 queries. So meh. Pipe in on the Grafana issue with intelligent feedback that some plugins require more queries, like flowcharting or imageit.
Try to do less queries with larger data scopes to get what you need and then use the flowcharting metric selection regex to get the ones you want. Not much the maintainer of flowcharting can do about it. It is a Grafana issue.

**Comment by CrashLaker** [comment]
Instead you can use any other datasource whose query results in unlimited (way more than 27 but constrained by the browser's capacity) targets which you can then pipe to flowcharting.
