### ISSUE TITLE
Rules not handling decimal value correctly

### ISSUE THREAD

**Issue by Theoooooo** [algenty/grafana-flowcharting#18]
After importing an XML form draw.io, i wanted to setup uptime display with decimals to have the hours, minutes and seconds.
But when i setup the decimal to "2", the value display doesn't have any decimal :
![image](https://user-images.githubusercontent.com/33425208/59424843-043a7080-8dd5-11e9-910d-226f549ea1ab.png)

![image](https://user-images.githubusercontent.com/33425208/59424876-10bec900-8dd5-11e9-8ac4-4cad06d03736.png)

If i setup a similar request in a another panel (SingleStat in this case) i got the correct value out of it with the decimals :

![image](https://user-images.githubusercontent.com/33425208/59430551-d78d5580-8de2-11e9-977a-692eb0746a1f.png)

![image](https://user-images.githubusercontent.com/33425208/59430542-d0664780-8de2-11e9-8a6b-c1a2ad10dc3a.png)

**Comment by algenty** [comment]
Hi Theo,
Thanks for your feedback
What is your version of flowcharting ?
Can you try last stable version 0.3.0 ?
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BG,
Arnaud

**Comment by Theoooooo** [comment]
I'm using the 0.2.5 version available on Grafana.
I'm testing the 0.3.0 right now i will edit this post with an update soon

**Comment by algenty** [comment]
Your welcome,
don't forget to stargazer project if you like it :)

BG
