### ISSUE TITLE
Rotate item by a condition

### ISSUE THREAD

**Issue by Arthur380** [algenty/grafana-flowcharting#181]
Hello,

I'm new to FlowCharting and I would like to use this plugin to display a switch based on the last influxdb data (0 or 1).
You can see on the next screen my example.

![measurement_capture](https://user-images.githubusercontent.com/45686298/84395006-f4c75080-abfd-11ea-8923-b992db2e25ed.png)

How can I set a rule to close the interrupt if the last value is 0?

Next you can see what I'm trying to do.

![measurement_capture2](https://user-images.githubusercontent.com/45686298/84395654-63a4a980-abfe-11ea-8a03-28ee613d1d4c.png)
![measurement_capture3](https://user-images.githubusercontent.com/45686298/84395690-669f9a00-abfe-11ea-98de-636decbaf76c.png)

The metric "last-value" correspond to the alias set on InfluxDB.

Can you help me please? I really don't know how to add a condition on this rule.

Arthur

**Comment by algenty** [comment]
Yes, offcourse, put 2 shape on the place,
choose hide event instead, hide one when level is 0 for example and hide the other when level is 1

BR
Arnaud

**Comment by Arthur380** [comment]
Thank you Arnaud, it works well !

Regards,

Arthur
