### ISSUE TITLE
Display Label Value instead of metric Value

### ISSUE THREAD

**Issue by techcubs** [algenty/grafana-flowcharting#183]
Hi, Is there a way of displaying the label value instead of metric value

Metric:
**fgSysVersion{fgSysVersion="v6.0.9,build0335,200121(GA)",instance="x.x.x.x",job="snmp"}**
Result is **1**

I want to show just the version in the tooltip.

If I leave the Tooltips "Label" empty, i get this displayed as the tooltip:
_fgSysVersion{fgSysVersion="v6.0.9,build0335,200121(GA)",instance="x.x.x.x",job="snmp"}:1_

If I change Tooltips Label to Vesion, I get this displayed as the tooltip: 
_Version: 1_

Is there a way I can manipulate the metric name to only show  "v6.0.9,build0335,200121(GA)" in the tooltip.

maybe a regex to only show certain parts of the label?

**Comment by algenty** [comment]
Maybe with text replace in event, you can use a javascript expresssion like
${_value}.split('"')[2]

**Comment by techcubs** [comment]
The Rule is set as follows:

Prometheus metric result:
fgSysVersion{fgSysVersion="v6.0.9,build0335,200121(GA)",instance="x.x.x.x",job="snmp"}
Result is 1

Rule Name: VersionDetails
Apply To Metrics: fgSysV.*instance="x.x.x.x".*}

Type: String

Display Metrics: Yes
Label: Auto

This shows:
![image](https://user-images.githubusercontent.com/59602334/84604114-ac24c700-ae8b-11ea-9ff1-abbd78287a67.png)

I would like to have this show as:
Version: v6.0.9,build0335,200121(GA)
Av:16.00560(2012-10-19 08:31)
and so on....

Thanks @algenty, do you mean that i should put this in the Value mapping field:
Value = 1
Text = ${_value}.split('"')[1]

![image](https://user-images.githubusercontent.com/59602334/84604169-045bc900-ae8c-11ea-90cf-a1acb5667592.png)

I tried this above but it doesn't show the desired result. 
![image](https://user-images.githubusercontent.com/59602334/84604061-40425e80-ae8b-11ea-9779-421b7badb099.png)
for that matter it doesnt translate the $(_value). Am i doing something wrong ?

**Comment by algenty** [comment]
Not in mapping, try it in event with "replace text event"
You need to construct your metric to return the version.
It's also a possible evolution for next version to add a new variable like ${_metric}
