### ISSUE TITLE
Loading diagrams in XML format

### ISSUE THREAD

**Issue by VinuraD** [algenty/grafana-flowcharting#185]
Hello! I am new to grafana as well as to this plugin. I am generating an XML content like [this:](https://jsfiddle.net/3v9wueL6/1/) in a flask server and try to retrieve that in grafana by providing my localhost url. (I have enabled the download source option). Is this method possible? However the graph is not loading and no error is displayed either.

**Comment by algenty** [comment]
Hi @VinuraD 
Welcome to grafana users ;)
your xml must be begin by mxgraph, i can't see that in you model
try a graph in draw.io and clieck on menu Extra > edit diagram
See the xml like this example 
https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#RtVXbjtowEP2aPLYiMddHCLSVdhErIfWyL5Wxh8SqEyPjLKFfXxsPuYJ2K%2B0iHsbHM%2BOZc8ZOQOKs%2FKrpIV0rDjKIBrwMyDKIonAYRYH7D%2FjZI5PZ0AOJFhydamAr%2FgKCA0QLweHYcjRKSSMObZCpPAdmWhjVWp3abnsl26ceaAI9YMuo7KM%2FBDepR6fRpMa%2FgUjS68nheOZ3Mnp1xk6OKeXq1IDIKiCxVsp4KytjkI68Ky8%2B7sud3aowDbl5S8DzaLV4%2BJ4MN%2FSBLmK2Xv%2FeLD9hlhcqC2wYizXnKwO27oMz2VmKnIMOyOKUCgPbA2UOP1nhLZaaTNpVaM2dKqwjf9xVAGV%2FEu3QTWFsFkAcDwdtoLzbVVhxZYcMVAZGn60LBgyRXRyvam5OtVhjhNKGTlPEKI5HUiWuGbQGkvgfhEY9QufMKH2X1SKT3oEsHA%2FCTt4j3YF8UkdhhMqty04ZozLrIN3GouIyVtLF2Wxkf%2Fk1csylSFysUR1tlBcgrq7L4H10qIhHIcJpXwhyQ4jxRwlB3j7Zewnl3L0VlgrIOZpLJunxKFibPyiF%2BdmwfzkKP49wtSyR0cvi3KIXeO%2Bl6ZBri1OFZvD6fTVUJ2BeG8O%2BWA0xRjfEuGIaJDXipV3uLYXwhCclbCPVLISz9iyQSUdk3yZGNZ%2BsTqLu7SZRJ5HnoZfoMjBV27dmyC7rl9e7198vsvoH

**Comment by VinuraD** [comment]
Hi! Thanks for replying...! So this means that even if I generate the XML content of this example (your's) locally, I should be able to generate the graph? Hence, I just copied its XML content and only changed cell-ids (pardon me for my laziness) and returned it through the server to the plugin. But the graph still not showing up and an error comes up; "Error : TypeError: Failed to fetch" Is this kind of drawing not supported or can there be any other issue ? (I have not previously come through the mxgraph format as well)

**Comment by algenty** [comment]
try get started in doc

**Comment by VinuraD** [comment]
Okay...I will be referring the docs as well. Meanwhile this is the new XML content I am trying to retrieve to the plugin, [here](https://jsfiddle.net/d0bxaLtn/)

**Comment by VinuraD** [comment]
Hi, on the manual and repo site for the plugin ([site link](https://algenty.github.io/flowcharting-repository/DEFINITION_XML#Type)) you have put, "By selecting URL, flowcharting downloads xml file from url with mxgraph definition. /!\ NOT EMPLEMENTED". Does that mean this functionality is not implemented yet? Thanks

**Comment by algenty** [comment]
See configuration examples at https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1

**Comment by CrashLaker** [comment]
Hi @VinuraD 

You export it to XML.

![image](https://user-images.githubusercontent.com/4432491/84667074-41f63b80-aef8-11ea-8dcf-47b24e5c0f81.png)

uncheck compress
![image](https://user-images.githubusercontent.com/4432491/84667176-60f4cd80-aef8-11ea-99d1-67e8932e0236.png)

then output only the `<mxGraphModel>` content in your flask endpoint including `<mxGraphModel>` tag.
![image](https://user-images.githubusercontent.com/4432491/84667249-779b2480-aef8-11ea-9f48-6e2e6d9ad2c7.png)

then customize your shapes inside `<mxGraphModel>` as you wish

then in grafana flowcharting choose `Download Source` using source type `XML` (note you can do this with both CSV and XML just return the right syntax. both have its perks).
![image](https://user-images.githubusercontent.com/4432491/84667451-c1840a80-aef8-11ea-8f69-a47388aee53c.png)


this should work :)

**Comment by algenty** [comment]
or menu > extra > edit diagram

**Comment by CrashLaker** [comment]
omg @algenty ...
i didn't know that! o.O just saved a bunch os clicks 👏

**Comment by VinuraD** [comment]
Hi! I went through the examples and understand that it fetches mxgraph type content from draw.io and create the diagram. However, it is not clear to me how do I fetch similar xml content from a localhost server and make it work. You have mentioned "By selecting URL, flowcharting downloads xml file from url with mxgraph definition. /!\ NOT EMPLEMENTED". in  [github repo](https://github.com/algenty/flowcharting-repository/blob/master/DEFINITION_XML.md). Could you please be kind enough to elaborate how this url thing works? What does it mean "/!\ NOT EMPLEMENTED" ?

 [Here](https://community.grafana.com/t/algenty-flowcharting-plugin-getting-xml-data-from-a-localhost-to-generate-diagram/32070) are my settings that I use in the plugin. Thank you!

**Comment by CrashLaker** [comment]
something like this would work
![image](https://user-images.githubusercontent.com/4432491/84675548-cb127000-af02-11ea-8494-9f21dc6a14e6.png)

![image](https://user-images.githubusercontent.com/4432491/84675595-db2a4f80-af02-11ea-9810-1261db42cfb6.png)

![image](https://user-images.githubusercontent.com/4432491/84675648-eda48900-af02-11ea-9bf5-3e2c0f01ec96.png)

**Comment by VinuraD** [comment]
@CrashLaker Thanks for reply. It was my fault at the flask server implementation that I had not implemented Cross Origin Resource Sharing (CORS), Otherwise it was the same way. So, my bad! Thanks for the support @CrashLaker and @algenty

**Comment by VinuraD** [comment]
@CrashLaker Sorry for bothering again. You mentioned that both CSV and XML can be used as source type. Could you please guide me to source/doc or any example which shows that. In my case I can only select "Source Type: XML content" from the drop down menu in grafana. Thanks!

**Comment by algenty** [comment]
CSV only available since 0.9 released yesterday

**Comment by VinuraD** [comment]
That's great. I updated and checked the same process with source type csv. However, I encountered a different issue. But will start that in another new thread. Thanks!

**Comment by layer3lv** [comment]
Hi,

still, getting an error Error : "TypeError: Failed to fetch" if I want to host my file https://example.com/example.xml any suggestion why it's happening? grafana 8.2.5
