### ISSUE TITLE
Two metrics has same name

### ISSUE THREAD

**Issue by tdungsi1** [algenty/grafana-flowcharting#186]
I have two metrics which has the name name here.
![image](https://user-images.githubusercontent.com/26120816/84600480-9f13d200-aea3-11ea-95f8-9edcd77b50d0.png)
When i applied 1 metric on my diagram, the diagram shows them both. 
![image](https://user-images.githubusercontent.com/26120816/84600508-d08c9d80-aea3-11ea-93b1-854339b981c5.png)

My question is : I want to show each metric on different lines, is there a way to do so?

**Comment by techcubs** [comment]
Are those (Outbound traffic on Gi2/0/25) resuting from a single metrics query?

I am assuming you are defining these queries and then using the legend field as
Outbound Traffic On Interface {{ interface }}

**Comment by algenty** [comment]
You need to define an alias to distinguish the same metric

**Comment by tdungsi1** [comment]
Two devices have same interface,
