### ISSUE TITLE
FlowChart takes so long to load.

### ISSUE THREAD

**Issue by tdungsi1** [algenty/grafana-flowcharting#187]
Hello, noob again,
So i want to know why it takes so long to load this thing. Is there a way to actually fasten this loading speed? 25 seconds in total is soooooooooooooooooo long :( 
![image](https://user-images.githubusercontent.com/26120816/84763607-ad263780-aff6-11ea-9019-4bcb16137f47.png)

**Comment by algenty** [comment]
Hi,
Can you try last version released yesterday ?
Have you a big XML ? How many rules ?

**Comment by tdungsi1** [comment]
Hello,
I have 24 rules. 22 queries.
Just small XML with around 20 nodes.
Thank you.

**Comment by tdungsi1** [comment]
I tried but it still took too long to load.
Looks like it was trying to load this fetch thinggy.
![image](https://user-images.githubusercontent.com/26120816/84874928-7eb86300-b0af-11ea-86d4-edc10db2dbd7.png)

Thank you.

**Comment by algenty** [comment]
Can you active trace please in inspect conf and give me a screenshot of tables

**Comment by tdungsi1** [comment]
I will do it but now i'm facing a problem, the chart showing no metrics data. Everything is black 
![image](https://user-images.githubusercontent.com/26120816/84878174-ac9fa680-b0b3-11ea-9ba6-df289cb01a55.png)

**Comment by tdungsi1** [comment]
All queries are not working at the moment.

**Comment by tdungsi1** [comment]
Hello, 
FlowCharting plugin is showing as unsigned plugin. Is there a way to fix this?
Thank you.

**Comment by tdungsi1** [comment]
![image](https://user-images.githubusercontent.com/26120816/84884930-892d2980-b0bc-11ea-81d4-b8c4d640a47f.png)

**Comment by tdungsi1** [comment]
![image](https://user-images.githubusercontent.com/26120816/84885842-cb0a9f80-b0bd-11ea-86d9-19587f782c32.png)

**Comment by tdungsi1** [comment]
![image](https://user-images.githubusercontent.com/26120816/84885866-d2ca4400-b0bd-11ea-9a7d-e26df8d85971.png)

**Comment by tdungsi1** [comment]
I'm facing some problems here.
Please help me to fix them.
Thank you so much.

**Comment by algenty** [comment]
duplicate
