### ISSUE TITLE
Event/Animation Mappings - For "When" only All is available 

### ISSUE THREAD

**Issue by QualityAgileFlow** [algenty/grafana-flowcharting#188]
I try to set up a "Shape: blink". I have 3 levels defined, but I can only select "all" for "when" in the configuration. So the shape is always blinking, not.

What do I have to change, to let it only blink on a specific level?

**Comment by QualityAgileFlow** [comment]
after some refresh it worked.

**Comment by nickper** [comment]
I have the same problem, but for me refreshing doesn't help unfortunately and the it is quite some work to rebuild the dashboard.
