### ISSUE TITLE
Embedded zoom in/out buttons?

### ISSUE THREAD

**Issue by paregupt** [algenty/grafana-flowcharting#19]
First of all, the plugin works great for me. I want to take to the next level to make large complex tree-like diagram. I am wondering if it is possible to have an embedded zoom in/out button? Essentially, I want to show a high-level view by default but when required, drill down to the lowest level. This would be similar to + and - available on maps (including the maps plugin in grafana). Any guidance is much appreciated. Thanks.

**Comment by algenty** [comment]
Hi paregupt,
thanks for your comment, it's a pleasure.
i have a similar idea with notions of children and parents graph where parent takes state of children.
It's in the roadmap. For the zoom buttons, it's a good idea
You can also use group in draw.io (advanced) but not work at tis this : bug on values

Bg
Arnaud

**Comment by paregupt** [comment]
Thank for your quick response. If it helps to prioritize the zoom in/out buttons, here is the use-case: I am monitoring a large campus network. Devices are at core, distribution and edge. By default, we just want to show core when everything is working fine. When health degrades, we want to give option to the user to zoom in all the way to an edge device (think of multi-layer tree, with root, children and leaf). 

Questions:
1. Is zoom in/out button functionality of this plugin or does it need to be enhanced in draw.io?
2. The expand/collapse functionality of draw.io would have worked too for the above use-case but as per draw.io, the capability does not work with XML format. Any thoughts/workarounds?

Thanks again.

**Comment by algenty** [comment]
1. Zoom is already implemented in draw.io, just need implement it in plugin
2. Its a bug in my plugin, when i fix it, i'll mak an example demo
see demo on draw.io https://desk.draw.io/support/solutions/articles/16000042489-how-to-enable-disable-collapse-expand-

**Comment by paregupt** [comment]
I will wait for the enhancements. Thank you for making a very powerful plugin.

**Comment by algenty** [comment]
Hi,
Try last version, first version with zoom 
https://algenty.github.io/flowcharting-repository/CHANGELOG.html
![zoom_ani](https://user-images.githubusercontent.com/47012725/62025147-9658d580-b1d7-11e9-9457-1676f559c416.gif)

**Comment by paregupt** [comment]
Tried and tested. Works great. Thanks for the enhancement.

**Comment by Seana36** [comment]
@paregupt , How did you get version 0.4.0 to download to your grafana instance? I am still only seeing 0.3.0 as latest version.

**Comment by paregupt** [comment]
Here: https://github.com/algenty/flowcharting-repository/tree/master/archives

**Comment by algenty** [comment]
Hi,
Wait a little, i work on version where you can on the mouse pointer (Ctrl + mouse) instead center
See demo below, it's work but i must clean code to delete debug trace.

![floorplan_ani_pointer](https://user-images.githubusercontent.com/47012725/62513484-8a46c680-b81c-11e9-8d40-d369c4d43689.gif)
oom on pointer, see demo

**Comment by algenty** [comment]
Hi,
New snapshot available with zoom on pointer or zoom on shape with double click

**Comment by algenty** [comment]
Hi @paregupt, Hi @Seana36,
You can see the result at
https://twitter.com/gf_flowcharting/status/1158788115567403008

**Comment by algenty** [comment]
Thx for your "like" on twit @paregupt  👍

**Comment by paregupt** [comment]
@algenty 
I am unable to unzip the latest 0.4.0 snapshot. It worked for me when I downloaded it last time. Can you please check?

**Comment by bijwaard** [comment]
Hi Arnaud,
Double click zoom on icons works in August 8 version 0.40, cntrl+mouse has weird behavior in Firefox. In Firefox this key/mouse combination is already used for[ scaling the whole web-page](https://www.accessfirefox.org/Firefox_Keyboard_and_Mouse_Shortcuts.html), this no longer works for the page and instead all icons disappear (see screenshot below) in the flow-chart panel. Before the update, the panel resized with the rest of the webpage, keyboard shortcuts cntrl + '+' and cntrl + '-' still work.
![image](https://user-images.githubusercontent.com/6523124/63162241-4fb20a80-c022-11e9-9b3e-bb12c7ec7d15.png)

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi, I'll try to find a solution
