### ISSUE TITLE
CSV content downloaded from localhost, but configuration options not working

### ISSUE THREAD

**Issue by VinuraD** [algenty/grafana-flowcharting#191]
Hi! I used localhost server to fetch CSV content into grafana as did with XML content in [here](https://github.com/algenty/grafana-flowcharting/issues/185). I am using the example flowchart given on draw.io. However, the diagram does not show up. But when the configuration lines are removed (only csv lines left) a partial diagram appears. What could be wrong here or any possible solution? Thanks! 

The csv data used (the diagram does not show up for this);
<img width="623" alt="csv1" src="https://user-images.githubusercontent.com/31266374/84813389-8afbdc00-b02d-11ea-8461-e3967bec5621.png">

Removing the configuration lines (a partial diagram shows up);
<img width="472" alt="csv2" src="https://user-images.githubusercontent.com/31266374/84813498-aebf2200-b02d-11ea-8814-685d093180ec.png">

<img width="867" alt="csv3" src="https://user-images.githubusercontent.com/31266374/84813512-b4b50300-b02d-11ea-9ee4-e81f370976db.png">

**Comment by CrashLaker** [comment]
Hi @VinuraD 

there's kind of a tutorial I made [here](https://github.com/algenty/grafana-flowcharting/issues/161#issuecomment-636260520) which i also used flask

I'd suggest you to try it out.

you can either start with the default CSV from flowcharting or the one I mentioned there https://raw.githubusercontent.com/CrashLaker/plainrepo/master/flowcharting-example-vmware.csv

**Comment by VinuraD** [comment]
@CrashLaker thanks, it turns out that I need to remove all unnecessary white spaces (there were white spaces at the beginnings of each line) and now it works! Is there any source if you could direct me to, which contains similar csv examples like the [one](https://raw.githubusercontent.com/CrashLaker/plainrepo/master/flowcharting-example-vmware.csv) you put above (I found that there is no option to export mxgraph to csv available on draw.io)?

**Comment by xkilian** [comment]
Note sure I follow you... The whole point of CSV is to let mxgraph auto-create the layout. If you create a particular view, use the XML.

**Comment by VinuraD** [comment]
Maybe I'm not getting something here. I thought that generating CSV syntax rather than creating mxgraph models is much easier especially when creating diagrams dynamically, so that I won't have to use XML.

**Comment by CrashLaker** [comment]
Exactly what @xkilian said.
as i've mentioned [here](https://github.com/algenty/grafana-flowcharting/issues/185#issuecomment-644159760) each has its perks.

By writing CSV you won't know your shapes' absolute position beforehand.
You just set on the CSV that you want a TD (Top -> Down) placement. LR (Left -> Right) and so on and  it automatically arranges that for you.

I suppose you want to save the mxgraph already computed positions back to CSV but that's just not how it works. CSV -> mxgraph is **one way only**.

If you need to precisely customize your shapes then you have to "manually place/code" that.
The only lib that comes to mind is D3js.
Draw.io's CSV to diagram is basically [d3js + dagrejs](https://github.com/dagrejs/dagre-d3)

**Comment by VinuraD** [comment]
Thanks for the reply.  can we write csv for any mxgraph diagram that is possible? (neglecting the positions)

**Comment by CrashLaker** [comment]
afaik one would use the CSV template to display graph or hierarchical type of data.

you cannot group objects inside another like the image below:
![image](https://user-images.githubusercontent.com/4432491/84951048-36f10600-b0c6-11ea-9027-ab6768a7af4f.png)

you can get the same result using HTML but It won't be an element that flowcharting can map and therefore act on 

this [[vis]](https://github.com/algenty/grafana-flowcharting/issues/145#issuecomment-618382536) for instance I don't think it's possible to do that in CSV

**Comment by VinuraD** [comment]
I will look into this and thanks for the support!!!
