### ISSUE TITLE
FlowCharting takes so long to load.

### ISSUE THREAD

**Issue by tdungsi1** [algenty/grafana-flowcharting#196]
**Hello,
I dont have much experience about capturing packets and monitoring behavior. So i've been using Grafana for a while, i have found that every time i refresh my dashboard, it takes around 15 to 30 seconds to finish the loading. I press F12 to see what happening is in the network Tab, here the result.**
![image](https://user-images.githubusercontent.com/26120816/85388895-e1f33b00-b570-11ea-8d3f-5b7e855f674b.png)

**If you need any other information such as some other debug method, please show me how or give a document so i can research and send the information here.**

**Thank you and best regards, Algenty.**

**Comment by algenty** [comment]
Have you an AD blocker ? disable it if you have , 13s to download 1,3MB is too mutch.
In version 0.9.0, in inspect mode, you have a trace option, enable it and refresh data with console log opened

**Comment by tdungsi1** [comment]
No, i dont have AD Blocker. But it still takes around 20 seconds to load the dashboard.

**Comment by algenty** [comment]
Hi, if possible, can you try version 0.9.1 downloadable at
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by tdungsi1** [comment]
Hi, I tried but nothing has changed so far.
