### ISSUE TITLE
Fetch error: 404 Not Found

### ISSUE THREAD

**Issue by QualityAgileFlow** [algenty/grafana-flowcharting#199]
On upgrading to the latest version we got the following error:
`Plugin component error Error: Fetch error: 404 Not Found
  Instantiating http://grafana.xxxxxxx.de/public/@grafana/data
  Loading http://grafana.xxxxxxx.de/public/plugins/agenty-flowcharting-panel/module.js
  Loading plugins/agenty-flowcharting-panel/module
    at /public/build/0.4f5454f867a0cc2fe8dd.js:1`
We use Grafana 5.2.2.
Any ideas what could went wrong? 
Thanks

**Comment by algenty** [comment]
I need to test it on grafana v5
Maybe a regression on this version.
Can you try a restart of grafana ?

**Comment by algenty** [comment]
any news ?

**Comment by QualityAgileFlow** [comment]
I contact Ops tomorrow for the restart test

**Comment by algenty** [comment]
Fixed in last build
