### ISSUE TITLE
Guidance needed

### ISSUE THREAD

**Issue by alexbidule** [algenty/grafana-flowcharting#2]
Hi,

Thank you for writing this plugin, it looks very promising, but I'm not sure how to make it work.

I have tried to use a Graphite data source with a serie like:
alias(cumulative(xxx.stats_counts.processing.success), 'processingCount')

The output in a SingleStat panel works, I get a number.

Now, how am I supposed to say in the Flowcharting plugin that I want to have this value somewhere ?

Thank you

Alex

**Comment by algenty** [comment]
Hi Guidance,
Thanks for using Flowcharting, i'll try it with graphite and i'll make an animated gif for example.
Version 3 coming soon next week i think, 
French ?

**Comment by alexbidule** [comment]
Thank you ! Yes Arnaud, I am French indeed :)

**Comment by alexbidule** [comment]
Hi, any news on this please ? thank you

**Comment by algenty** [comment]
Salut bidule
0.3 not stable, 0.2.5 today or tomorrow.
Je m'active

**Comment by algenty** [comment]
0.2.5 pushed, in progress
you can found zip at 
https://github.com/algenty/grafana-flowcharting/files/3036986/agenty-flowcharting-panel.zip

**Comment by algenty** [comment]
dont forget to name your metrics with alias

**Comment by alexbidule** [comment]
Thanks a lot !

**Comment by algenty** [comment]
pas de quoi
