### ISSUE TITLE
Feature request: Variables inside the flowchart

### ISSUE THREAD

**Issue by scaarup** [algenty/grafana-flowcharting#20]
Hi.

I would like to be able to use variables inside the flowchart. 

I have a rather big multidatacenter infrastructure diagram in both production and staging environments. In Grafana i have an "environment" variable and it would make sense if url-names, servernames etc could change when I switch the environment variable.

Thank you.

**Comment by algenty** [comment]
Hi scaarup,
Thx for your feedback, what is your version ?
Yes, you could. granafa team is very long to publish a new version (>1month).
In version 0.4.0, variables is implemented, try it
https://algenty.github.io/flowcharting-repository/CHANGELOG.html
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by scaarup** [comment]
Hi algenty.

Thanks for a quick reply. I am on an old version 0.2.5. But it is actually the latest one referred to by Grafana here: https://grafana.com/plugins/agenty-flowcharting-panel.

But awesome to see its already there, I will try the 0.4.0 :).

**Comment by scaarup** [comment]
I am 0.4.0 now. It is not clear to me how to accomplish what I want. In draw.io I have a simple text-box. I have tried with the variable syntax ${}, but that is not translated.

**Comment by algenty** [comment]
ok,
Many possibility, 
you can pass current var by link with "Add params to link".
You can add variable in xml definition like value="${myvar}"
You can add variable value by text mapping in type string

Example, Open it in large screen
![ani_variables_example](https://user-images.githubusercontent.com/47012725/59499344-855a3c00-8e97-11e9-9955-419de94430c5.png)

BG,
Arnaud

**Comment by algenty** [comment]
Since 0.3.0, you can rename id of your shapes/arrows for more maintenance,
see
https://algenty.github.io/flowcharting-repository/STARTED.html

**Comment by scaarup** [comment]
If I update the value="" directly in the XML it seems to work. However it doesn't switch when I switch the variable.
Also if I edit the diagram in draw.io and save it, the variables are not resolved at all. The text is just saying ${env}.

**Comment by algenty** [comment]
draw.io transform ${} with http code

**Comment by algenty** [comment]
its good for you ?
I can upgrade it with your suggestion

**Comment by algenty** [comment]
Verify xml if value have ${}
I close ticket
Dont forget to star project if u like it.

BG
Arnaud
