### ISSUE TITLE
Multiple values under with discrete color variables (enhancement request)

### ISSUE THREAD

**Issue by thecowinheat** [algenty/grafana-flowcharting#201]
This is my absolute favorite plugin for Grafana.  I have some overly complex flowcharts as I'm trying to map multiple variables to a network object for visual alerting of issue.  this is requiring I create 4-12 mappings per element.  Would be nice under a single mapping to have multiple query fields and color mappings for each.  This would help simplify the mappings and keep things organized.

**Comment by algenty** [comment]
I don't understand, 1 rule => 1 or n metrics (if regex) = > n shapes

**Comment by thecowinheat** [comment]
Yup regex works but not all variables being pulled in are the same type or need the same color values.  

Example:  Pulling in data for all ports on a switch to visually show the port status (48 unique shapes on an image of a switch. See example)

-one value is port active (1 up, 2 down) (red for down, green for up)
- one value is fiber laser power (anything below .1 red, anything above green)
- One value is RX,TX speed (anything above zero yellow, anything above 1000000 green)

Now with the above example I cannot have a color scheme that shows red when one of these is false.  I also do not want to do math on the values above to normalize them as this would throw off the data on the hover over from the user giving false values. 

Right now I have to create three different mappings to do the above due to the coloring requirements resulting in 144 mapping rules.

Would be nice if under a Mapping you could add Regex expressions with individual color mapings which would reduce the above to 48 mappings.

Also this would possibly allow us to only show the graphs of the items we need (ie Rx,Tx of a port and graph port status)

Hope this is descriptive enough.  If you need additional info I'm happy to provide.  If its not possible that's cool.  I appreciate you even reaching back out!!!

<img width="786" alt="Screen Shot 2020-07-06 at 7 48 32 AM" src="https://user-images.githubusercontent.com/17133362/86594707-1bf31280-bf5d-11ea-84aa-6ffe99eb0952.png">

**Comment by algenty** [comment]
duplicate
https://github.com/algenty/grafana-flowcharting/issues/232
