### ISSUE TITLE
Multiple graphs on same dashboard (copied elements) not all updating

### ISSUE THREAD

**Issue by thecowinheat** [algenty/grafana-flowcharting#202]
In a single dashboard if you reuse or create a copy of a flowchart dashboard and reuse some of the elements then colors in one of the graphs de-saturates and sometimes the same elements do not update based on status changes.  Moving to a dedicated row or another panel fixes the issue.

**Comment by algenty** [comment]
Hi,
It's already in the roadmap for the version 1.0.0

**Comment by thecowinheat** [comment]
Cool!  Ill close this then as you are aware of it.
