### ISSUE TITLE
[HELP] This is not an issue.

### ISSUE THREAD

**Issue by tdungsi1** [algenty/grafana-flowcharting#208]
Hello,

I'm building a network weather map, I want to make an export plugin to get some specific report.
So I'm developing a Grafana App Plugin to collect data from your plugin (FlowCharting) and I want to collect the json within interval time to do some calculations. Your app queries data overtime and my app queries your json simultaneously, parallel. That's how I think of a way to keep updating the data and process them. Do i need to make a new data source plugin to collect your json file? Is there a way that my app can collect the json file? Please teach me if there is.

Thank you for reading.

**Comment by tdungsi1** [comment]
Or my app can be just a little button like this
![image](https://user-images.githubusercontent.com/26120816/87927797-fa8e3c80-caad-11ea-90ba-c7db96dc02f4.png)
The idea is when I click, it will generate a report which includes such as "Export all connection lines  and days that were 95% bandwidth in the last month"

**Comment by CrashLaker** [comment]
I'm not sure I understand this.
Can't you just connect your plugin to the same source flowcharting is receiving its feed from?

**Comment by tdungsi1** [comment]
I want to use that plugin to get the json file from another dashboard.
