### ISSUE TITLE
open links with target _self 

### ISSUE THREAD

**Issue by baggins466** [algenty/grafana-flowcharting#212]
Is there a way to control the target of links configured in the plugin. By default, all links open in a new window I need the links to open in the same window or iframe.

**Comment by algenty** [comment]
Hi @baggins466,
Thx for your feedback 
Not at this time, Flowcharting use link function from draw.io libs. In draw.io, you cannot define how to open a link.
Duplicate with https://github.com/algenty/grafana-flowcharting/issues/108
