### ISSUE TITLE
In Firefox Browser, when I tried to zoom in a panel using flowcharting plugin the adjacent panel which also uses flowcharting plugin moves 

### ISSUE THREAD

**Issue by GokulSNarayan** [algenty/grafana-flowcharting#214]
![flowchartingPanelIssue](https://user-images.githubusercontent.com/44142590/89267604-102a6700-d655-11ea-833f-f56957f0fc76.gif)

I tired this in chrome and it works perfectly, but when I take it in firefox the adjacent panel also gets zoomed in or when I move it in one panel, it takes affect in the adjacent one.

**Comment by algenty** [comment]
Hi @GokulSNarayan 
First at all, very nice example of usecase, can i share it ?
I'll try to fix it in 9.1, release date at september.

**Comment by GokulSNarayan** [comment]
Although its a bug, its a great feature 
![image](https://user-images.githubusercontent.com/44142590/89286778-6c4eb480-d670-11ea-9ecd-071221e12b83.png)

**Comment by algenty** [comment]
Try this 😁
https://github.com/algenty/grafana-flowcharting/issues/242
