### ISSUE TITLE
Can't find Flowcharting Visualization in Grafana 7.1.3

### ISSUE THREAD

**Issue by theodiefenthal** [algenty/grafana-flowcharting#217]
Due to restricted internet in our prod environment, I build my custom Grafana Image with installation of plugins via CLI like so:

```
FROM grafana/grafana:7.1.3
# Important: Change default plugin dir so that a volume mount to /var/lib/grafana for user data (dashboards, data sources)
# won't override the installed plugins
USER root
RUN mkdir /grafana-plugins && chown grafana:grafana /grafana-plugins
ENV GF_PLUGIN_DIR=/grafana-plugins
USER grafana

# Plugins...
RUN grafana-cli --pluginsDir "${GF_PLUGIN_DIR}" plugins install agenty-flowcharting-panel
```

I then run my docker-container with environment variable `GF_PATHS_PLUGINS=/grafana-plugins`  set. This works nicely for all of my plugins ( e.g. piechart panel, FLUX beta data source plugin, ..). 

I also see the flowcharting plugin being installed in the plugin overview:
![grafik](https://user-images.githubusercontent.com/4670569/90399578-74a8e580-e09b-11ea-8afa-71933aa15f60.png)

However, if I create a new dashboard with a new panel, there is no flowcharting visualization I could choose. It simply doesn't exist, independent of the data source I choose (InfluxDB, Flux, Grafana Random Walk)

![grafik](https://user-images.githubusercontent.com/4670569/90399686-a621b100-e09b-11ea-8bba-9717fe56f084.png)

Am I missing a step here or is this a bug? According to documentation, I just need to make sure that the plugin is installed (yes!) and then can use it as visualization.

**Comment by algenty** [comment]
Are you in production mode ?
I think since 7.1, unsigned plugin isn't visible

**Comment by algenty** [comment]
see https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/
plugin is unsigned at this time

**Comment by theodiefenthal** [comment]
Ah thank you @algenty , so it indeed was a configuration issue. I set `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=agenty-flowcharting-panel` and now it works fine :)  
Sorry for the inconvenience of opening a ticket. Another of my plugins which is unsigned _seemed_ to work fine (Could see it in a drop down for datasource selects) so I didn't image this to be the problem.
