### ISSUE TITLE
Graph inspect id not displayed correctly

### ISSUE THREAD

**Issue by ale-nieto** [algenty/grafana-flowcharting#219]
When I enable the Graph Inspect id toggle, all the sub content is behind the other buttons, it does not get pushed down.
It happens on linux or Windows, no matter what browser I use.
Running Grafana v7.1.3 (5723d951af) on Centos 8.

Enabled:
![2020-08-25_22-46](https://user-images.githubusercontent.com/24699341/91245832-cfd67a00-e724-11ea-821b-ebd737552baf.png)
Disabled:
![disabled](https://user-images.githubusercontent.com/24699341/91245890-f1cffc80-e724-11ea-84cb-a35f74ae87e8.png)

**Comment by algenty** [comment]
hI
aready issue opened for that
thx for your feedback
