### ISSUE TITLE
Mixed Datasource multiples querys Mapping

### ISSUE THREAD

**Issue by guillermodep** [algenty/grafana-flowcharting#220]
I have mixed datasource but in the mapping I cannot use two or more querys, the mapping just use the first one. 

![image](https://user-images.githubusercontent.com/58941444/91618121-f2a0a280-e95f-11ea-8cd4-8218977a2542.png)

**Comment by algenty** [comment]
you need to select one or enter a regex in "apply tometrics"

**Comment by algenty** [comment]
https://github.com/algenty/grafana-flowcharting/issues/232
