### ISSUE TITLE
Dynamic charts

### ISSUE THREAD

**Issue by vishnubraj** [algenty/grafana-flowcharting#222]
Hi, I am planning to use CSV for Dynamic charts,  can we add metric details also in the CSV? or it has to be manual.
Sorry, I couldn't find this in the documents so created a ticket.

**Comment by algenty** [comment]
Hi @vishnubraj,
Only graph can be dynamic with option "url "download"
Enter an url with an api server to generate the CVS.
The queries and metrics are managed by grafana engine, not by flowcharting.
See for more examples @CrashLaker issues
https://github.com/algenty/grafana-flowcharting/issues/191
https://github.com/algenty/grafana-flowcharting/issues/162
https://github.com/algenty/grafana-flowcharting/issues/161

BR
Arnaud

**Comment by vishnubraj** [comment]
Thanks @algenty
