### ISSUE TITLE
Feature Request: Multiple Mappings from 1 Metric

### ISSUE THREAD

**Issue by nfonz23** [algenty/grafana-flowcharting#223]
Hi,
I have 1 Metric which returns a table of information, an example below:

Name, Status, uptime

I would love to be able to match objects automatically based on the "Name" column in my metric. This would save a lot of time in creating individual metrics and mappings manually for each object.

**Comment by algenty** [comment]
see https://github.com/algenty/grafana-flowcharting/issues/232
