### ISSUE TITLE
Tag & Parameters on Link mappings

### ISSUE THREAD

**Issue by mpiotrowski-pandq** [algenty/grafana-flowcharting#229]
![image](https://user-images.githubusercontent.com/71433353/95753233-9be9f080-0ca1-11eb-8bac-8d669627577b.png)

Enabling "Params" is giving as prefix '%3F' (?) sign also, it actually block any extra tag setting in new scheme/page.
Print screen below for ilustration view of such case :

![image](https://user-images.githubusercontent.com/71433353/95753991-af498b80-0ca2-11eb-9b63-c2d78792c3f3.png)

Regards,
Mariusz

**Comment by algenty** [comment]
I will fix it in 9.1

**Comment by algenty** [comment]
@mpiotrowski-pandq 
If you link mapping has not parameter, you can add link directly in draw.io schema

**Comment by algenty** [comment]
what is your version ? can't reproduce 
![image](https://user-images.githubusercontent.com/47012725/98797441-dcf23380-240c-11eb-9ce3-2b6a9deafaa8.png)

![image](https://user-images.githubusercontent.com/47012725/98797331-b46a3980-240c-11eb-9002-626721916fc2.png)
