### ISSUE TITLE
0 decimals for number is not remembered

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#23]
I can successfully change the decimals for number type under Mapping. However, when I set it to 0 decimals, save and switch dashboard it is back to the default 2 decimals.

**Comment by algenty** [comment]
thanks for your feedback
which is your version ?

**Comment by bijwaard** [comment]
This is with the 0.40 snapshot

**Comment by algenty** [comment]
ok i'll try to reproduce it and i come back

**Comment by algenty** [comment]
Lol, i found the problem,
I dont understand, first i try with 5 decimals and it's work.
In the code, i have  this.data.decimals = obj.decimals || 2;
if decimal = 0, javascript understand false then it takes 2 by default.
I test and i build a snapshot

**Comment by bijwaard** [comment]
I prefer some stricter typing such as in C++ and python3.x;-)
Guess you would need a more precise handling of the non-existence of obj.decimals. Hope that fixes it.

**Comment by algenty** [comment]
Hi @bijwaard,
Decimal is fixed in new snapshot version
https://algenty.github.io/flowcharting-repository/ARCHIVES.html
Tooltip with metrics added in this version

BR,
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud,

Great! I'll check later, I don't have proper Internet  these days.

Dennis

⁣Sent from TypeApp ​

**Comment by bijwaard** [comment]
just verified that the fix appears to work in the new snapshot, great work!

**Comment by algenty** [comment]
you're welcome
