### ISSUE TITLE
Is There An Easier Way To Link Multiple Values?

### ISSUE THREAD

**Issue by calebcoverdale** [algenty/grafana-flowcharting#232]
Hey there, 

I am trying to go through and map switch up/down status but I am having to create these manually for each port...... mostly because I don't know what the appropriate way would be to link setup these up automatically..... does anyone have any quick tips?

There's a screenshot of what I am doing now: 
<img width="2529" alt="CleanShot 2020-10-22 at 13-30-47@2x" src="https://user-images.githubusercontent.com/5885864/96920836-ecfca000-146a-11eb-9902-35a5a6fb9641.png">

I would love it if I could somehow set the objects up as the values.... just looking for any advice.

**Comment by algenty** [comment]
Hi, 
At this time, no way.
The query table is managed by grafana, not by flowcharting

sorry
BR
Arnaud
