### ISSUE TITLE
Need feedback and tester for 0.9.1

### ISSUE THREAD

**Issue by algenty** [algenty/grafana-flowcharting#233]
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

### Added
  - New initialization engine for drawio libs
  
### Fixed
  - Fixed : Inspect mode [(issue #209)](https://github.com/algenty/grafana-flowcharting/issues/209)
  - Fixed : Label position in shape [(issue #147)](https://github.com/algenty/grafana-flowcharting/issues/147)   
  - Fixed : Initialization of first model
  - Fixed : Display refresh between "edit mode" and "dashboard mode" in grafana v7 [(issue #205)](https://github.com/algenty/grafana-flowcharting/issues/205)

**Comment by bijwaard** [comment]
Hi Arnoud,

I just installed the updated plugin snapshot. The main functions still seem to be working great (I'll keep it running to further monitor it), label position looks correct. However, (at least in firefox), the inspect mode is still drawn over debugging mode stuff.
![image](https://user-images.githubusercontent.com/6523124/97145746-fcc7fd00-1766-11eb-91cb-397e9500e65b.png)

Kind regards,
Denins

**Comment by algenty** [comment]
My fault,
I forget to push new image sorry, 
Can you try again ?

![image](https://user-images.githubusercontent.com/47012725/97156341-e164ee00-1776-11eb-9f3b-f4a6847d2704.png)

BR
Arnaud

**Comment by bijwaard** [comment]
No problem, just re-tested. The inspector does no longer overwrite the debug Mode.
No change to the initially empty diagram in Edit mode.

**Comment by algenty** [comment]
i see that,
try to reproduce it

**Comment by lawhoisun** [comment]
Everything disappears when the changes are applied.
Re-editing the panel shows that only the metrics are retained.
Using Chrome
![Screenshot 2020-10-27 075800](https://user-images.githubusercontent.com/16285164/97240818-44fc2380-182a-11eb-90f1-6c21f3b536cf.png)

**Comment by algenty** [comment]
Hi all,
Thx for your feedback.
New image are 0.9.1 available
at https://algenty.github.io/flowcharting-repository/ARCHIVES.html

## [[0.9.1 SNAPSHOT]](https://algenty.github.io/flowcharting-repository/archives/agenty-flowcharting-panel-0.9.1-SNAPSHOT.zip) - 2020-10-30
### Added
  - New initialization engine for drawio libs
  - New notifier handler in panel.
  
### Fixed
  - Fixed : Inspect mode [(issue #209)](https://github.com/algenty/grafana-flowcharting/issues/209)
  - Fixed : Label position in shape [(issue #147)](https://github.com/algenty/grafana-flowcharting/issues/147)   
  - Fixed : Initialization of first model
  - Fixed : Display refresh between "edit mode" and "dashboard mode" in grafana v7 [(issue #205)](https://github.com/algenty/grafana-flowcharting/issues/205)  
  - Fixed :  zoom on text without witdth and height
  - Fixed : Disable select text when double click for zoom

BR
Arnaud

**Comment by algenty** [comment]
Be carefull, i notice a new bug, when i modify a model in a one panel with flowcharting, all flowcharting panels are modified
