### ISSUE TITLE
Is it possible to add a time slider directly in flowcharting?

### ISSUE THREAD

**Issue by Arthur380** [algenty/grafana-flowcharting#239]
Hello,

I am using flowcharting to create a synoptic.
But I need to add a time slider to it to be able to display the last value of the requested date.

On the following screenshot I present to you what I did with html + iframe (show an other dashboard without time slider and we control it by the url).
I developed the time slider in html and I use iframe to show my synoptic.

![image](https://user-images.githubusercontent.com/45686298/98261322-9fad2200-1f84-11eb-95fd-6319c2709828.png)

This is exactly what I want in the final result, but the big problem encountered by this solution is that the iframe is reloaded each time the cursor is moved on the time slider which leads to a significant loading time.
So I can't use iframe like I currently do

Did you know if it's possible to do what I want directly in flow charting?
If not, did you know another solution to do that?

Thanks !

Regards,

Arthur

**Comment by CrashLaker** [comment]
afaik it's still not possible.
although you could build that slider on another panel. a few docs that could be of help:
* https://demo.factry.io/d/ZhjweprWk/city-water-tank-flowchart?orgId=1 (check "Replay Controls")
* https://www.factry.io/blog/tutorial-using-the-grafana-flowchart-plugin-to-create-a-process-diagram/?utm_medium=social&utm_source=twitter
* https://github.com/factrylabs/grafana-replay-controls (you could tweek the controls here into a slider)

**Comment by xkilian** [comment]
You mean it is not possible, because flowcharting does not support it. A plugin like  [https://grafana.com/grafana/plugins/pr0ps-trackmap-panel](https://grafana.com/grafana/plugins/pr0ps-trackmap-panel) can match hover position in a graph to show a data point in the GPS map.

**Comment by Arthur380** [comment]
Thanks for you answer !
