### ISSUE TITLE
The query statement in grafana cannot be used normally after more than 26

### ISSUE THREAD

**Issue by m199369309** [algenty/grafana-flowcharting#243]
In grafana 7.3.1, the number of query statements ranges from A-Z. After more than 26 query conditions, NA is the query number. If there are multiple query conditions with NA query numbers, it will cause flowchartting to fail to display normally

**Comment by CrashLaker** [comment]
Are you using TestData DB?
You can see [here](https://play.grafana.org/d/ubByxW2Gz/flowcharting-dc-floor?orgId=1) an example of grafana 7.3.1 with more than 100 queries.

**Comment by algenty** [comment]
ticket for it exits in grafana issues. It's not a limit of flowcharting
