### ISSUE TITLE
Plugin is not signed

### ISSUE THREAD

**Issue by meshkov** [algenty/grafana-flowcharting#244]
![image](https://user-images.githubusercontent.com/1703670/98938375-d2ad6380-24f8-11eb-8119-459af2ffe417.png)

Grafana Labs checks each plugin to verify that it has a valid digital signature. Plugin signature verification is part of our security measures to ensure plugins are safe and trustworthy.
[https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/](https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/)
Grafana v7.3.2
Flowcharting v.0.9.0

**Comment by algenty** [comment]
I know, in next level plugin is signed
