### ISSUE TITLE
Mermaid Format support for flowchart source

### ISSUE THREAD

**Issue by sohooo** [algenty/grafana-flowcharting#245]
The latest release includes _CSV Format support for flowchart source_ as a new feature.

As we have architecture diagrams based on Mermaid.js syntax, the [draw.io import feature for Mermaid](https://drawio-app.com/create-mermaid-diagrams-in-draw-io/) would also be very useful in grafana-flowcharting.

**Comment by algenty** [comment]
Mermaid is supported in draw.io but all diagram is as one object
