### ISSUE TITLE
mapping value from table to object by label

### ISSUE THREAD

**Issue by arnitolog** [algenty/grafana-flowcharting#247]
Hello,
Let's imagine we have a table:
podA  value1
podB  value2
podC  value3           
podD  value3
And we have a diagram with podA-podD objects
I'm wondering is it possible to map values from the table to the corresponding object and use them as label/text

**Comment by CrashLaker** [comment]
Hi.

as of now i don't think it's doable. 
what you can do is pre-render your drawio xml.
there had been some similar thoughts [here](https://github.com/algenty/grafana-flowcharting/issues/145#issuecomment-616017915)

regards, c.

**Comment by arnitolog** [comment]
I see, thank you @CrashLaker
