### ISSUE TITLE
Feature Request: Support interactive changes with Shared Crosshair option enabled

### ISSUE THREAD

**Issue by librilex** [algenty/grafana-flowcharting#25]
It would be really great if FlowCharting would support the _Shared Crosshair_/_Shared Tooltip_ options (from the _Graph Tooltip_ setting in the _Panel Options_ in the dashboard settings) and interactively change the numbers/formatting according to the crosshair position from another panel. This would give the option to easily scroll through history and display the state of the diagram at the selected time.

Here is a simple example dashboard of what I mean: At the top, there two graph panel which shows an ambient temperature and a mean temperature of three different sensors. The bottom diagram is a simple Flowcharting panel, showing the temperature values of the three sensors for the average. At the moment, flowchart only shows a single value according to the selected time. With this feature request, the values would change interactively (as shown in this GIF mockup):
![InteractiveChangeCrosshair](https://user-images.githubusercontent.com/26027208/60770946-04cadc00-a0e1-11e9-9c72-b461159b8f10.gif)

**Comment by algenty** [comment]
Hi librilex,
Thanks for your feedback,
it's  great idea, not simple, i don't know how, i'll try to reproduce your graph.
i'll keep this feature for next versions

BG
Arnaud

**Comment by algenty** [comment]
Implemented in V0.9.0
![floorplan_graphhover](https://user-images.githubusercontent.com/47012725/83437118-7c170600-a43f-11ea-8d45-a4050080c290.gif)
