### ISSUE TITLE
List of items is obscured by control elements.

### ISSUE THREAD

**Issue by VyacheslavIsaev** [algenty/grafana-flowcharting#250]
Hello!

Amazing plugin! Really love it.

I tested it in Firefox and Chrome on both platforms I have an issue with Inspector.

List of items appears beneath buttons. 
So, the list is obscured by them.

I haven't found mentioning of such issue. 
Is it something wrong with my setup?

![Screenshot 2020-11-28 203228](https://user-images.githubusercontent.com/312815/100524506-f7702f00-31b8-11eb-8041-4dfbc27ec117.jpg)

Thank you!

**Comment by algenty** [comment]
Hi @VyacheslavIsaev,
thx
bug fixed in 9.1.0 but not published on grafana.com at this time (tests in progress)
available at https://algenty.github.io/flowcharting-repository/ARCHIVES.html
