### ISSUE TITLE
flowcharting panel can not save

### ISSUE THREAD

**Issue by bigHave** [algenty/grafana-flowcharting#253]
**What did you do?**
I installed flowcharting for my grafana, then I tried to draw a flow chart by XML source file generated by draw.io

**What did you expect to see?**
I see my chart, all good so far. 
![image](https://user-images.githubusercontent.com/9249583/100734372-8922ab00-340a-11eb-9c5d-b60baf91f860.png)

but when I try to save this panel, something weired happend.

**What did you see instead? Under which circumstances?**
when I click "back" button, my chart disappeared:
![image](https://user-images.githubusercontent.com/9249583/100734423-a0619880-340a-11eb-9332-ab3e92828d19.png)
![image](https://user-images.githubusercontent.com/9249583/100734456-ace5f100-340a-11eb-9fc7-3a9b23362e58.png)

edit my panel again, all settings are gone:
![image](https://user-images.githubusercontent.com/9249583/100734551-d0a93700-340a-11eb-9ed2-6e4bf2dae554.png)

**Environment**

grafana:v6.7.4(8e44bbc5f5)
flowcharting:0.9.1

Tried many times, nothing changed.
and no error logs in browser console

I'm not sure is this a bug or just a grafana version issue?

appreciated for any suggestions

**Comment by algenty** [comment]
Hi @bigHave 

Can you open the console and see if you have an error ?

**Comment by bigHave** [comment]
> Hi @bigHave
> 
> Can you open the console and see if you have an error ?

Hi @algenty , thanks for replying, I opened the console but can not see any error.

but I found my issue is similar with #197 , so I tried version 0.9.1 and problem solved.
