### ISSUE TITLE
Flow Charting plugin Inspect Abnormal display

### ISSUE THREAD

**Issue by bbker** [algenty/grafana-flowcharting#259]
**What happened**: Flow Charting plugin Inspect Abnormal display

**What you expected to happen**: Grafana version 7.0.3 is displayed normally

**As the picture shows**:

![](https://s3.ax1x.com/2020/12/03/DTxSsS.png)

**Environment**:
- Grafana version: 7.3.0 or up
- OS Grafana is installed on:Windows Server 2016
- User OS & Browser:Windows Edge\Chrome
- Grafana plugins:FlowChart plugin version:0.9.0

**Comment by algenty** [comment]
duplicate with 
https://github.com/algenty/grafana-flowcharting/issues/209
