### ISSUE TITLE
Feature Request:Support shape show/hide by value changed

### ISSUE THREAD

**Issue by nh-live** [algenty/grafana-flowcharting#26]

**Comment by algenty** [comment]
i dont understand

**Comment by nh-live** [comment]
example: 
case:   value > 1 ,display shapeA,hide shapeB
case:   value == 0,display shapeB,hide shapeA

**Comment by algenty** [comment]
@AndreasTheCat have have the same idea, i don't when and how i'll implement this idea but i keep this idea.

BR
Arnaud

**Comment by AndreasTheCat** [comment]
Guys, sorry I've got no time to implement this for I'm too busy.

**Comment by bijwaard** [comment]
This show/hide behavior looks similar my remark in ticket #22.

> The circuit open/close could alternatively be accomplished when the visibility of a shape could be mapped. You could then draw one or more alternatives with draw.io and make one of them visible based on e.g. a threshold or variable.

**Comment by algenty** [comment]
i'll try to integrate it in 0.4  or 0.5  in august

**Comment by rlcomte** [comment]
+1 for this enhancement

**Comment by algenty** [comment]
@nh-live @rlcomte 
Implemented in 0.8.0
