### ISSUE TITLE
Embed Gifs

### ISSUE THREAD

**Issue by CrashLaker** [algenty/grafana-flowcharting#268]
Hi,

Is it possible to embed gifs in drawio/flowcharting?

for instance
![Scada_std_anim_no_lang](https://user-images.githubusercontent.com/4432491/105367131-e3581500-5bde-11eb-9f92-255eff30f33f.gif)

having a spinning wheel animation etc

Regards,
C.

**Comment by algenty** [comment]
in draw.io maybe with a copy/past, but you only can color the border

**Comment by CrashLaker** [comment]
oh yeah! it works!
perhaps i was copy pasting it wrongly

ty
