### ISSUE TITLE
object ID reference alternative

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#27]
Dear Arnoud,
Thanks again for your great plugin. Currently the draw.io ID attribute is used to reference wxGraphModel objects. I learned the hard way that this can corrupt the drawing when I tried to swap the names of two objects.

As an alternative mapping approach, an additional attribute could be used on the object, e.g. "flowcharting_id", which could leave the original draw.io object references intact. This would give the following advantages:
- you can already provide the names in draw.io, i.e. via Edit Data
- when you copy the draw.io object, it will retain the same ID, so you can easily adjust it in draw.io and/or the FlowCharting plugin. Without changing the name I could expect it to have the same mapping behavior as the original object.
- it would no longer be possible to corrupt the drawing by trying to swap object-ids
- draw.io library objects can be created that already have an initial flowcharting_id.

With a highly structured diagram (i.e. with lots of groupings), it would become possible to automatically create the flowcharting_id when each element has a name or label attribute. I.e. in the DSP flow diagram below where a voltage and a current sensor together calculate power at 50Hz from 4KHz raw samples. E.g. the ID of the port pq_vec within ComplexPower within LV-Sensor VT, could then be automatically created as flow_charting_id = LV-Sensor VT/ComplexPower/pq_vec. I could envisage a "create object names from name attribute" button in the Inspect tab of the FlowCharting plugin. This could considerably speed up configuration of the mappings.

![image](https://user-images.githubusercontent.com/6523124/60795317-be6e8f00-a16b-11e9-8a7e-13f68e229a78.png)

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi Dennis,

Nice diagramm again, 

Its already in roadmap, if you look in mapping tab, you can found "props" field with only id. In next versions, it will possible to map with values or properties.
Now, you can rename id in inspect tab by double clic on id name, i added this function because generated id by draw.io ar not friendly user.

BR
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud,
Great that this is already on the roadmap! Is it also planned to enable using hierarchical naming from corresponding attribute of grouped objects?

I understand that draw.io ID is not so user friendly, and have edited them to get a functional diagram. This ID is mainly meant to keep the objects unique and maintain relations between objects. I would rather not touch these IDs to keep the drawing consistent.

Kind regards,
Dennis
