### ISSUE TITLE
 link mappings when always not working on nodata query

### ISSUE THREAD

**Issue by wagnersmjunior** [algenty/grafana-flowcharting#270]
When a link Mappings is configured to another url, not work when query return no data. How can I get it with no data?

**Comment by algenty** [comment]
First Hi,

if you have no conditions for link, edit and add link into draw.io
![image](https://user-images.githubusercontent.com/47012725/106031368-7ad1d200-60cf-11eb-8173-c384fc4b3a1d.png)

**Comment by wagnersmjunior** [comment]
Thanks a lot! Working fine!
