### ISSUE TITLE
Word Wrap in object

### ISSUE THREAD

**Issue by Seana36** [algenty/grafana-flowcharting#28]
I would like to know if there is a way to do word wrapping within an object. You can see in the picture the labeling on the box is very large, I would like it to wrap inside the box.  Below is how I have defined the XML for that box 

        <object label="VERIFY_SUPPCANCEL_TLS_REMOVE" id="101">
            <mxCell style="rounded=0;whiteSpace=wrap;html=1;fillColor=white;strokeColor=black;" parent="1" vertex="1">
                <mxGeometry x="60" y="0" width="120" height="60" as="geometry"/>
            </mxCell>
        </object>

![image](https://user-images.githubusercontent.com/11064014/61305037-1a629480-a7b8-11e9-9b73-5d964c64f49b.png)

**Comment by algenty** [comment]
Hi Emily,
Thx for your feedback. 
Flowcharting plugin uses draw.io libs, if in draw.io, text is more large than box. it's the same in Flowcharting.
Edit it in draw.io and change size of box.

BR,
Arnaud
