### ISSUE TITLE
Issue while trying to color text

### ISSUE THREAD

**Issue by vopierre** [algenty/grafana-flowcharting#29]
Hi Arnaud, first of all, thank you very much for the plugin ... it's great !!!

I'am encounting an issue when I try to colorize a value, It's works, but I have the background going white

In draw.io
![image](https://user-images.githubusercontent.com/40362619/61308269-2bc79300-a7f0-11e9-97ac-4e7472b22391.png)

 
In grafana
![grafana2p](https://user-images.githubusercontent.com/40362619/61308208-09ce1080-a7f0-11e9-9593-4e0b349d9bc8.PNG)

If you could figure out what's going on, it would be great

Many thanks again for you work

Pierre

**Comment by algenty** [comment]
Hi pierre,
Thx for your feedback,
Yes it's a bug, i'll fix it speedly in 0.4.0

BR
Arnaud

**Comment by algenty** [comment]
fixed in last snapshot
