### ISSUE TITLE
Overlapping text while creating a flow chart

### ISSUE THREAD

**Issue by muralikanagala** [algenty/grafana-flowcharting#291]
Hi All,

I am new to Grafana flowcharts and seeing the below issue while creating my first flowchart. 
I am seeing this overlapping text in Grafana which is very uncomfortable to work with. 
As this is not a signed plugin I have tried overriding that in grafana.ini as well but still see the same problem.

![image](https://user-images.githubusercontent.com/32024686/116130688-2370dd00-a691-11eb-907d-bdf1c11df56b.png)

Grafana version:  Grafana v7.5.1 (4dffb875cf)
Plugin version:  agenty-flowcharting-panel @ 0.9.0

Please suggest on what I can do to fix this problem. 

Thanks,
Murali K

**Comment by algenty** [comment]
Hi,
This bug was fixed in beta version.
Try it in download section

**Comment by muralikanagala** [comment]
Thank you @algenty. Upgrade to the beta version fixed it.

**Comment by muralikanagala** [comment]
Issue is fixed after upgrading to the latest beta version.
