### ISSUE TITLE
the error is occuring after installing the flowcharting plugin , just after selecting it from visualisation,the version is 0.9.0

### ISSUE THREAD

**Issue by developer-sachidanand** [algenty/grafana-flowcharting#295]
![Screenshot from 2021-05-14 12-00-06](https://user-images.githubusercontent.com/74866315/118231028-26026d80-b4ac-11eb-89db-567bb0245bcf.png)

**Comment by algenty** [comment]
Try beta in download section

**Comment by developer-sachidanand** [comment]
The issue is resolved Thank you
