### ISSUE TITLE
draw.io - hyperlink open in the same window

### ISSUE THREAD

**Issue by chrispatin** [algenty/grafana-flowcharting#3]
A hyperlink in a draw.io diagram can link to other dashboard. However it always opens in a new window, rather than the same window. Any suggestions?

draw.io does hyperlinks which link to pages within the diagram. However the flowcharting plugin only appears to support one page.

**Comment by algenty** [comment]
Hi chrispatin
Link wil be implemented in 0.3 or 0.4, wait a little,
its on my personal time, i develop it.

**Comment by chrispatin** [comment]
Sounds great.
