### ISSUE TITLE
Zoom, Scale Issues

### ISSUE THREAD

**Issue by Seana36** [algenty/grafana-flowcharting#30]
I am working with a very large flow chart, 6000 down x 750 wide. When using the zoom feature it is cutting off part of the diagram when I display it. When I use the scale option is is extremely small even when I change the iFrame size to match the diagram it is still not filling the space and stays very tiny. This has made it very hard to view large flow charts. I have also changed the size of the page in the xml to match the large flow chart size, but still am not able to view whole chart correctly. 

This is part of the xml: <mxGraphModel dx="1073" dy="521" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="750" pageHeight="6000" math="0" shadow="0">

**Comment by algenty** [comment]
Hi Seana36,
I'll try to add zoom with button or mouse wheel for next versoin.
it could satisfy your need ?

BR
Arnaud

**Comment by Seana36** [comment]
Hi Arnaud, yes actually that would be great. Thanks!

**Comment by algenty** [comment]
Hi Emily,
Try last version, first version with zoom 
https://algenty.github.io/flowcharting-repository/CHANGELOG.html
![zoom_ani](https://user-images.githubusercontent.com/47012725/62025147-9658d580-b1d7-11e9-9457-1676f559c416.gif)

**Comment by Seana36** [comment]
I have installed the latest version of the plugin. I can see that the right click to drag is working fine. For the zoom, when holding down control and using the mouse wheel in Chrome the browser zoom in/out is taking over, even when making sure to have clicked inside the panel. Is there any specific setting I need to be using?

**Comment by algenty** [comment]
no, just use ctrl + mousewheel on panel and esc to restore

**Comment by Seana36** [comment]
Looks like i was still using version 0.3.0, once 0.4.0 is available for download I will test out the zoom. Thanks.
