### ISSUE TITLE
Some of the shapes in draw.io not visualized well in grafana

### ISSUE THREAD

**Issue by snirgu** [algenty/grafana-flowcharting#31]
why some of the shapes used in draw.io not visualized well on grafana using this plugin .. 
for example cisco shapes shown as blue rectangular wile fortigate shapes showing well.

my grafana version is 5.3.2 and grafana-flowcharting plugin version is 0.3.0 .

thanks
![Uploading Untitled.png…]()
![Uploading Capture1.PNG…]()

as i continue invastigate   , the issue seems to be related to the style of the shape ..  but i;m not sure

**Comment by algenty** [comment]
Hi snirgu
Thx for your feedback
Only version 0.4.0 includes all shapes. its not released, perhaps in september
Try it on https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BR
Arnaud
