### ISSUE TITLE
Issues with Arrows (draw.io)

### ISSUE THREAD

**Issue by dj1301215** [algenty/grafana-flowcharting#315]
Hi GitHub,
I've been using this Flowcharting tool as part of a work project to design an overview monitoring system - nice work btw, reading in draw.io documents is a stroke of genius! - However, I am having problems getting any arrows to change colour. I have the correct metric and thresholds set up, the issue appears to be in the 'Color/Tooltip Mappings'. The documentation says that I should change the 'Shape Stroke/Border' property but this has no effect.  The code defining this line is:
`edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=0.5;exitY=0;exitDx=0;exitDy=0;entryX=0.5;entryY=1;entryDx=0;entryDy=0;strokeWidth=3;strokeColor=#000000;comic=0;fillColor=#FFFFFF;`
I assume from the entries 'strokeWidth' and 'strokeColor' that this is, indeed, the correct property. Maybe it's just buggy?

I have this same issue using a filled and a non-filled arrow (Arrow and Directional Connector respectively in draw.io). With the filled arrow I can neither change the 'Shape Stroke/Border' nor the 'Shape Fill' property. I can set the 'Shape Fill' property of other shapes though... The issue occurs on Chrome, Firefox and Opera so I don't think it is OS dependent.

I'm not sure where to go from here, I was hoping there would be a way to programmatically set the colour but I guess that's not implemented/implementable . Any help would be greatly appreciated. 
Thanks in advance

P.S. Some are also asking me if we can set the order of arrows (front to back etc). I haven't found any parameter setting for this yet; is this even possible?

**Comment by bijwaard** [comment]
Hi dj1301215,
For me Shape Stroke/Border indeed works for changing colors on regular lines, just tried all different styles on a line (grafana 8.1.4, flowcharting 1.0.0b). The style of my line is `endArrow=none;html=1;strokeWidth=3;exitX=1;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=0;gradientColor=#ea6b66;fillColor=#f8cecc;strokeColor=#b85450;`. The shape fill option only seems to work on 2D objects like circles/rectangles, etc.
The order background/foreground order can be set in draw.io using Arange / "To Front" and "To Back", don't think the ordering of is changeable from flowcharting rules yet.
Kind regards,
Dennis

**Comment by dj1301215** [comment]
I do not have the same luck. 
![image](https://user-images.githubusercontent.com/91051056/134148911-fbb5a0cd-0e6e-454a-94d4-d9e088eab1e5.png)
As you can see, the raw value should turn the line on the right red.
Here is me line style:
`endArrow=none;html=1;strokeWidth=3;exitX=0.5;exitY=0;exitDx=0;exitDy=0;gradientColor=#ea6b66;fillColor=#f8cecc;strokeColor=#CCCCCC;endFill=0;` Which I copied and pasted from your example.

How do I find my Flowcharting/Grafana versions?

**Comment by bijwaard** [comment]
You may be using an older flowcharting version as me, I'm using the newest snapshot.
You can see the flowcharting version by going to grafana configuration / plugins / flowcharting, the version will be on the right, as in my example below. The 1.0.0b snapshot can be [downloaded as a zipfile](https://algenty.github.io/flowcharting-repository/ARCHIVES.html) and installed in the /var/lib/grafana/plugin folder.
![image](https://user-images.githubusercontent.com/6523124/134150155-c602f7d7-176c-4309-bc53-d2b346bbf845.png)
Kind regards,
Dennis

**Comment by dj1301215** [comment]
Pardon my ignorance, I don't see any menu option for Grafana configuration.
I can see this, which shows I am using Grafana v8.1.0:
![image](https://user-images.githubusercontent.com/91051056/134152691-bef89bb3-96a1-44c7-a033-cbd301ec1b51.png)
But all of these lead me to support pages.

**Comment by bijwaard** [comment]
Please use the configuration gear-wheel button on the left for configuration.
![image](https://user-images.githubusercontent.com/6523124/134153459-2a6a5088-8f2a-4434-ae0f-155ada17cd03.png)

**Comment by dj1301215** [comment]
Unfortunately I don't have a configuration gearwheel...
![image](https://user-images.githubusercontent.com/91051056/134155807-b36599a2-d256-44bc-8fc8-ff2cbe2352fc.png)

**Comment by bijwaard** [comment]
don't know what is up with your grafana 8.1, I have the gearwheel in grafana 7.5.7, 8.0.6, 8.1.4. Are you logged in as admin or guest? You may need more karma to see the configuration.

**Comment by dj1301215** [comment]
I'm not an administrator, just a user. I'm having difficulty finding out who has admin rights for our service, nobody seems to know...

**Comment by bijwaard** [comment]
Only being a regular grafana user may explain the missing gear-wheel, you can easily do a private grafana install [on your own PC.](https://grafana.com/grafana/download?pg=get&plcmt=selfmanaged-box1-cta1) Otherwise, it may also still have the default password. Try e.g. [admin:adamin](https://stackoverflow.com/questions/54039604/what-is-the-default-username-and-password-for-grafana-login-page).

**Comment by dj1301215** [comment]
Flowcharting version is 0.9.1. I assume this version is expected to cause issues?
Unfortunately I don't have permission to uninstall/install new plugins. I suppose I will have to wait for IT to update it.
Thanks for your help, much appreciated. I'll let you know if I still have issues after the next IT update.

**Comment by bijwaard** [comment]
Flowcharting 0.9.1 is the last official release, the 1.0.0b snapshot is a re-release for v1.0.0. A lot has happened since 0.9.1. Not sure when 1.0.0 can be released since the maintainer has not been very responsive the last half year.

**Comment by dj1301215** [comment]
So... does the Shape Stroke/Border property work for the last official release i.e. 0.9.1? If not then can the documentation reflect this caveat?

**Comment by bijwaard** [comment]
This sort of fixes are normally mentioned in the snapshot Changelog, but cannot find a specific fix for changing line colors in the [snapshot changelog](https://algenty.github.io/flowcharting-repository/CHANGELOG.html), it may have been fixed after 0.9.1  together with something else. Only the maintainer can currently change the documentation.

**Comment by dj1301215** [comment]
Sorry to repeat myself but does that mean that the Shape Stroke/Border property doesn't work for lines in 0.9.1? Can anyone confirm this?

**Comment by moseskt** [comment]
Hey guys anyone managed to get it working with Grafana 8.x.x?

**Comment by bijwaard** [comment]
Hi moseskt,
Color change seems to work fine in v1.0.0b that can be installed manually, in the last official release (v0.9.1) it is unfortunately not working.
Kind regards,
Dennis

**Comment by dj1301215** [comment]
Thanks for the confirmation Dennis. Have a nice day :)
