### ISSUE TITLE
Graph type --- edit

### ISSUE THREAD

**Issue by sumou9723** [algenty/grafana-flowcharting#335]
![d790f208196413d0408855a9da5df28](https://user-images.githubusercontent.com/70930169/166890603-c7a00232-8647-4112-b33a-c56fc242889d.png)

Is it possible to support more forms of diagrams?  For example: pie charts and so on.

**Comment by algenty** [comment]
why not, i ll add it in the roadmap

**Comment by sumou9723** [comment]
dear algenty,



> why not, i ll add it in the roadmap

>dear algenty,Your help was very much appreciated.

**Comment by sumou9723** [comment]
dear algenty,Your help was very much appreciated.

**Comment by sumou9723** [comment]
okok，that‘s all right，thanks algenty.
