### ISSUE TITLE
图无法正常显示

### ISSUE THREAD

**Issue by zhudemiao** [algenty/grafana-flowcharting#338]
1、通过界面plugins增加插件0.9.1无法正常显示示例图，后台日志没有报错
2、通过下载https://github.com/algenty/grafana-flowcharting/tree/master/built下面的agenty-flowcharting-panel-1.0.0d.220509354-SNAPSHOT.zip，unzip后，把目录下dist中的内容复制到安装目录plugins/agenty-flowcharting-panel下面，也尝试master分支下的built目录中“https://github.com/algenty/grafana-flowcharting/blob/master/built/agenty-flowcharting-panel-1.0.0d.220509354-SNAPSHOT.zip”放到plugins下，通过grafana-cli plugins ls 看到已经安装的插件，但是就是无法正常显示。

我的测试版本是8.3.7和8.5.3、8.5.2。
操作步骤：新建面板，选择flowcharting，左侧的示例图片没有显示，偶尔报告“Unable to initialize graph”错误。
但是在6.7.6版本面板，选择flowcharting后，界面上方默认显示示例图片，显示结果正常。

请问，本0.9.1和1.0.0d的插件是否不兼容8.3.7、8.5.3、8.5.2版本，我哪一步没有做对，如果兼容是否需要安装额外的插件？

此外，还有一个细节，就是从draw.io的edit diagram中拷贝出的xml直接粘贴到6.7.6的时候，图片正常显示是修改后的，但是，粘贴到8.3.7、8.5.3、8.5.2，有错误提示：Invalid Xml definition

**Comment by zhudemiao** [comment]
按照文中提示的代码编译过程总是无法通过，以下是编译过程：
yarn install
yarn run build

**Comment by algenty** [comment]
Please write issue in English for a best support
thx

**Comment by ezio2456** [comment]
我也遇见了这个问题，请问解决了吗
