### ISSUE TITLE
Getting XML By URL now working

### ISSUE THREAD

**Issue by Seana36** [algenty/grafana-flowcharting#35]
Thank you so much for all the help so far! I have written a service to return the XML needed to display the graphic and am trying to test it out. I am facing a couple issues, 1) not sure if related to this plugin, but am seeing error "WARN : XML Content not defined undefined" in the chrome console. 2) it is as if nothing is happening on the screen, i can't see the request hit my service so not sure if its making it out of grafana. We are also not seeing any errors in the granfana logs. I have written the service to return of type "xml/plain" and is working fine in postman.

**Comment by algenty** [comment]
Hi @Seana36,
I know, funtion not implemented, i hope it will be in 0.4

**Comment by algenty** [comment]
Duplicate with https://github.com/algenty/grafana-flowcharting/issues/17
I close it
