### ISSUE TITLE
[0.4.0 SNAPSHOT]No object shows in Inspector 

### ISSUE THREAD

**Issue by Sunnor** [algenty/grafana-flowcharting#36]
I downloaded the 0.4.0 from  https://algenty.github.io/flowcharting-repository/ARCHIVES.html unzip it into grafana plugin folder.
I found that inspector can't show the object, but it shows normal in 0.3.0.
![image](https://user-images.githubusercontent.com/49578115/64583236-e7f1a400-d3c2-11e9-8fda-9b292d389397.png)

My grafana version is: 6.2.5

**Comment by algenty** [comment]
Hi Sunnor,
I saw that last week. Since an optimization, inspect not shows all objects.
It show only object targeted in rules, i'll correct it.
Thx for your issue

BR
Arnaud

**Comment by algenty** [comment]
fixed it in 0.4.0

**Comment by Sunnor** [comment]
It works now.

Thank you so much for the great job!!

**Comment by algenty** [comment]
you're welcome. i close ticket
