### ISSUE TITLE
Variable inside link url

### ISSUE THREAD

**Issue by segersrobbertKlarrio** [algenty/grafana-flowcharting#37]
How can we use a Grafana variable inside a link url?
to be able to define url like: https://sub.${VARIABLE}.domain.com

Great plugin! 
Thanks

**Comment by algenty** [comment]
Hi,
Thank you for the compliment :) and your feedback
I take this good idea, i'll try to intregrate it in 0.5.0.
For this week, i'll try to release it.

BR,
Arnaud

**Comment by algenty** [comment]
Hi @segersrobbertKlarrio,
It's already in 0.4.0 but i found a bug, if shape isn't mapping in "Color Mappings" and "Link Mapping",
Flowcharting not add link and replace variable
Fixed in 0.5.0-SNAPSHOT

BR
Arnaud

**Comment by Seana36** [comment]
Hello, Thank you so much for making this update, its exactly what i've been needing! I am trying it out in my local but am seeing some errors within the plugin itself. Any ideas what might be causing it?

![image](https://user-images.githubusercontent.com/11064014/66660625-8a47b600-ec13-11e9-97d3-08bc0099350e.png)
![image](https://user-images.githubusercontent.com/11064014/66660758-c713ad00-ec13-11e9-96f9-9137ac0aa8e5.png)

**Comment by algenty** [comment]
Hi Seana,
Sorry, I didn't see your message.
If you copy/paste the XML in draw.io, its work ?

**Comment by Seana36** [comment]
Yes, if i copy/paste the XML it works fine. I'm seeing in my backend services that it is not replacing the variable, instead it is sending as ${orderNum} instead of the actual value. Is this the correct way to use the variable in the URL?

**Comment by segersrobbertKlarrio** [comment]
usage:
https://algenty.github.io/flowcharting-repository/images/variable_link_ani.png
