### ISSUE TITLE
Invalid XML definition for all xml in self-hosted grafana

### ISSUE THREAD

**Issue by bck01215** [algenty/grafana-flowcharting#373]
My Grafana version is 9.1.2.
My agenty-flowcharting-panel is v0.9.1

In my grafana instance log I can see this error:

> logger=context userId=88 orgId=1 uname=bkauffman7 t=2022-09-15T21:07:10.021656202Z level=error msg="Plugin file not found" error="open /var/lib/grafana/plugins/agenty-flowcharting-panel/module.js.map: no such file or directory" traceID=

I can confirm the file is not there. I'm installing via the GUI, but I have also tried the CLI.

Here is a screenshot from my dev console

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/77836661/190510690-5bf77ada-0bcb-4e30-b350-8ede5ae8990c.png">

**Comment by 6fears7** [comment]
I tested on my local machine with the same versions of both, and was able to load the default XML. I then put it behind my institution's proxy and still did not encounter any errors. My console did not show that GF ERROR.

**Comment by bck01215** [comment]
Issue seemed to resolve after install and uninstalling another broken plugin. Not sure why or what happened.
