### ISSUE TITLE
 NEW 0.4.0 SNAPSHOT candidate for release : BETA USERS NEEDED

### ISSUE THREAD

**Issue by algenty** [algenty/grafana-flowcharting#38]
Hi Users and grafana team.  
Since 4 months, i work on version 0.4.0.
I think this version is stable but before to pull for release, i need feedback and beta tester.
You can found it at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

Documentation at
https://algenty.github.io/flowcharting-repository/

What's news for this version : 
### Added

* Draw.io editor ([Example](https://algenty.github.io/flowcharting-repository/images/openEditor_ani.gif))
  * Open draw.io with dark theme for better rendering
  * Display waiting screen when loading xml definition.
* Upgrading libraries
  * mxGraph 4.0.4
  * draw.io 11.2.8
* Graph definition
  * Adding download function to download source by http on load. ([Example](https://algenty.github.io/flowcharting-repository/images/download_ani.gif))
* Metric
  * Adding string support for state
* Zoom [(issue #19)](https://github.com/algenty/grafana-flowcharting/issues/19) ([Example](https://algenty.github.io/flowcharting-repository/images/zoom2_ani.gif))
  * On the mouse pointer : Ctrl + Mouse
  * Hold right button to move diagram.
  * double click on shape to zoom on.
  * Escape key to restore.
* Tooltip/popup support ([Example](https://algenty.github.io/flowcharting-repository/images/tooltip2_ani.gif))
  * Grafana style css and date
  * Adding metrics with color according levels
  * Adding colors on metrics in tooltip
  * Adding date of change
  * Adding label input for metric
* Variables/templates support, accept variable like ${} ([Example](https://algenty.github.io/flowcharting-repository/images/variable_ani.gif))
  * In xml definition
  * In text mapping when type in sring for "Range to text" and "Value to text"
  * In link ovewrite
* full shapes from draw.io included ([Examples](https://algenty.github.io/flowcharting-repository/images/shapes_ani.gif))
* Some optimizations

### Fixed

* Optimization when refresh/render [(issue #15)](https://github.com/algenty/grafana-flowcharting/issues/15)
* No decimal fixed when 0 [(issue #23)](https://github.com/algenty/grafana-flowcharting/issues/23)
* Text substring and color [(issues #29)](https://github.com/algenty/grafana-flowcharting/issues/29)

BR
Arnaud

**Comment by bijwaard** [comment]
Hi Arnoud,

I started testing your 0.40-September version. The zooming improved a lot, in firefox the mouse-zoom still removes the graphical icons as I reported in #19. In both firefox&chromium the zoom level resets once grafana reloads data, would be great if the zoom level can stay fixed longer than the refresh rate or independently.

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi Dennis,
i work on it but not in this version, because i ll try to release it in few days

**Comment by bijwaard** [comment]
Hi Arnoud,
No problem to wait for next version, it is not that critical.

**Comment by algenty** [comment]
Pull request at Grafana in progress
https://github.com/grafana/grafana-plugin-repository/pull/486

**Comment by PikaYellow35** [comment]
Hi, Arnaud.

I'm testing 0.4.0 snapshot and seeing that rule order not saving on save action. It's viewing like this

* Rule A
* Rule B
* Rule C

After save and refresh page.

* Rule A
* Rule C
* Rule B

Wrong order is preserved when the page is updated without changes. I'm not see sorting logic. 

Also i seeing color selector bug in rule colors. Sometime selected color not applying. I'm tryed select color from predefined, select color in custom tab and insert color string in custom tab in #000000 and rgba() formats. After save the previously selected color applying to rule, but new attempt color changing not work.

Grafana 6.3.5

**Comment by algenty** [comment]
Hi @PikaYellow35,
Thanks for your feedback, 
can you create an issue for this ?
I'll check it this bug asap
BR,
Arnaud

**Comment by algenty** [comment]
Ok, i can repeat the bug.
For the order, that seems easy but for the color it's looks a bug of grafana

**Comment by PikaYellow35** [comment]
Hi, Arnaud.
Sorry for long answer and thanks for quick reaction. =)

Yes, color picker bug seems more as Grafana bug. I will check his work in other panels and will say more precisely.

**Comment by algenty** [comment]
Fixed in 0.4.0 just in time before release
0.4.0 are available on grafana.com
