### ISSUE TITLE
Feature Request: Additional Thresholds (>3 colors)

### ISSUE THREAD

**Issue by herb337** [algenty/grafana-flowcharting#39]
#39

Hi algenty, thanks for making this Grafana Plugin. It is working to great affects. I do have a request, is it possible to add additional thresholds & colors. As of right now, the plugin is limited to 3 colors.

**Comment by algenty** [comment]
Hi, 
Thx for your feedback.
It's already in roadmap "Gradien Mode for color", maybe in next version.
At this time, only 3 colors for each state (OK, WARN and ERROR)

BR
Arnaud

**Comment by xkilian** [comment]
I also like this feature very much, as it can provide the coloring for bandwidth/capacity usage of a physical or logical ressource. Which is not the same as state coloring. Will definitely test this when available.

**Comment by algenty** [comment]
planified in 0.6.0

**Comment by algenty** [comment]
implemented in 0.7.0

![](https://raw.githubusercontent.com/algenty/flowcharting-repository/master/images/multicolor_ani.png)
