### ISSUE TITLE
Flowchart not working anymore with Grafa version 9..4.7

### ISSUE THREAD

**Issue by github-ps1304** [algenty/grafana-flowcharting#398]
atfer updating to Grafana 9.4.7 the plugin isnt working anymore:
reproduce the issue - open a Dashboard with a flowchart panel - edit your flowchart with draw.io - in my case replace a picture - save the draw.io xml - you will see a blank screen.

**Comment by github-ps1304** [comment]
problem described in #397

**Comment by guliangsi** [comment]
Hello,

We also reproduce the same problem in Grafana 7.5.17, since this morning.
As a workaround, it seems that removing the mxfile and diagram (added when we save the diagram in draw.io window) xml tags in the Source Content (at the begining and at the end) allows the graph to be displayed

**Comment by pauljones0** [comment]
I had the same problem this morning, but this workaround fixed the problem.
Thanks @guliangsi :)

**Comment by github-ps1304** [comment]
can you post an example file - what you did remove?
