### ISSUE TITLE
Mapping Tab

### ISSUE THREAD

**Issue by QualityAgileFlow** [algenty/grafana-flowcharting#4]
Hi,

can you give me short hint how the "Mapping" tab works? Or do you have an example? I see the screenshot but I don't understand how to use it ;-)

Thank you

**Comment by algenty** [comment]
Off course
I've added rounded rectangle on your example and 3 texts (value 1, value2 and Value3).
Can i add this animated in docs for next release ? 
Open image on tab or full screen to see detail.
PS : Sorry for my powerless english

![mapping_subway](https://user-images.githubusercontent.com/47012725/55474490-93771b00-5611-11e9-9a42-92d6d262f3c3.png)

**Comment by QualityAgileFlow** [comment]
Thank you very much, now i understand :-)
Sure, use it for your documentation.
