### ISSUE TITLE
Number of query limitation 

### ISSUE THREAD

**Issue by yassinemaadid** [algenty/grafana-flowcharting#40]
Hi , 

I'm using Grafana 6.2.5  with agenty-flowcharting-panel @ 0.4.0 , I have a limitation in number of query that i can create , every new request assign a letter between A and Z , after Z the system dont assign any letter.

Is it a known limitation or a bug ?

Thanks  in advance

**Comment by algenty** [comment]
Hi Yassine, 
it is a limitation in grafana, not in the plugin.
Try to redure query with group by tag or like it ;
on influxdb : select host, value from /.*/ group by host.
Flowcharting can list all tags

BR
Arnaud

**Comment by yassinemaadid** [comment]
Hi Arnaud , 

Thanks you for your help .
