### ISSUE TITLE
Feature Request: Use an internal drawio website

### ISSUE THREAD

**Issue by fredbcode** [algenty/grafana-flowcharting#43]
Hello,

I'm using an internal drawio website, with flowcharting 4.0 I switched some links in code to my internal domain, of course there are a lot of changes in 5.0 and I need to find and change the new entries

I think a global variable or a parameter for this could be helpful (at least for me :))  

Thanks for your works !

**Comment by algenty** [comment]
Hi fredCode
I had the same idea. In my enterprise, i have a internal draw.io.
The change is easy to code. I add it in roadmap

BR

**Comment by fredbcode** [comment]
Thanks ! Great

**Comment by fredbcode** [comment]
Tell me if I can help for testing 

You can contact me directly if needed (I'm french too)

**Comment by algenty** [comment]
I see but even if my English is bad, I have to write in this language.
On the other hand, I'm looking for contributors for the doc, if you're interested.

Try last 0.5.0 and get me your feedback
![image](https://user-images.githubusercontent.com/47012725/66005401-9d3be700-e4ab-11e9-8666-fb4f51689a51.png)

BR
Arnaud
