### ISSUE TITLE
background color to transparant after selecting variable

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#44]
Hi Arnoud,
I just changed selection of a variable in the top of grafana (which is not changing any flowcharting metric), and now the flowcharting panel background went transparant. When I look at the background color in the flowcharting settings it is still set to my custom blue, see figure, but as seen in top of figure, the flowchart has transparent background (probably black because of my grafana layout style). When I reload the webpage in firefox, the color comes back. When I dive into the color setting, the right custom color is still selected

This is with the agenty-flowcharting-panel-0.4.0 from September, as well as the 0.40 release.

Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/65914210-54176480-e3d1-11e9-85cb-9f3b3f30d4f1.png)

**Comment by algenty** [comment]
Fixed in 0.5.0 06-10-2019

**Comment by bijwaard** [comment]
This appears to work, thanks for the fix!
