### ISSUE TITLE
no metrics tab or flowcharting menu

### ISSUE THREAD

**Issue by cappelaere** [algenty/grafana-flowcharting#46]
I am using Grafana 6.3.2 and flowcharting 0.4.0 on OSX using Chrome and Safari.
The FlowCharting menu bar does not show up and there is no metrics tab.
Am I doing something wrong?
Thanks,
Pat.

![Screen Shot 2019-10-02 at 1 11 24 PM](https://user-images.githubusercontent.com/7567/66066007-a7df9600-e516-11e9-8448-e853166b3abe.png)

**Comment by algenty** [comment]
In grafana 6, metrics are on the first icon on the left

**Comment by cappelaere** [comment]
First icon on the left is to define queries.  
In my case, I have a link table and want to display a link value

SELECT value from links where link_id=1

I do not seem to be able to set an alias.

I then thought about using variables defined on the particular dashboard.  I do see them at the top of the widget but when I try to do the mapping, nothing changes.

It would be nice to have a simple example using latest grafana.
I do appreciate the work you put into this.

Pat.

**Comment by algenty** [comment]
what is your db ? influx ? mysql ?

**Comment by cappelaere** [comment]
I use Postgresql.
SELECT link_value from links where link_id=1  works

If I use  the query editor, I do not seem to be able to name it and in the mapping rule, I do not have a way to refer to one of the queries (named A,B,…)

If I use variables, how do I refer to them in the mapping rules?
If it is a text element, I can change the XML directly using ${var} in the text property… but then I cannot recolor a line which requires a mapping rule.

Thanks,
Pat.

**Comment by algenty** [comment]
if your db is a time series, you must found the alias in "metric name"

**Comment by cappelaere** [comment]
Arnaud,

What does that mean?

If I define a query using the query icon (grafana 6.4.1), I only see a Metric column entry but I am constraint to use a real column name.  This is not what I want as I am interested in defining queries that return a single element or row.
And I would like to use the values and map them onto the diagram.

Using variables associated with a particular dashboard would be nice.
I can define a variable like LINK1_VALUE (and I see a value at the top of panel of 1)
I tried to map LINK1_VALUE and ${LINK1_VALUE} to one of the diagram element but it does not seem to be working.  Should it?

Thanks,

Pat.

Arnaud is French name.  Are you French?

**Comment by cappelaere** [comment]
I figured it out.  I had to quote the metric string in the query.
Vive la france.

**Comment by algenty** [comment]
Your request can return several lines but only one value (column), use group by to use more tags.

**Comment by mridude23** [comment]
@cappelaere Hi there, did you manage to do something like a count of rows based on clauses? And then map that metric to some text for eg?

I'm trying to count all alerts from a table based on 2 where clauses and then to map that value to a text on my flowchart. DId you manage to do something like this?
I cannot seem to make it show under Apply to metrics name: in Rule tab of Visualization.

If anyone can point me to anything it would be appreciated.

**Comment by algenty** [comment]
Hi,
Can you try experimental version at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html
