### ISSUE TITLE
Overwrite link is inactive 

### ISSUE THREAD

**Issue by fredbcode** [algenty/grafana-flowcharting#47]
Hello,

I'm using 0.5.0_3_fix_bug_draw.io_editor branch, "Object as link" seems without any effect 

"Object as link" is enabled
"Overwrite" is on Warning/Critical
Url box with a different url

When the state switch to critical the link still the same  

Thanks

**Comment by algenty** [comment]
Hi fred,
I advise you not to use a branch other than master, they are not stable.
Please prefer to download snapshot in download section in documentation.

One Rule = One metric
Define threshold like 50,80 if metric is number, that's mean 
0-50 = OK
50-80 = WARNING
>80 = ERROR
Or invert
If it is a string, select string in type and add "value mapping", exemple from http code
200 to 299 = OK
400 to 599 = "KO"
In Warning input, keep empty 
In Error input, enter "KO"

In Color Mapping, choose shapes you want to color
In Text Mapping, choose shapes you want to display value
In link Mapping , choose shapes you want to link according the rules

You can choose different shapes for color, text or link

> When the state switch to critical the link still the same

have you selected shape in Link Mapping ? 

BR Arnaud

**Comment by fredbcode** [comment]
Ok I missed Link Mapping below :)

Thanks

**Comment by algenty** [comment]
Imagine a rule for it, with flowcharting, you can
![image](https://user-images.githubusercontent.com/47012725/66140808-097d2e80-e603-11e9-978f-792a31d14cf7.png)

dont close ticket plz

**Comment by fredbcode** [comment]
Ok very interesting, I have a question sorry but not directly related 

There is way to related rules ? Eg: I have a central firewall down so the others objects should be also down (but I check by an admin network) or a database down connected to a specific http server but it still answer a 200 code

**Comment by fredbcode** [comment]
A rule can change the status for others ?

**Comment by fredbcode** [comment]
Perhaps I'm unclear, I mean we can change the color from another object, but there is no message about which services (if many) make your object critical 

A and B switch to red and C is also red, from user point of view A or B can be the point, but this may not necessarily be true, just one can be only configured to change C the reader can't knows

**Comment by algenty** [comment]
If the form is present in several rules, it will always take the rule with the highest level.
If level is the same, the last rule will always overwrite the previous one, that's why you can change the order of the rules. See get started for examples

**Comment by algenty** [comment]
And don't forget to star project if you like it :)
