### ISSUE TITLE
Multiple FlowCharts On a Dashboard

### ISSUE THREAD

**Issue by Gyetko** [algenty/grafana-flowcharting#48]
When creating and saving multiple FlowCharts on a Dashboard, sometimes on the first time of saving, both Flowcharts show the same content.  Valid in Version 0.3.0 and 0.4.0

To reproduce:
1. Add a panel to a dashboard, configure it to be a Flowchart, open the draw io editor clean everything out, and add a component, give it some text like "Hello" and save.  So far so good.
2. Add a second panel to the same dashboard, configure it to be a Flowchart, open the draw io editor clean everything out, and add a component, give it some text like "World" and save.  
3. Sometimes when saving the second instance for the first time, both instances of the FlowCharting component will have one component and both say "World".  So it looks like your serializer back to JSON has problems sometimes when saving back to find the proper instance of the FlowCharting component.  So what I do to work around this is to copy the json XML config for the first instance to my clipboard or external editor, then create the second one.  If the problem happens, then I paste the Json xml back into the dashboard json for the first instance and things work fine.  After that, editing either one works fine for ever more.  Interesting bug.  :) Hope you fix this one.  :)

**Comment by algenty** [comment]
yes Interesting bug. I'll try it ;)

**Comment by algenty** [comment]
Fixed in 0.5.0 SNAPSHOT
