### ISSUE TITLE
Tooltips and URL Linking Don't Both Work at the Same Time

### ISSUE THREAD

**Issue by Gyetko** [algenty/grafana-flowcharting#49]
Version 0.4.0
If you take a component and add a URL Link click through things work fine.
If you take a second component and add tooltip text from the draw io editor it renders fine.
However if you take a 3rd component and add a URL click through link and a tooltip they both don't work.  I was wondering if I am doing something wrong.
It seems to me I had to make a lower Z level component do the click through URL and place another component on top that is smaller for the tooltip.  

What is the recommended way to have one component that supports URL click through and tooltips?

**Comment by algenty** [comment]
Hi @Gyetko
 
This bug is known and fixed in the version 0.5.0 SNAPSHOT not let published
Can you try it at

https://algenty.github.io/flowcharting-repository/ARCHIVES.html


BR,
Arnaud
