### ISSUE TITLE
Feature Request: Support for Tooltips

### ISSUE THREAD

**Issue by bhozar** [algenty/grafana-flowcharting#5]
Draw.io allows tooltips to be added to shapes. Would be helpful to have these display when I hover over in Grafana please?

If tooltips are included in the .XML at the moment it breaks the graphic as I have it updating a value by replacing the word VALUE in the Text Pattern box. Including the tooltip changes it to replace all content.

**Comment by algenty** [comment]
Hi bhozar,
thx to use flowcharting and your back
its on roadmap, in version 0.5 or 0.6.

Best reguards
Arnaud

**Comment by algenty** [comment]
its for you
https://twitter.com/gf_flowcharting/status/1126591892173594627
comming in 0.4 in one month or early in snapshot version

**Comment by bhozar** [comment]
Nice! That looks brilliant, thanks!

**Comment by algenty** [comment]
Hi,
0.4.0 is available in SNASHOT version with tooltip
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BG
Arnaud
