### ISSUE TITLE
feature: map metric to draw.io placeholder

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#50]
Hi Arnaud,
Would it be possible to map a map a metric to a draw.io [placeholder](https://desk.draw.io/support/solutions/articles/16000051979)?
This would enable displaying multiple metrics within one label like "%metric1%, %metric2%, %metric3%" on a draw.io object, and would make it easier to reuse these placeholders in different objects.
Kind regards,
Dennis

**Comment by bijwaard** [comment]
Since I'm heavily using draw.io placeholders in my DSP  flow (see #67), I only see the placeholders themselves in the inspector, I would really like to see the referenced attributes like draw.io and the tooltips do.
![image](https://user-images.githubusercontent.com/6523124/68067934-bf48b380-fd4e-11e9-83f2-d5f39659a52a.png)

**Comment by bijwaard** [comment]
Hi Arnaud,

Since the snapshot 0.6.0-24/11, I start seeing placeholders within the flowchart, this is not so pretty. I guess there is a function in draw.io to expand the placeholders within the label before appending the metric value(s).

I.e. with mapping rule for RMS as below, I see the following in the flowchart, and the following in draw.io:
![image](https://user-images.githubusercontent.com/6523124/69616156-665ef900-1036-11ea-9a7f-e3dabc128178.png)
![image](https://user-images.githubusercontent.com/6523124/69615915-fcdeea80-1035-11ea-943c-e9c0507eb5ae.png)
![image](https://user-images.githubusercontent.com/6523124/69616585-29473680-1037-11ea-8a48-cc9f00c6db9d.png)

**Comment by bijwaard** [comment]
Hi Arnaud,
I think using placeholders can make updating labels easier for you. I guess you now need to search regularly (every update?) within the labels to change/append it with the measurements.
With a placeholder, the flowcharting panel can just add %metrics% in the label at the desired place when the rule is initialized/updated and then the panel only needs to update the metrics attribute when update measurements arrive. Adding individual 

I.e. in pseudo-code:

When rule is changed/initialized:

- depending on display rule
  - when replacing all content: change label to %metrics%
  - else find content part of label
    - when replacing substring: change content to %metrics%
    - when appending with space or newline: append %metrics% to content

When updated metrics become available:

- update metrics attribute:
  - when replacing substring/all or appending with space: setAttribute("metrics","metric1 metric2 metric3 ...")
  - when appending with comma: setAttribute("metrics","metric1,metric2,metric3, ...")
  - when appending with newline: setAttribute("metrics","metric1\nmetric2\nmetric3\n...")

Once the attribute changes, the draw.io library should take care of updating the placeholder(s) in the label, like it did before version 0.6.0 snapshot of 24/11.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Hi Arnaud,

I was able to fix the placeholder not showing by disabling model.setValue a line in the setLabel function:

```
  setLabelCell(mxcell: mxCell, text: string): string {
    let label: string = text;
    if (mxUtils.isNode(mxcell.value)) {
      label = mxcell.value.setAttribute('label', text);
    } else {
      mxcell.setValue(text);
    }
    //this.graph.model.setValue(mxcell, text); // DISABLED
    return label;
  }
```

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Just experimented in draw.io with using placeholders on a line, and when I do this, the line gets embedded into an object with the placeholder in the label:
```
    <object label="%name%" name="my line" placeholders="1" id="s8bRC8wg6MaYrf834KEh-3">
      <mxCell style="endArrow=classic;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;" edge="1" parent="1" source="s8bRC8wg6MaYrf834KEh-1" target="s8bRC8wg6MaYrf834KEh-2">
        <mxGeometry width="50" height="50" relative="1" as="geometry">
          <mxPoint x="20" y="170" as="sourcePoint"/>
          <mxPoint x="70" y="120" as="targetPoint"/>
        </mxGeometry>
      </mxCell>
    </object>
```

**Comment by bijwaard** [comment]
I found the API for [mxCell.isNode()](https://jgraph.github.io/mxgraph/docs/js-api/files/model/mxCell-js.html) and it seems to conflict a bit for the label/value on simple lines. I guess the isLabel() and setLabelCell() functions could be rewritten as below. I changed this in: /var/lib/grafana/plugins/grafana-flowcharting/dist/module.js and restarted grafana, and it appears to work for my flowcharting panels that have both labels on lines and objects.

```
/**
   * Return Label/value of mxcell
   *
   * @param {mxCell} mxcell - mxcell or object containing an mxcell
   * @returns {string} Label of current cell
   * @memberof XGraph
   */
  getLabel(mxcell: mxCell): string {
    if (mxUtils.isNode(mxcell.value)) { // mxcell has inner value cell and label when it is an object
      return mxcell.getAttribute('label');
    } else {
      return mxcell.getAttribute("value"); // this is probably a simple mxCell like a line, that has value attribute
    }
  }

/**
   * Assign new label for mxcell
   *
   * @param {mxCell} mxcell - mxcell or object containing mxcell
   * @param {string} text - New label
   * @returns {string} New label
   * @memberof XGraph
   */
  setLabelCell(mxcell: mxCell, text: string): string {
    let label: string = text;
    if (mxUtils.isNode(mxcell.value)) {
      label = mxcell.setAttribute('label', text); // mxcell has inner value cell and label when it is an object
    } else {
      label = mxcell.setAttribute("value",text); // this is probably a simple mxCell like a line, that has value attribute
    }
    return label;
  }
```

**Comment by bijwaard** [comment]
Hi Arnaud,
Note that (aside of disabling your model.setValue) I changed mxcell.**value**.setAttribute('label',text) to mxcell.setAttribute('label',text), and similar in getLabel.
Kind regards,
Dennis

**Comment by algenty** [comment]
Hi, 
I've tested, and if  this.graph.model.setValue(mxcell, text); is  disabled.
Some mxCell isn't updated, i can't generate this update.
Can you give an XML example with placeholder ?

BR,
Arnaud

**Comment by algenty** [comment]
If i understand the API doc, setLabelcell should be written like the.
Be carefull, i don't use native mxgraph libs, drawio libs changes many functions in mxgraph.

setLabelCell(mxcell: mxCell, text: string): string {
    let label: string = text;
    this.graph.cellLabelChanged(mxcell, text, false);
    return label;
}
It seems to  work in my examples, can you try in your model with placeholder ?

BR
Arnaud

**Comment by bijwaard** [comment]
This is the Error I see in console for the ':' in the let statement. When I remove ": string", it seems to correctly update the placeholders.

Error loading panel plugin: agenty-flowcharting-panel Error: "unexpected token: ':'
  Instantiating https://dashboard.smartstatetechnology.nl/public/plugins/agenty-flowcharting-panel/module.js
  Loading plugins/agenty-flowcharting-panel/module"
    st system.js:4
    yt system.js:4
keybindingSrv.ts:20:2

**Comment by algenty** [comment]
i'll build a zip and i'll put it here

**Comment by algenty** [comment]
[agenty-flowcharting-panel-0.6.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/3969026/agenty-flowcharting-panel-0.6.0-SNAPSHOT.zip)

**Comment by algenty** [comment]
With this modification, placehorder seems work fine :)

**Comment by bijwaard** [comment]
Hi Arnaud,
I can confirm that the placeholder show and update fine with your fix.
The issue with the string typing is probably because I edited "grafana-flowcharting/dist/module.js", in which the typescript types are apparently stripped off to look more like javascript that the browser understands.
Kind regards,
Dennis

**Comment by algenty** [comment]
Yeah, good news,
thx for your feeback and your help

**Comment by bijwaard** [comment]
Hi Arnaud,

I'm pleased to help, it helps me forwards as well;-)

The inspector still shows the non-evaluated placeholders though. There is hopefully some way to expand them and get rid of the styles.

Kind regards,
Dennis

![image](https://user-images.githubusercontent.com/6523124/70945717-18964900-2056-11ea-9bf7-e8755d8bd044.png)
