### ISSUE TITLE
Some BPMN symbols not correctly shown

### ISSUE THREAD

**Issue by anthraxn8b** [algenty/grafana-flowcharting#51]
1st of all: GREAT TOOL!

My Problem: Using BPMN leads to charts in Grafana where some symbols (for now I know "start", "cancel" and "teminate" are shown correctly in draw.io but grafana just shows rectancle boxes.

DRAW.IO:
![image](https://user-images.githubusercontent.com/7797912/66375491-d2fe3580-e9ad-11e9-9e7d-06407fb85a5e.png)

GRAFANA:
![image](https://user-images.githubusercontent.com/7797912/66375444-b104b300-e9ad-11e9-8ed4-deeb5bddde0e.png)

Used Versions:
Grafana: 6.1.1
Grafana-Plugin: 0.4.0

**Comment by anthraxn8b** [comment]
Now the only thing I get displayed is a circle... Plugin is unusable.

**Comment by algenty** [comment]
can you give me you xml definition ?

**Comment by algenty** [comment]
I opened an issue for draw.io team.
https://github.com/jgraph/drawio/issues/588

I'll fix it for next snapshot

br,
Arnaud

**Comment by algenty** [comment]
Snapshot published 
Can you test it please ?

**Comment by anthraxn8b** [comment]
Yeha! Seems to work! Thank you for your fast reaction AND solution!
