### ISSUE TITLE
Build with @grafana/toolkit

### ISSUE THREAD

**Issue by ryantxu** [algenty/grafana-flowcharting#52]
@algenty this plugin is looking really great.  Do you have any interest in converting it to use https://www.npmjs.com/package/@grafana/toolkit for the build?

I can help with that transition, and then we can support better cross version testing

**Comment by algenty** [comment]
Hi @ryantxu,
Thanks a lot :) 
I don't know this tool, is it an official Grafana tool ?
Are you a member of team grafana ?

BR
Arnaud

**Comment by ryantxu** [comment]
> is it an official Grafana tool?

Yes -- the goal is to share as much common tooling so plugins don't have to reinvent the wheel to use best practices.

> Are you a member of team grafana?

Yes -- I joined grafana a few months back... after working with grafana plugins for many years

**Comment by algenty** [comment]
It's a good idea.
i need to convert Flowcharting in react and typescript before. there's a lot of work to do.

**Comment by ryantxu** [comment]
with toolkit, you can incrementally convert to typescript.  Converting the config UI to react will be difficult though!

**Comment by algenty** [comment]
Hi @ryantxu 
Can you issue in grafana project please
https://github.com/grafana/grafana/issues/20148
I'am blocked
