### ISSUE TITLE
Release flowcharting 0.5.0

### ISSUE THREAD

**Issue by fredbcode** [algenty/grafana-flowcharting#53]
Hello,

Do you have an approximate schedule about it ?

Thanks

**Comment by algenty** [comment]
Hi,
I think i push it in one month approximately.
Miss some fix for zoom
i want to add charts feature in tooltip
I'm running out of time.

**Comment by fredbcode** [comment]
Thank you, the v5.0 snapshot is generated from which branch ?
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

I will use this for now, for continuous deployment I'm using git directly but there is no V5.0 branch with all changes

**Comment by algenty** [comment]
Hi Fred,
I create a branch for each feature, not for a version.
Use snapshot in archive to get the latest developments

**Comment by fredbcode** [comment]
Hi, Snapshot is auto generated ?

**Comment by algenty** [comment]
no, it's manually

**Comment by algenty** [comment]
in the issue https://github.com/algenty/grafana-flowcharting/issues/45
Dennis tryes the lastest version, you can also try it
