### ISSUE TITLE
Only one tooltip graph is displayed with multiple metrics in regex

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#54]
Currently when a regex for for a rule matches multiple metrics, only the graph for the last one is displayed when tooltip graph is enabled. It would be great when each metric graph is displayed, the default label could be the metric name when the tooltip label is empty. It could also support regex replacement syntax with grouping, such that e.g. group 1 and 2 in regex /\(.\*\):L\(.\*\)/ could be used in the label as \1:L\2
The "color with state" could then be done for each metric according to the specified threshold.

This would also make the functionality similar to the the display of multi-metric values as text in the chart, where values can be appended with new-line or space. 

Note that the color mapping may also change according to the last metric. The specific metric could be reflected by changing the text background or font color of the specific metric value text instead.

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi
Fix in progress

BR
Arnaud

**Comment by algenty** [comment]
Hi Dennis,
Can you try this experiental version
All test are not finished
[agenty-flowcharting-panel-0.5.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/3731164/agenty-flowcharting-panel-0.5.0-SNAPSHOT.zip)

BR
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud,
Empty label works like a charm (first figure)! Couldn't get tooltips on lines and text boxes yet, and multi-metric labels don't color according to threshold yet, i.e. 5 non-colored CT1 currents on left side of F01 feeder and no tooltip on them, 2nd figure. Not sure what other functionally to test at the moment.
Dennis

![image](https://user-images.githubusercontent.com/6523124/66894432-a9b65880-eff0-11e9-82cf-9e495d9045df.png)
![image](https://user-images.githubusercontent.com/6523124/66894963-036b5280-eff2-11e9-809a-2c213ffad01c.png)

**Comment by algenty** [comment]
yes ! thanks for your feedbacks

**Comment by algenty** [comment]
Hi Dennis,
For color, you need to change Color, or clone rule to change it for line and arrow.
I try tooltip on text and line, i cant reproduce it, it work for me
![tooltip_line](https://user-images.githubusercontent.com/47012725/67028984-a0221300-f10c-11e9-8bc1-103d73209229.gif)
Can you copy/call your objects  who doesn't work in empty draw in draw.io and send me it your xml source ?

BR
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud,
The problem with text appeared to be a configuration issue of the color setting, which was set to a non-existing node (i.e. one that I removed) instead of the same one of the . Once I set it to an the same node as the text label, both color and tooltip worked. Note that choosing append(New line) for Display with bottom marker, starts at the bottom with an empty line (see left side of outgoing feeder F01).
I'll investigate the arrows some more.
Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/67039732-37459580-f122-11e9-8bb7-c33fae5f8a63.png)

**Comment by bijwaard** [comment]
Hi Arnaud,
I could get the tooltip on the arrow working by adding the ID of the line to the color settings, tooltip doesn't show up when color mapping is not configured. I disabled the color settings since I don't want my RED phase one to change color.
Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/67040704-4f1e1900-f124-11e9-8bc6-403516906a39.png)
