### ISSUE TITLE
Shapes

### ISSUE THREAD

**Issue by kotviphp** [algenty/grafana-flowcharting#55]
Hi

why forms Cisco not displayed?
how to fix?

**Comment by kotviphp** [comment]
![ciscoJPG](https://user-images.githubusercontent.com/25497579/66902971-6f19e380-f023-11e9-8cd5-8a59ed207d04.JPG)

**Comment by algenty** [comment]
Hi,
What is your version of Flowcharting ?

**Comment by kotviphp** [comment]
0.3.0
update to 0.4.0, everything is working
thank

**Comment by algenty** [comment]
you'r welcome,
You can try also the next version at
https://algenty.github.io/flowcharting-repository/ARCHIVES.html.
see changelog for fixes and features

PS : don't forget to star projet if you like Flowcharting
