### ISSUE TITLE
Links to object without having to associate a metric to it.

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#56]
Simple use case to add links to objects.

**Comment by algenty** [comment]
You can add a link directly in draw.io

**Comment by xkilian** [comment]
Ah ok, that is clear enough. Pease add that to the documentation when you talk about links. From a least surprising perspective, in Grafana we typically define links in the Grafana UI. There is also the usability component of having the dashboard picker and other facilities to make it easy to manage/update links. Perhaps in flowcharting the feature request would be an easy way to manage object links.

**Comment by algenty** [comment]
I'll add this in doc
