### ISSUE TITLE
Link - Overwrite link on property is not saved

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#57]
When re-opening a dashboard that has a link with overwrite link on property set. The property is empty. Selecting Always from the dropdown list restores it temporarely. Using 5.0 latest snapshot.

**Comment by algenty** [comment]
Hi xkilian,
Thanks for your feedback
I'll try it

**Comment by algenty** [comment]
I can't reproduce it,
Can you try with the lastest snapshot ? or send me a capture ?

BR
Arnaud

**Comment by xkilian** [comment]
I will try the snapshot from the 15th (I do not see a newer one).
I will also get a screenshot when retesting.

**Comment by xkilian** [comment]
Works with the latest snapshot! :-) I will go ahead and close the issue.
On a side note: the main suggestion to improve this feature is to have access to the standard Grafana datalink picker. I think this will be easy when you use the standard grafana-toolkit...
