### ISSUE TITLE
Editing Id names in inspect tab does not consistently save them to XML file.

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#58]
Editing in the inspect tab will often work and changes are applied to the XML. Unfortunately, changes done to the  inspect tab often are not actually applied to the XML definition. So when saving and reopening the dashboard, changes are lost.
Manually editing the XML works for testing purposes. Using Firefox 69 and Grafana 6.0.2.
Keep up the great work!

**Comment by algenty** [comment]
Hi xkilian,
I'll try it

**Comment by xkilian** [comment]
Using the latest snapshort it works with a quick test. But will go through a full creation from scratch to make sure I catch it if it does come up. (And what I did prior to the issue cropping up. Because in the original testing I used two different firefox version and I was swapping between inspect and rule creation. So the exact steps to reproduce are a little hazy.

**Comment by algenty** [comment]
Hi @xkilian 
Can you try the lastest version in download section ?

**Comment by tbaczynski** [comment]
I'm not sure this is exactly this same problem, it was, but in the meantime i upgraded grafana and plugin, and now I have situation, when i do not see 'apply changes' button on Graph Inspect ID. I cannot see any posibility to manage/save new names for objects.
grafana (6.5.2) and plugin (0.6.0).
![image](https://user-images.githubusercontent.com/48806116/71854516-b40f5c80-30de-11ea-87ab-9f2c51368612.png)

**Comment by NURULFARAHINirwanshah** [comment]
> I'm not sure this is exactly this same problem, it was, but in the meantime i upgraded grafana and plugin, and now I have situation, when i do not see 'apply changes' button on Graph Inspect ID. I cannot see any posibility to manage/save new names for objects.
> grafana (6.5.2) and plugin (0.6.0).
> ![image](https://user-images.githubusercontent.com/48806116/71854516-b40f5c80-30de-11ea-87ab-9f2c51368612.png)

Hi, I'm having the same problem here. Have you found the solution?

Regards,
Farah

**Comment by jorlandobr** [comment]
> 
> 
> I'm not sure this is exactly this same problem, it was, but in the meantime i upgraded grafana and plugin, and now I have situation, when i do not see 'apply changes' button on Graph Inspect ID. I cannot see any posibility to manage/save new names for objects.
> grafana (6.5.2) and plugin (0.6.0).
> ![image](https://user-images.githubusercontent.com/48806116/71854516-b40f5c80-30de-11ea-87ab-9f2c51368612.png)

Experiencing the same problem. There is no "Apply Changes" button. 

Grafana v6.4.4(092e514), Flowcharting v0.6.0

**Comment by jorlandobr** [comment]
I removed version 0.6 e manually installed 0.50. The "Apply Changes" button appears after renaming some id.

**Comment by algenty** [comment]
Fixed in 0.6.1.
Release in progress
https://github.com/grafana/grafana-plugin-repository/pull/556
Put a health to speed it up ;)

**Comment by algenty** [comment]
[agenty-flowcharting-panel-0.6.1-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/4109216/agenty-flowcharting-panel-0.6.1-SNAPSHOT.zip)
The preview

**Comment by jorlandobr** [comment]
Just tested!

"Apply Changes" buuton appears after renaming ids.

Saved changes, opened another browser in a different computer and could confirm that the changes were made and saved! :-)
