### ISSUE TITLE
Only one Color Mode can mapping to one Rule.

### ISSUE THREAD

**Issue by kp7050** [algenty/grafana-flowcharting#59]
Hi. Flowchart panel is very useful to me.
I want to Flowcharting Panel is provide "fill & stroke" Color mode
However, just Only one color mode can mapping to one Rule.
For example, I have to make network map that has 100 nodes and 200 lines. we add rules for nodes at least 100. As I mention before, Flowcharting panel only one color mode can mapping to one rule. So, we define rules for lines at least at 200 Additionally. This cause slow loading and unnecessary works.
So, Flowcharting Panel need to providing "fill & stroke" Color mode or mapping various color mode at a  node.
![image](https://user-images.githubusercontent.com/24567259/67069878-7c68d680-f1b9-11e9-93ed-c74d3db1316f.png)
![image](https://user-images.githubusercontent.com/24567259/67070945-4bd66c00-f1bc-11e9-9735-4a758ea9cc01.png)

**Comment by algenty** [comment]
Hi kp7050,
What is your version ? the 0.5.0 est 2 fois plus rapide

**Comment by algenty** [comment]
0.5.0 coming this week, pull request in progress
https://github.com/grafana/grafana-plugin-repository/pull/499

**Comment by algenty** [comment]
Hi,
have you try the last published version 0.5.0 ?
can you see difference for speed ?

BR
Arnaud

**Comment by kp7050** [comment]
Thank you, algenty. 
Definitely version 0.5.0 is so fast. 
However if I made over 70 rules for mapping a hundreds of nodes, it slow again.
(The version 0.4.0 was slow when it mapping over 3~40 rules.)

**Comment by algenty** [comment]
You can reduce rules in 0.7.0 because in one rule, you can select condictions for each shape
Can you try 0.7.0 snapshot in https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by xkilian** [comment]
Wow, I can se you have been a busy bee. Looking forward to using the new version. Multiple object conditions and colours. Hmm.. I can see new network process diagrams in my future! What with all the Covid-19 crazyness, I will have a lot more time to create nice flowcharting dashboards in Grafana!

**Comment by algenty** [comment]
Hi @xkilian 
You can found it at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html
I hope to publish it this week, regression test in progress
Give me a feedback 

BR

**Comment by algenty** [comment]
An example with gradient Mode
![floorplan_gradient_gradient](https://user-images.githubusercontent.com/47012725/77562473-5b22b980-6ec0-11ea-8800-15d2c21f6868.gif)
