### ISSUE TITLE
Add "Total" aggregation for values

### ISSUE THREAD

**Issue by bhozar** [algenty/grafana-flowcharting#6]
Would be helpful to add "Total" to the aggregation options available.

Thanks

**Comment by algenty** [comment]
Hi, bhozar,
offcourse it's implemented, try Sum

**Comment by bhozar** [comment]
Odd, I was getting some different results when using Sum compared with other panels using Total. I'll have another look, thanks.

**Comment by algenty** [comment]
your welcome
