### ISSUE TITLE
Expand and Collapse support?

### ISSUE THREAD

**Issue by paregupt** [algenty/grafana-flowcharting#64]
Hi there

Is the draw.io expand and collapse (via a container) supported? I remember reading somewhere that it was supported but can't make it work. Any help, please?

BTW, Great work!

**Comment by algenty** [comment]
Hi pareGupt,
Happy to see you again.
Yes, expand and collapse work in 0.5.0 if your graph is unlock in flowcharting
![url_download_variable_ani](https://user-images.githubusercontent.com/47012725/67743230-53004400-fa1e-11e9-8f79-50fcfda958c8.gif)

BR
Arnaud

**Comment by algenty** [comment]
in editor, don't forget to arrange container in back otherwise it's diffcult to select shapes in flowcharting

**Comment by paregupt** [comment]
Hi Arnaud

Thanks for the confirmation. It's working now in v0.5.0 after unchecking the Lock button. This is great work and is helping me to represent a complicate design in a simpler way. Thanks again.

**Comment by algenty** [comment]
you're welcome 👍
