### ISSUE TITLE
A null value returned from AWS CloudWatch breaks all queries

### ISSUE THREAD

**Issue by rickbowden** [algenty/grafana-flowcharting#66]
Thank you for this fantastic plug but I'm having an issue with it.

I'm currently attempting to create a dashboard using this plugin but when ever CloudWatch returns a null value all the rest of the queries break.
CloudWatch often returns null values, if for example there is no network traffic into a loadbalancer then no values are recorded in CloudWatch so the return is null.
I found a similar issue here https://github.com/algenty/grafana-flowcharting/issues/65 and tried the 0.6.0 snapshot but the issue is still there for me.

The null value returned from CloudWatch looks like this.
![image](https://user-images.githubusercontent.com/22094101/67841215-7ba43e80-faef-11e9-99ef-cea94f9f5662.png)

This is the error I get.
angular.js:14700 TypeError: Cannot read property '0' of undefined
    at Rule.getValueForSerie (rule_class.js:484)
    at State.setState (state_class.js:121)
    at eval (statesHandler.js:139)
    at Array.forEach (<anonymous>)
    at eval (statesHandler.js:138)
    at Map.forEach (<anonymous>)
    at eval (statesHandler.js:137)
    at Array.forEach (<anonymous>)
    at StateHandler.setStates (statesHandler.js:135)
    at Flowchart.setStates (flowchart_class.js:114)

A valid response where the data returned is not null would look like this.
![image](https://user-images.githubusercontent.com/22094101/67841368-d3db4080-faef-11e9-8fb9-e144e7584662.png)

**Comment by algenty** [comment]
Hi @rickbowden,
Thx for compliment, it's always nice.
Flowcharting is always in beta, i need to add filters and secures in code for this case before release it in 1.0.0. maybe return nothing when serie is empty. i come back to you when i correct it

BR
Arnaud

**Comment by rickbowden** [comment]
Thank you.

**Comment by algenty** [comment]
Can you try the last build ?

**Comment by algenty** [comment]
no answer, i close it
