### ISSUE TITLE
Feature request : change the place of the value on a shape

### ISSUE THREAD

**Issue by cbtsgithub** [algenty/grafana-flowcharting#69]
First of all, i have to say that GF is a marvelous tool for Grafana !!!
I love it.

However i have a feature request: could it be possible to change the place of the value on a shape.
This is usefull when the pictures are small with very few room.

Thanks in advance.
Chris

**Comment by algenty** [comment]
Hi Chris,

First, thanks a lot, it's always a pleasure to read that.
The position of label is defined into draw.io
Go to https://desk.draw.io/support/solutions/articles/16000057962-how-to-position-labels-outside-of-shapes-

BR
Arnaud
