### ISSUE TITLE
Referencing metrics in text mappings

### ISSUE THREAD

**Issue by teunvink** [algenty/grafana-flowcharting#7]
I'm trying to achieve the following:

I have a network map (quite like the examples in the animated gifs) which contain labels. 
I have an influxdb query which does a 'GROUP BY' to gather data for all links in the network map in every direction. Aliases are set using the tags used. So I have a lot of metrics named 'IFDESC1-IN', 'IFDESC2-OUT' etc. In my draw.io map I changed the ID's on the labels to match these names. Now, I would like to replace those labels with the measurements in one go. I can use a regexp to match /.*/ in the "apply to metrics named" field, but when I leave "/.*/ in the "Text Mappings" field all labels get the same value.

I assume that in the "Text Mapping" fields I would like to reference the value in the "apply to metrics field. Is there any way to reference that field value, so that I can use one rule to set each value on the appropriate label?

**Comment by algenty** [comment]
Hi teunvink,
thx to use flowchating and your back.
i make an animated for example, i found a bug thanks to you
![text_replace](https://user-images.githubusercontent.com/47012725/55990418-eb63f080-5ca7-11e9-9cfd-cf38f0a62893.png)

Try this zip
[agenty-flowcharting-panel.zip](https://github.com/algenty/grafana-flowcharting/files/3070443/agenty-flowcharting-panel.zip)

Best reguards
Arnaud

**Comment by algenty** [comment]
i close ticket, open it again it if you have questions
