### ISSUE TITLE
Feature Request : multiple values on the same object

### ISSUE THREAD

**Issue by cbtsgithub** [algenty/grafana-flowcharting#70]
First of all, i have to say that GF is a marvelous tool for Grafana !!!
I love it.

However i have a feature request: could it be possible to have multiple values on the same objetc:
this could be the case of a two-way arrow between 2 routers (Download & upload).
![2019-11-01 20_05_01-Network Map Panel - Grafana](https://user-images.githubusercontent.com/51846991/68049367-fc775c00-fce2-11e9-8f0f-06a162a5f707.png)

Thanks in advance.
Chris

**Comment by algenty** [comment]
Yes you can already with append mode in "update text", maybe the name of this input is not enough explice.
see it :
![append mod](https://algenty.github.io/flowcharting-repository/images/append_mode_ani.png)
FreeBox, are you french, like me ;)

**Comment by cbtsgithub** [comment]
Super !!
Merci à vous. Et encore bravo pour ce plugin exceptionnel !!
Cordialement
