### ISSUE TITLE
Metrics Documentation Update

### ISSUE THREAD

**Issue by nwies** [algenty/grafana-flowcharting#72]
hello,

Could you please update the documentation regarding the metrics?
With last version grafana, I'm not able to define alias.
I'm trying to define a flow chart from a prometheus db.

Thanks for your help

**Comment by algenty** [comment]
Hi nwies,
yes documentation is not up to date, I'll try

**Comment by nwies** [comment]
Hello,

Could you share the template Json file of the picture "animated_tech_small.png"?
Maybe I can understand how it should be working into lastest grafana version and help you to update the documentation.

**Comment by algenty** [comment]
have you try https://algenty.github.io/flowcharting-repository/STARTED.html ?

**Comment by nwies** [comment]
Yes,
I'm stuck at the metrics definition.
With the new grafana layout, I can't define "scenario" as in picture "getting_started_metrics.png".
As I understand, I must define the database as "grafana"; but after I only have "test data :random walk" on the query zone.

**Comment by algenty** [comment]
random walk is an example,
Define your prometheus metrics in queries and in mapping select your metrics and apply it on chapes

**Comment by nwies** [comment]
Thanks for the explaination.
I was able to define the queries(not able to create alias for it), then apply rules to the differents shapes.
You will find as attachement the queries and the rules (grafana_flowchart1.png) and the basic result (grafana_flowchart2.png)
I create a flowchart for a windows exporter system only for a "UP" status
![grafana_flowchart1](https://user-images.githubusercontent.com/10389749/68163386-b1677e00-ff5a-11e9-832e-532dc0580142.PNG)
![grafana_flowchart2](https://user-images.githubusercontent.com/10389749/68163397-b5939b80-ff5a-11e9-8633-dd0b536ab811.PNG)

feel free to use it for the documentation if needed.
Thanks a lot for your help

**Comment by algenty** [comment]
you're welcome,
good luck
