### ISSUE TITLE
Report last timestamp of a metric

### ISSUE THREAD

**Issue by klu03rl** [algenty/grafana-flowcharting#74]
Firstly love Grafana flowcharting! great job @algenty 

At the moment for some application availability and data flow monitoring I have, I am not able with flowcharting to be able to report the timestamp of the last metric from an InfluxDB data source. 

Within Singlestat is possible from 4.6.0, configured though the stat value, it would be great if a similar feature could be implemented into flowcharting.
![Singlestat - capabilities

![Use case and Influx query](https://user-images.githubusercontent.com/34960207/68328466-3c658700-00c7-11ea-88c9-d22eb77bc1ba.PNG)
![Singlestat - capabilities](https://user-images.githubusercontent.com/34960207/68328472-3ec7e100-00c7-11ea-8f37-ace59b2b0bcb.png)

**Comment by algenty** [comment]
Hi @klu03rl 
Thx for this compliment,
It's a good idea, i add it into the roadmap
BR
Arnaud

**Comment by algenty** [comment]
implemented in 0.9.0
