### ISSUE TITLE
Plugin doesn't load correctly

### ISSUE THREAD

**Issue by jonthekiller** [algenty/grafana-flowcharting#75]
On Grafana 6.5.0, I tried to use the Flowcharting plugin, version 0.5.0 installed from Grafana CLI inside a Docker image but when I select the Flowcharting Vizualisation, the interface doesn't load completely and I can't configure anything.
I can see inside the Javascript console the following error:

<img width="1662" alt="Flowcharting" src="https://user-images.githubusercontent.com/5202324/68396829-78a1f180-0172-11ea-92f6-e9c2a8c54951.png">

An idea how to fix it?

**Comment by algenty** [comment]
Hi
Yes, i have the same, but 6.5 of grafana is a nighty build, not stable.
BR 
Arnaud

**Comment by algenty** [comment]
FI,
https://github.com/grafana/grafana/issues/20255
thx for your attention

BR
Arnaud

**Comment by algenty** [comment]
I found a bypass

**Comment by algenty** [comment]
try 0.6.0 in download section in documentation
