### ISSUE TITLE
Timestamp in tooltip abreviates minutes and seconds to one digit when < 10

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#77]
Hi Arnaud,
I noticed something odd with the timestamps presented in the tooltip. When the time is for example 9:05:06, the timestamp in the tooltip is abbreviated to 9:5:6 which looks very odd.
I checked the normal behavior for dates in e.g. the graph panel, and it doesn't abbreviate timestamps like this.
Kind regards,
Dennis

**Comment by algenty** [comment]
Fixed in next version, push comming soon

**Comment by algenty** [comment]
new 0.6.0 available

**Comment by bijwaard** [comment]
Hi Arnaud,
The timestamps look great now! Thanks
Kind regards,
Dennis

**Comment by algenty** [comment]
👍
