### ISSUE TITLE
Use variable for draw.io page

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#78]
Hi Arnaud,

I noticed you added 'Variables support in download input url' to the 0.60 snapshot. To get this to work, I guess you would enable "download source" and configure URL like http://\<source\>:\<port\>/\<pathToXml\> with a variable in the pathToXml such as path/\[\[my file selection\]\].xml in the download link.

I was wondering if it would also be possible to change the draw.io page. This would allow to change the flowchart without downloading and/or to select an alternative page in the downloaded source.

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi Dennis
It's already possible in 0.6.0 see change log at 
https://algenty.github.io/flowcharting-repository/CHANGELOG.html

**Comment by bijwaard** [comment]
Hi Arnaud,

I have seen URL for diagram download in the changelog, but not selecting a page within a diagram. See https://about.draw.io/multiple-pages-per-diagram/

Kind regards,
Dennis

⁣Sent from TypeApp ​

**Comment by algenty** [comment]
it not works like this page, it downloads ${var}.xml when $var changes

**Comment by bijwaard** [comment]
Hi Arnaud,

Then I guessed correctly above for the usage of the variable in the URL;-)

My question remains, can flowcharting also support selecting a page within a diagram, when the diagram itself has multiple pages (see https://about.draw.io/multiple-pages-per-diagram/)?


Kind regards,
Dennis

**Comment by algenty** [comment]
I understood, but I answered wrong. 
Multi page is not supported at this time
Maybe, a day in a next version. the roadmap is already well filled out ;)
