### ISSUE TITLE
Postgresql metrics and Flowcharting

### ISSUE THREAD

**Issue by mridude23** [algenty/grafana-flowcharting#79]
Hi Arnaud,

I'm having an issue that i can't seem to get around when using Postgresql as a datasource.
Consider the following:
![image](https://user-images.githubusercontent.com/35563212/68705264-6bcc3600-0596-11ea-8121-42a36b96e902.png)

I'm trying to get the total number of alerts with those specific clauses. For me the time column is not important, I could use the query without it, but it seems it's not working.
How do I assign the count(*) value from the metric to the Rule mapping section?
![image](https://user-images.githubusercontent.com/35563212/68705499-ded5ac80-0596-11ea-9406-e83871253670.png)

What I would like to get is something along these lines:
`select count(*) from alerts  where resource = 'server_name' and status = 'open' and severity = 'critical'`
- which would give a number and which I would like to assign to the no_of_alerts variable.

**Comment by algenty** [comment]
Hi,
transform your count(*) by * and select count in rule

BR,
Arnaud

**Comment by mridude23** [comment]
I'm not sure I understand.
![image](https://user-images.githubusercontent.com/35563212/68843132-480d0b00-06d0-11ea-9d46-21b6b238771a.png)

This is my query that I'm trying to run. Is this what you are referring to? 
Also when trying to `Apply to metrics named` i cannot reference the query I wrote before. This seems to be step that I cannot seem to find a solution.

**Comment by algenty** [comment]
Today, only timeseries is supported, i don't see timestamp in your query

**Comment by mridude23** [comment]
So ok, even if only timeseries is supported, is there a posibility to group all results into only 1 value?
Say I'm using the first iteration of the query:
```
SELECT
  floor(extract(epoch from last_receive_time)/60)*60 AS "time",
  count(*) AS "no_of_alerts"
FROM alerts
WHERE
  resource = 'server_name' AND
  status = 'open' AND
  severity = 'warning'
GROUP BY 1
ORDER BY 1
```
This one is a timeseries one, but it returns more than 1 row. Can I make it somehow return only 1 row that gives me the 3 alerts I actually have? 
I don't need for it to be a table or something else, my only goal is to somehow get **all** alerts at once, not 3 rows separately.

**Comment by algenty** [comment]
For me, your request seems good but i see in query inspector : serie : null, table are not supported at this time in GF. maybe in next version

**Comment by mridude23** [comment]
I see. So it's more Grafana related that this plugin. 
As a side note: Would it be possible to implement for the Postgresql datasource the ability to just have a simple query? Without any time constraints.

Here's an example of how the Singlestat dashboard works:
![image](https://user-images.githubusercontent.com/35563212/68943081-d78aea80-07b2-11ea-9da2-8fdd12f5b72b.png)
![image](https://user-images.githubusercontent.com/35563212/68943106-ee314180-07b2-11ea-8f7b-95260964ca31.png)

This is how I use the Postgres where Grafana stores the alerts so that it gives me only a number. 

Would it be possible for you to 'enhance' the flowcharting plugin, to mimic this behaviour.

**Comment by algenty** [comment]
Yes, 
I think in the next version, i'll try to implement tables (i hope,) but at this time, i need to migration GF with grafana-toolit for more compatibility with grafana.

**Comment by mridude23** [comment]
Ok, thanks for taking your time explaining.

**Comment by algenty** [comment]
Hi @mridude23,
I begin the dev of support table, are you ok to test it next time ?

BR
Arnaud

**Comment by algenty** [comment]
Hi @mridude23 
Can you try experimental version at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by mridude23** [comment]
Hi @algenty, 

Sorry, I was out and without access. I will be testing in the next few days and will come back with news.

Thank you.
