### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by newtekpog** [algenty/grafana-flowcharting#8]
Good morning

Thank you for this great plugins.

The attached shape render nice in draw.io but a bit different in this plugin.

[shape.txt](https://github.com/algenty/grafana-flowcharting/files/3073896/shape.txt)

Can you have a look please.

Thank you

Sylvain

**Comment by algenty** [comment]
Hi Sylvain,
thx for using flowcharting and thx for you comment.
I know, custom stencils (libs) not work for moment only basic shape are suported at this time. custom stencil support is in the roadmap in 0.4 or 0.5.
How have you added this shape in draw.io ? give me a picture plz

Best reguards
Arnaud

**Comment by newtekpog** [comment]
Hi Arnaud

Thanks for reply.

First this is .vsd shape

I dropped in the scratchpad area and add to new shapes to the drawing.

Delete all unwanted icons and keep one and the > extra > edit diagram

Br

Sylvain

[image: image.png]

Le ven. 12 avr. 2019 à 16:22, Arnaud GENTY <notifications@github.com> a
écrit :

**Comment by newtekpog** [comment]
Sorry I reply with gmail , nothing uploaded

[Vyatta_icon_set.zip](https://github.com/algenty/grafana-flowcharting/files/3074003/Vyatta_icon_set.zip)
![draw io](https://user-images.githubusercontent.com/49564248/56049412-51e91d00-5d41-11e9-9a39-cdebfacb77c7.png)

**Comment by newtekpog** [comment]
Finally I clean and ungroup it in Inskape, draged the svg to Draw.io and the rendering is correct in the plugin

![2019-04-12 16_55_52-New dashboard - Grafana](https://user-images.githubusercontent.com/49564248/56050506-008e5d00-5d44-11e9-85d8-b4b998bfe2af.png)

[switch-shape.txt](https://github.com/algenty/grafana-flowcharting/files/3074083/switch-shape.txt)

**Comment by algenty** [comment]
ok, ill try to reproduce it
Thx for your feedback

**Comment by algenty** [comment]
Sylvain,
I'll need feedback of my young plugin, i am not a developer, just an ingeneer production.
i'll need opinion, suggestion to improve quality service.
Are you french ?

**Comment by algenty** [comment]
Hi,
Try this version
https://github.com/algenty/grafana-flowcharting/files/3129320/agenty-flowcharting-panel-0.3.0-SNAPSHOT.zip

**Comment by newtekpog** [comment]
Bonjour

Merci pour la maj je testerai asap.

Sylvain

**Comment by algenty** [comment]
Forget version above, too more bugs
try 0.3.0 instead
https://github.com/algenty/flowcharting-repository/tree/master/archives

**Comment by algenty** [comment]
Hi Sylvain
In version 0.4.0, i have added all libs/form from draw.io.
Can you try it ?
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BG
Arnaud

**Comment by newtekpog** [comment]
Hi Arnaud

Of course I ll give a try

Thank you

Br

Sylvain
