### ISSUE TITLE
Flash shape color

### ISSUE THREAD

**Issue by QualityAgileFlow** [algenty/grafana-flowcharting#80]
Hi, our graph uses colored lines (see #73). which get another color on warning/critical. It would be great if there is an option to flash the color (switch between original color and warning/critial color e.g. every sec).

**Comment by algenty** [comment]
Hi, I will add an option to disable this animation

BR
Arnaud

**Comment by QualityAgileFlow** [comment]
Hi Arnaud, did I miss something that the flash-animation is already available? Cause you wrote "option to disable this animation". To clarify: On warning or critital I want the shape to flash alternatig with warning/original color like a signal light ;-) 
Best regards

**Comment by algenty** [comment]
Okay, I didn't understand, today you can check state icon in rules 
I'll add your feature in roadmap

**Comment by algenty** [comment]
Hi @QualityAgileFlow,
What's new ?
For information 0.8.0, blink is implemented, only alpha at this time
https://user-images.githubusercontent.com/47012725/79608514-723a7d00-80f5-11ea-99d1-ef72e40299cd.png
