### ISSUE TITLE
Problem using URL

### ISSUE THREAD

**Issue by mariuszlewandowski13** [algenty/grafana-flowcharting#81]
Hi, I have a problem while loading XML content from external source ("Download source" checked). Downloading works fine, I'm saving the dashboard and when I'm refreshing the page, It loads me the graph from "Source content". As if option "Download source" wasn't checked (but it is).

**Comment by algenty** [comment]
Hi @mariuszlewandowski13 
This bug is fix in next version
Try 0.6.0 at https://algenty.github.io/flowcharting-repository/ARCHIVES.html

BR
Arnaud
