### ISSUE TITLE
Inspector does not show anything

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#82]
Hi Arnaud,

I just tried to enable the inspector, and no elements are shown with the 0.6.0-20191104 snapshot.
The objects are still highlighted in the mapping rules.

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi,
Yes, i saw it.
i'll fix it after migration in typescript

**Comment by algenty** [comment]
Hi Dennis @bijwaard,

Can you try the lastest version, plz,
Many change, but not visual, migrate to typescript, new engine of graph.
Log scale is available, new design of rules

BR
Arnaud

**Comment by algenty** [comment]
Fixed in last 0.6.0

**Comment by bijwaard** [comment]
Hi Arnaud,
Thanks for the update, everything still seems to be working, and the inspector is back, thanks!
I can now configure the logarithmic scale, no visual change yet indeed;-)

The inspector doesn't show something usable for me in the label/name column yet, because of my placeholders, see also ticket #50.

Kind regards,
Dennis

**Comment by algenty** [comment]
Cool,
Thx for your feeback
