### ISSUE TITLE
Tooltip does not show graph

### ISSUE THREAD

**Issue by digitecnodata** [algenty/grafana-flowcharting#83]
On grafana 6.4.2 I updated the plugin to 0.5.0 release and I configured the rules to show the graph on tooltip but I have the tooltip like in the pictures without graph.
What can I do?

Thanks

![flowcharting](https://user-images.githubusercontent.com/54400801/68953115-8504fa80-07c1-11ea-9fe2-5ae1b5a36d1e.png)

**Comment by algenty** [comment]
Hi @digitecnodata,
whoo!!, can you verify in query instector if you have several metrics ? 
What is the type of datasource ? 

BR
Arnaud

**Comment by digitecnodata** [comment]
Hi Arnaud and thanks for your reply.
I use influxdb as datasource and in this case I have several metrics but I tested with a query with only one metric and I have the same problem.
![flowcharting1](https://user-images.githubusercontent.com/54400801/69042167-0b535380-09f1-11ea-8af8-be9ccb7222dd.png)

**Comment by algenty** [comment]
You have only on line, then graph displays only one point
Do not write your query with aggregation like count, min, max
write it like :
select cpu from measure where ... group by ...
and in rule, select your aggregation like current, last, ...

BR
Arnaud

**Comment by romainlaisne** [comment]
There could also be the issue that in Drawio/Diagram.net, a shape is in front of the shape where we want the tooltip. In this situation the tooltip does not work!

**Comment by algenty** [comment]
ok, can you give me your xml definition ?

**Comment by romainlaisne** [comment]
For me the issue was with the drawio diagram. I have remove the shape in front of the one I expected to show a tooltip. Now it works.
