### ISSUE TITLE
Multiple series aggregations

### ISSUE THREAD

**Issue by sekomarek** [algenty/grafana-flowcharting#84]
Hello,

Is it possible to calculate aggregations from multiple series? I have a query named "A", which is returning array of 7 series. In plugin I set mapping for all "A" series with regex, and aggregation "Avg". But displayed value is last value from series returned by query. Also color is different for value in tooltip (correct according to thresholds) and circle on map (incorrect according to thresholds).

![mapping](https://user-images.githubusercontent.com/9357440/69253438-f0314100-0bb4-11ea-9251-f84f9254d862.png)
![series](https://user-images.githubusercontent.com/9357440/69253439-f0314100-0bb4-11ea-90a8-00e7ef9fc3d0.png)

I am using InfluxDB 1.7.4 and Grafana 6.2.5

Thank you for your response, and awesome plugin.
Best regards,
Marek.

**Comment by algenty** [comment]
2 possibilities :
1) Use regex in metric name, i see in your screen the name of querie doesn't content A, case sensitive.
2) Create 7 rules with one metric and target the same shape (circle).

BR
Arnaud

**Comment by algenty** [comment]
I forget : Hi, thx for your feedback :)
