### ISSUE TITLE
Enhance Text to Value to report a fixed string based upon a integer metric

### ISSUE THREAD

**Issue by klu03rl** [algenty/grafana-flowcharting#86]
Hi Arnaud

I am using flowchart to report the status of my automation test results for application functional testing. At the moment in InfluxDB I am saving my test result as a 0 for fail and 1 for Pass. This is allowing me to have a simple query to be able to apply rules for test case count, Average pass rate and last result. 

Test result count and Test Pass rate work great, but at the moment within my dashboard I am only able to have my last test result displayed as a 0 or 1. 
It would be great if the text to value function could be enhanced to so that based on the integer value of the test result I would be able to report correlated string within my Dashboard.
so would need a new rule option for this I believe.

Thanks

Richard

**Comment by algenty** [comment]
Hi Richard,
in your first rule, with 1 or 0, select string unit and use Value Map to convert it
1 => OK
0 => KO
In a second rule, select the same metric and select avg, in unit select percent and put it in in text mapping in other shape, active tooltip with graph, you can see when it is down or up.

BR
Arnaud

**Comment by klu03rl** [comment]
Thanks Arnaud

This works as needed - Keep up the great work with Flowcharting! We are planning to use it across out organisation
