### ISSUE TITLE
Grafana 6.5.x Flowchart Plugin is broken

### ISSUE THREAD

**Issue by HaveFun83** [algenty/grafana-flowcharting#89]
Hi 
the flowchart plugin is broken on the newest grafana release 6.5.x.

![Bildschirmfoto_2019-11-26_17-10-53](https://user-images.githubusercontent.com/38665716/69651169-f8cfbe80-106f-11ea-8472-41687746324b.png)

**Comment by algenty** [comment]
Hi,
same issue that, i close it
https://github.com/algenty/grafana-flowcharting/issues/88
