### ISSUE TITLE
diagram editor breaks hyperlinks

### ISSUE THREAD

**Issue by teunvink** [algenty/grafana-flowcharting#9]
I'm testing the version mentioned in https://github.com/algenty/grafana-flowcharting/issues/7
One thing I noticed that changed since the previous version I used (which was installed with grafana-cli) is that hyperlinks on objects in the diagram don't work anymore.

For example:
`<mxGraphModel dx="492" dy="577" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
    <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <UserObject label="" link="https://grafana.com" id="2">
            <mxCell style="rounded=0;whiteSpace=wrap;html=1;" vertex="1" parent="1">
                <mxGeometry x="120" y="40" width="120" height="50" as="geometry"/>
            </mxCell>
        </UserObject>
    </root>
</mxGraphModel>`

used to work in the old version, now the hyperlink isn't clickable anymore. Does the minify/compress function perhaps break this? Looking at the generated HTML, I don't see a hyperlink anymore in the SVG.

**Comment by algenty** [comment]
Hi teunvink,
Thx for your feedback
I'm going to invest this. i think i know the problem.

**Comment by algenty** [comment]
Hi @teunvink,
Can you test this alpha, test in progress.
[agenty-flowcharting-panel-0.3.0-SNAPSHOT.zip](https://github.com/algenty/grafana-flowcharting/files/3129320/agenty-flowcharting-panel-0.3.0-SNAPSHOT.zip)

Best reguards,
Arnaud

**Comment by teunvink** [comment]
Hi Arnaud, thanks for the work. Unfortunately, this snapshot doesn't seem to work properly. All existing panels seem to have lost their layout, they are replaced by the default diagram provided by the plugin. I reverted back to the previous version since we rely on these diagrams for network monitoring.

**Comment by algenty** [comment]
Ok, thx for this feedback.
0.3 have many breaking changes.
What is your version ? 0.2 o 0.2.5 ?
Migrate process not work correctly at this time but for a new panel, it work.

**Comment by algenty** [comment]
ok, i know why, i'll correct it

**Comment by teunvink** [comment]
Ok great, let me know if you want me to test something.

**Comment by algenty** [comment]
Try it 0.3.0 in
https://github.com/algenty/flowcharting-repository/tree/master/archives

**Comment by teunvink** [comment]
Thanks for the quick update! The new snapshot seems to work ok. Diagrams are ok and hyperlinks work again.

**Comment by algenty** [comment]
Cool, thx for this back
