### ISSUE TITLE
Support for table data

### ISSUE THREAD

**Issue by nmoreaud** [algenty/grafana-flowcharting#90]
Hello,

Could you please add support for table data ?
Thanks for your work !

**Comment by algenty** [comment]
Hi @nmoreaud,
it's in progress, i'll need beta user to test. are you interrest ?

BR,
Arnaud

**Comment by nmoreaud** [comment]
Yeah, why not.
I can test my use case (zabbix connector, query for triggers data), when it's ready

**Comment by algenty** [comment]
@nmoreaud , Thanks for your contribution.
Can you give me an example of table in query inspector ? (cpu or mem)
Don't forget to hide sensible data like hostname

**Comment by nmoreaud** [comment]
With basic queries for cpu or memory, I get timeseries data.
I've got table formatted data when querying for triggers. 

Here is an example of query inspector result for triggers : 
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1",
    "data": {
      "jsonrpc": "2.0",
      "method": "trigger.get",
      "params": {
        "output": "extend",
        "hostids": [
          "10306"
        ],
        "min_severity": 0,
        "filter": {
          "value": 1
        },
        "expandDescription": true,
        "expandData": true,
        "expandComment": true,
        "monitored": true,
        "skipDependent": true,
        "selectLastEvent": "extend",
        "selectGroups": "extend",
        "selectHosts": [
          "host",
          "name"
        ],
        "lastChangeSince": 1503014670,
        "lastChangeTill": 1575014670
      },
      "id": 1,
      "auth": "85513e9cc329d13c5f2dd79420b9b084"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "triggerid": "16716",
        "expression": "{19597}=1 and {19598}>0",
        "description": "System name has changed (new name: 51740b14486f)",
        "url": "",
        "status": "0",
        "value": "1",
        "priority": "1",
        "lastchange": "1574785641",
        "comments": "System name has changed. Ack to close.",
        "error": "",
        "templateid": "16615",
        "type": "0",
        "state": "0",
        "flags": "0",
        "recovery_mode": "2",
        "recovery_expression": "",
        "correlation_mode": "0",
        "correlation_tag": "",
        "manual_close": "1",
        "opdata": "",
        "groups": [
          {
            "groupid": "2",
            "name": "Linux servers",
            "internal": "0",
            "flags": "0"
          }
        ],
        "hosts": [
          {
            "hostid": "10306",
            "host": "zabbix-agent-2",
            "name": "zabbix-agent-2"
          }
        ],
        "lastEvent": {
          "eventid": "189",
          "source": "0",
          "object": "0",
          "objectid": "16716",
          "clock": "1574785641",
          "value": "1",
          "acknowledged": "0",
          "ns": "641911385",
          "name": "System name has changed (new name: 51740b14486f)",
          "severity": "1"
        }
      }
    ],
    "id": 1
  }
}
```

However, I think that zabbix connector makes a post-treatment on this data.
What is actually passed to the panel seems to be : 
```
[
  {
    "columns": [
      {
        "text": "Host group"
      },
      {
        "text": "Disaster"
      },
      {
        "text": "High"
      },
      {
        "text": "Average"
      },
      {
        "text": "Warning"
      },
      {
        "text": "Information"
      },
      {
        "text": "Not classified"
      }
    ],
    "type": "table",
    "rows": [
      [
        "Linux servers",
        0,
        0,
        0,
        0,
        1,
        0
      ]
    ]
  }
]
```

**Comment by algenty** [comment]
Thx @nmoreaud 
Can you try experimental version at 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by nmoreaud** [comment]
Okay, I just tested it with an SQL datasource.
It seems to work fine with single row results or "aggregetable" datasources (nice !)

I tested another use case : I use a DB query to request multiple server's current state. Each server is described by a row.
Ex : 
```
SELECT 'serverA' as server, 'error' as severity, '<p>Error : cannot reach network XXX</p><p>Information : hostname changed</p>' as messages
union
SELECT 'serverB' as server, 'warning' as severity, '<p>Warning : bad directory permissions : /var/www/serviceB/log/</p>' as messages
union
SELECT 'serverC' as server, 'ok' as severity, '' as messages
```

I would like to assign to draw each server on draw.io and assign their status (color) + messages as tooltip. Do you think I could map cells (row+column) to chart nodes ? (feature request)

Ex : when property("server") = comboBox("serverA"), value("severity") => map to id("1")

**Comment by algenty** [comment]
Hi its already possible
Use grafana $variable instead server A in your Select like it
Select message from table where server=$variable
Use string type in flowcharting and Select current in aggregator
You need a Time column in epoch format for all aggregator

Br
Arnaud

**Comment by algenty** [comment]
Nice screenshot, can i use it in gallery or twitter ?

**Comment by nmoreaud** [comment]
I prefer not, this chart was not coded with flowcharting but with svg panel.
Do you think it is possible to build a similar view with flowcharting-panel with 1 or 2 SQL requests ?

I found a few bugs :
- I cannot delete rules : `GF ERROR : datapoint for table is null TypeError: "this.metrics.stats[e] is undefined"`
- In "Color mapping", when I change the ID, the preview is updated with the previous ID
- When I click on Color with state, the preview is not updated
- I added a property to chart nodes (draw.io > right click, edit data > property "server") but the new property is not detected in the panel editor

I didn't understand how I can link table cell value to a chart node.
If I declare a variable $server, then I can filter the servers to display at dashboard level.
However, I'd like to display all the servers on my chart. I don't try to filter, just to map the data.
Ex : table row("server") = "serverA", table column "severity" => chart node id 1 (color)

I can only make it work if I pivot the table (servers as columns, severity and messages as rows).
Here is a working example, I was only able to manage two rows of data (first and last). [chart-drawio-table-servers.zip](https://github.com/algenty/grafana-flowcharting/files/3921165/chart-drawio-table-servers.zip). Please look at the tooltips.

**Comment by algenty** [comment]
Hi @nmoreaud,

1- How you delete rule ? by the button inside rule or by le cross in rule header ?
In the header, you need to click 2 times to delete it.

2 & 3 need to investigate

4 - Yes server, must be a column, in your dashboard, you can create a variable and combo box
In the xml definition, you can add ${myVariable} in the label or in Value Mapping (Range or value)
See example : 
https://github.com/algenty/flowcharting-repository/blob/master/images/ani_variables_example.png

BR
Arnaud

**Comment by nmoreaud** [comment]
1 - double-click is fine, I missed it
4 - How can I use a custom prop here (instead of id) ?
![add prop](https://user-images.githubusercontent.com/2413781/70145751-1a98f900-16a1-11ea-9610-a04fa1fc3354.jpg)

**Comment by algenty** [comment]
Only id at this time, in next version, you'll can select by value

**Comment by algenty** [comment]
For double click, it is a security for miss clik :)

**Comment by nmoreaud** [comment]
I think that to handle true table data (ex sql requests results), you should add the possibility to map table cells.

Ex : 
![add row filtering](https://user-images.githubusercontent.com/2413781/70228781-45dd2000-1755-11ea-8ec9-c2d6c9fc0396.jpg)
When (column) (operator) (value)
When "server" = "serverC"
When "country" like "Kamerun", etc.

**Comment by algenty** [comment]
For me, type of condition would be in query, not in plugin.
Create 3 requests and 3 rules with Severity like '%SERVER C%'

**Comment by nmoreaud** [comment]
Yeah, it works but I can represent a lot of queries (duplication + performance impact).
Moreover, each query result would be a single row, in other words a list of data, instead of a table.

**Comment by CrashLaker** [comment]
@nmoreaud awesome map chart you've got there.
I'm trying to achieve the same results but I couldnt find a way to **programatically position** it (I'm still loading a buch of SVG shapes and manually positioning them to form a country or continent) and to **dynamically change** its color based on grafana's metrics.

any advice on how to solve these? https://github.com/algenty/grafana-flowcharting/issues/144
