### ISSUE TITLE
Color for connectors based on threshold

### ISSUE THREAD

**Issue by tanuj83** [algenty/grafana-flowcharting#92]
Color Mapping works good if selected ID is associated to "sqaure" shape but it is not changing color for "Directional Connector" ID.

I am creating a flow and my target to change the color of connectors based on threshold
Graph Inspector can show status OK for both ID but no color on Connector ID

In the screenshot the ID 110 is related to connector

![image](https://user-images.githubusercontent.com/22608694/69874248-7d287880-12e0-11ea-881a-cb933f466ce4.png)

![image](https://user-images.githubusercontent.com/22608694/69874069-186d1e00-12e0-11ea-83f9-df60e6859be7.png)

![image](https://user-images.githubusercontent.com/22608694/69874148-4f433400-12e0-11ea-8ca3-97bcf4604926.png)

**Comment by algenty** [comment]
Hi,
What is your version of flowcharting ?

**Comment by tanuj83** [comment]
@algenty
 agenty-flowcharting-panel @ 0.5.0

**Comment by algenty** [comment]
@tanuj83 
If it is a connector, you need to choose "stroke" in "color mode" : 
clone rule, remove you shape and keep connector
select stroke in "color mode", click on "i" in color mode to see example.

In a next version, you can select multiple color mode in one rule.
You can try too 0.6.0 in download section

BR
Arnaud

**Comment by tanuj83** [comment]
@algenty thank you very much, it is great now.
