### ISSUE TITLE
multiple series with single threshold

### ISSUE THREAD

**Issue by tanuj83** [algenty/grafana-flowcharting#93]
when my query was resulting 1 metrics, it was working good with threshold and tooltips and graphs shows good.

now change my query to generate 2 metrics and using regular expression in "Apply to metrics", everything seems normal except few things

1.  I want threshold based on single metric not both metrics as both metrics data is different.
2.  graph is okay to generate both metrics but based on requirement seems better.

**Comment by tanuj83** [comment]
Version 0.5.0

**Comment by algenty** [comment]
You need to create 2 rules for that if definition is different for each

**Comment by tanuj83** [comment]
it works thanks, but I was looking if it can have threshold based on ID in a single rule then it will reduce the number of rules and easy to manage
