### ISSUE TITLE
[Request] Suffix and Prefix for entities

### ISSUE THREAD

**Issue by darox** [algenty/grafana-flowcharting#95]
It would be amazing, to have the ability to add suffix or prefix to entities, like in the grafana panel plugin.

**Comment by algenty** [comment]
Hi @darox 
Like status panel ?
If suffix = °C
and value = 18, you would "18 °C", that is correct ?

**Comment by darox** [comment]
@algenty Exactly! I would like to place a free text before or after the value.

**Comment by algenty** [comment]
you can :
in your text in draw.io, put "VALUE °C" and in text mode, select "replace" with /VALUE/ in expression.

BR
Arnaud

**Comment by darox** [comment]
@algenty Where do I find this " select "replace with /VALUE/" in Grafana. May you share a screenshot?

**Comment by algenty** [comment]
See that : in doc
https://algenty.github.io/flowcharting-repository/images/example_text_pattern.png
