### ISSUE TITLE
Grafana keeps loading when 24+ queries are added

### ISSUE THREAD

**Issue by darox** [algenty/grafana-flowcharting#96]
I have 24 queries in the grafana flowcharting plugin, when I add a 25th grafana keeps loading forever. If I remove the 25th querie, it works again. Therefore I assume that 24+ queries are not supported. Please confirm this behaviour. 

Thanks

**Comment by algenty** [comment]
I don't know, i'll test it, maybe the count of alphabet letter.
What is the type of datasource ?
with influx, you can create queries like select h from /.*/ group by tag
and each tag have a value, you can select one tag in rules

**Comment by algenty** [comment]
Can you open console, and if you have an error ?

**Comment by algenty** [comment]
I have an error in console after Z
Panel data error: TypeError: Cannot read property 'tables' of undefined
    at t.processQueryResult (datasource.ts:70)
    at datasource.ts:56
    at angular.js:17051
    at angular.js:17095
    at c.$digest (angular.js:18232)
    at c.$apply (angular.js:18531)
    at angular.js:18832
    at p (angular.js:6362)
    at angular.js:6642

**Comment by algenty** [comment]
see https://github.com/grafana/grafana/issues/4978

**Comment by darox** [comment]
Can be closed, as the group by workaround helps me.
