### ISSUE TITLE
Click on the image object in flowchart provides drill down details or navigates to a new window/browser instead of showing the details in the same window/browser

### ISSUE THREAD

**Issue by gsreeman** [algenty/grafana-flowcharting#97]
I am looking for the work around or solution to show the drill down details in the same window/browser when clicked on the hyperlink of the objects within the flowchart.   Currently the hyperlink on the objects opening a new browser.

Thanks
Sriman

**Comment by algenty** [comment]
Hi, 
At this time, link open a new tab, maybe in the next version
