### ISSUE TITLE
Optimize rules using metric name as id

### ISSUE THREAD

**Issue by gsahbi** [algenty/grafana-flowcharting#99]
I use a fairly small network interconnect (25 interfaces) and the dashboard started to take 3-4 seconds to load.
it has 50 rules, 2 for each router interface. 
But if you look closely that can be reduced to only one if I put the mxgraph id as the metric name.
example in text mapping I put a variable ${metric_name} and in metric : A.* or vise versa

So basically the rule is  : for every metric in query A map it to id of the same name.

**Comment by algenty** [comment]
try 0.6.0,
